namespace RandomizerTests.Logic.Alttp.Open.NoGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public class SkullWoodsTest : OpenNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Skull Woods - Big Chest", false, new string[] {  }],
        ["Skull Woods - Big Chest", false, new string[] { "TitansMitt", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "TitansMitt", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD3" }],
        ["Skull Woods - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD3" }],

        ["Skull Woods - Big Key Chest", false, new string[] {  }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Skull Woods - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Skull Woods - Compass Chest", false, new string[] {  }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Skull Woods - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Skull Woods - Map Chest", false, new string[] {  }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Skull Woods - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Skull Woods - Bridge Room Chest", false, new string[] {  }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "TitansMitt", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod" }],
        ["Skull Woods - Bridge Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod" }],

        ["Skull Woods - Pot Prison", false, new string[] {  }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Skull Woods - Pot Prison", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Skull Woods - Pinball Chest", false, new string[] {  }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Skull Woods - Pinball Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Skull Woods - Boss", false, new string[] {  }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "TitansMitt", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "TitansMitt", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "TitansMitt", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "TitansMitt", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "TitansMitt", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "FireRod", "ProgressiveSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod", "UncleSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod", "MasterSword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod", "L3Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod", "L4Sword" }],
        ["Skull Woods - Boss", true, new string[] { "KeyD3", "KeyD3", "KeyD3", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "FireRod", "ProgressiveSword" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
