namespace RandomizerTests.Logic.Alttp.Inverted.NoGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public class GanonsTowerTest : InvertedNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Ganon's Tower - Bob's Torch", false, new string[] {  }],
        ["Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "AgahnimDefeated", "PegasusBoots", "TowerEntry" }],
        ["Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "PegasusBoots", "TowerEntry" }],
        ["Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "PegasusBoots", "TowerEntry" }],
        ["Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "PegasusBoots", "TowerEntry" }],
        ["Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "TitansMitt", "PegasusBoots", "TowerEntry" }],

        ["Ganon's Tower - DMs Room - Top Left", false, new string[] {  }],
        ["Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - DMs Room - Top Right", false, new string[] {  }],
        ["Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - DMs Room - Bottom Left", false, new string[] {  }],
        ["Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - DMs Room - Bottom Right", false, new string[] {  }],
        ["Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Randomizer Room - Top Left", false, new string[] {  }],
        ["Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Randomizer Room - Top Right", false, new string[] {  }],
        ["Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Randomizer Room - Bottom Left", false, new string[] {  }],
        ["Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Randomizer Room - Bottom Right", false, new string[] {  }],
        ["Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Firesnake Room", false, new string[] {  }],
        ["Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Map Chest", false, new string[] {  }],
        ["Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Big Chest", false, new string[] {  }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Hope Room - Left", false, new string[] {  }],
        ["Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "TowerEntry" }],

        ["Ganon's Tower - Hope Room - Right", false, new string[] {  }],
        ["Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "TowerEntry" }],
        ["Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "TowerEntry" }],

        ["Ganon's Tower - Bob's Chest", false, new string[] {  }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Tile Room Chest", false, new string[] {  }],
        ["Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "TitansMitt", "CaneOfSomaria", "TowerEntry" }],

        ["Ganon's Tower - Compass Room - Top Left", false, new string[] {  }],
        ["Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "TowerEntry" }],

        ["Ganon's Tower - Compass Room - Top Right", false, new string[] {  }],
        ["Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "TowerEntry" }],

        ["Ganon's Tower - Compass Room - Bottom Left", false, new string[] {  }],
        ["Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "TowerEntry" }],

        ["Ganon's Tower - Compass Room - Bottom Right", false, new string[] {  }],
        ["Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "TowerEntry" }],
        ["Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "TowerEntry" }],

        ["Ganon's Tower - Big Key Chest", false, new string[] {  }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Big Key Room - Left", false, new string[] {  }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Big Key Room - Right", false, new string[] {  }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "TowerEntry" }],
        ["Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "TowerEntry" }],

        ["Ganon's Tower - Mini Helmasaur Room - Left", false, new string[] {  }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "TowerEntry" }],

        ["Ganon's Tower - Mini Helmasaur Room - Right", false, new string[] {  }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "TowerEntry" }],

        ["Ganon's Tower - Pre-Moldorm Chest", false, new string[] {  }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "TowerEntry" }],

        ["Ganon's Tower - Moldorm Chest", false, new string[] {  }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Lamp", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "FireRod", "TowerEntry" }],
        ["Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "FireRod", "TowerEntry" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
