namespace RandomizerTests.Logic.Alttp.Inverted.NoGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public class IcePalaceTest : InvertedNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Ice Palace - Big Key Chest", false, new string[] {  }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],

        ["Ice Palace - Compass Chest", false, new string[] {  }],
        ["Ice Palace - Compass Chest", false, new string[] { "FireRod" }],
        ["Ice Palace - Compass Chest", false, new string[] { "Flippers" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bombos", "L4Sword" }],

        ["Ice Palace - Map Chest", false, new string[] {  }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Flippers", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],

        ["Ice Palace - Spike Room", false, new string[] {  }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "FireRod", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "Bombos", "UncleSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "Bombos", "MasterSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "Bombos", "L3Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "Bombos", "L4Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "FireRod", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "Bombos", "UncleSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "Bombos", "ProgressiveSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "Bombos", "MasterSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "Bombos", "L3Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Flippers", "Bombos", "L4Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "FireRod", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "Bombos", "UncleSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "Bombos", "ProgressiveSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "Bombos", "MasterSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "Bombos", "L3Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Flippers", "Bombos", "L4Sword", "KeyD5", "KeyD5" }],


        ["Ice Palace - Freezor Chest", false, new string[] {  }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bombos", "L4Sword" }],

        ["Ice Palace - Iced T Room", false, new string[] {  }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Flippers", "Bombos", "L4Sword" }],

        ["Ice Palace - Big Chest", false, new string[] {  }],
        ["Ice Palace - Big Chest", false, new string[] { "Flippers", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bombos", "L4Sword" }],

        ["Ice Palace - Boss", false, new string[] {  }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Flippers", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
