namespace RandomizerTests.Logic.Alttp.Inverted.NoGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public class PalaceOfDarknessTest : InvertedNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Palace of Darkness - Big Key Chest", false, new string[] {  }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Hammer" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Big Key Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - The Arena - Ledge", false, new string[] {  }],
        ["Palace of Darkness - The Arena - Ledge", false, new string[] { "Flippers" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "Flippers" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "Hammer" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - The Arena - Ledge", true, new string[] { "BowAndArrows", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - The Arena - Bridge Ledge Chest", false, new string[] {  }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "Flippers" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "Hammer" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "KeyD1", "MagicMirror", "AgahnimDefeated" }],
        ["Palace of Darkness - The Arena - Bridge Ledge Chest", true, new string[] { "BowAndArrows", "Hammer" }],

        ["Palace of Darkness - Big Chest", false, new string[] {  }],
        ["Palace of Darkness - Big Chest", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Flippers" }],
        ["Palace of Darkness - Big Chest", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Big Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Compass Chest", false, new string[] {  }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Hammer" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Compass Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Harmless Hellway Chest", false, new string[] {  }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Hammer" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Harmless Hellway Chest", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Stalfos Basement Chest", false, new string[] {  }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "Flippers" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "Hammer" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "KeyD1", "MagicMirror", "AgahnimDefeated" }],
        ["Palace of Darkness - Stalfos Basement Chest", true, new string[] { "BowAndArrows", "Hammer" }],

        ["Palace of Darkness - Dark Basement - Left", false, new string[] {  }],
        ["Palace of Darkness - Dark Basement - Left", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Basement - Left", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Dark Basement - Right", false, new string[] {  }],
        ["Palace of Darkness - Dark Basement - Right", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Basement - Right", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Map Chest", false, new string[] {  }],
        ["Palace of Darkness - Map Chest", false, new string[] { "Flippers" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "Flippers" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "Hammer" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Map Chest", true, new string[] { "BowAndArrows", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Dark Maze - Top", false, new string[] {  }],
        ["Palace of Darkness - Dark Maze - Top", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Maze - Top", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Dark Maze - Bottom", false, new string[] {  }],
        ["Palace of Darkness - Dark Maze - Bottom", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Flippers" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Flippers" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Dark Maze - Bottom", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Shooter Room Chest", false, new string[] {  }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "Flippers" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "Hammer" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "OcarinaInactive", "MoonPearl", "AgahnimDefeated" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "MagicMirror", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "MagicMirror", "MoonPearl", "TitansMitt" }],
        ["Palace of Darkness - Shooter Room Chest", true, new string[] { "MagicMirror", "AgahnimDefeated" }],

        ["Palace of Darkness - Boss", false, new string[] {  }],
        ["Palace of Darkness - Boss", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "Hammer" }],
        ["Palace of Darkness - Boss", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "BowAndArrows" }],
        ["Palace of Darkness - Boss", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Hammer", "BowAndArrows" }],
        ["Palace of Darkness - Boss", false, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "Lamp", "Hammer", "BowAndArrows" }],
        ["Palace of Darkness - Boss", true, new string[] { "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "KeyD1", "BigKeyD1", "Lamp", "Hammer", "BowAndArrows" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
