namespace RandomizerTests.Logic.Alttp.Inverted.OverworldGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public sealed class IcePalaceTest : InvertedOverworldGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Ice Palace - Big Key Chest", false, new string[] {  }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],

        ["Ice Palace - Compass Chest", false, new string[] {  }],
        ["Ice Palace - Compass Chest", true, new string[] { "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Bombos", "L4Sword" }],

        ["Ice Palace - Map Chest", false, new string[] {  }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "PowerGlove", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "CaneOfByrna", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Cape", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],

        ["Ice Palace - Spike Room", false, new string[] {  }],
        ["Ice Palace - Spike Room", true, new string[] { "FireRod", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Bombos", "UncleSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Bombos", "MasterSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Bombos", "L3Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Bombos", "L4Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "FireRod", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Bombos", "UncleSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Bombos", "ProgressiveSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Bombos", "MasterSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Bombos", "L3Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Cape", "Bombos", "L4Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "FireRod", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Bombos", "UncleSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Bombos", "ProgressiveSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Bombos", "MasterSword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Bombos", "L3Sword", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "CaneOfByrna", "Bombos", "L4Sword", "KeyD5", "KeyD5" }],

        ["Ice Palace - Freezor Chest", false, new string[] {  }],
        ["Ice Palace - Freezor Chest", true, new string[] { "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Bombos", "L4Sword" }],

        ["Ice Palace - Iced T Room", false, new string[] {  }],
        ["Ice Palace - Iced T Room", true, new string[] { "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "Bombos", "L4Sword" }],

        ["Ice Palace - Big Chest", false, new string[] {  }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Bombos", "L4Sword" }],

        ["Ice Palace - Boss", false, new string[] {  }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "ProgressiveGlove", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "PowerGlove", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "TitansMitt", "BigKeyD5", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
    ];
}
