//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
//     Loosely based on https://github.com/jsongraph/json-graph-specification (without hyper edges)
// </auto-generated>
//----------------------


namespace Randomizer.Graph.Json;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
public partial class JsonGraph
{

    [System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("label")]
    public string Label { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("directed")]
    public bool? Directed { get; set; } = true;

    [System.Text.Json.Serialization.JsonPropertyName("type")]
    public string Type { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("metadata")]
    public object Metadata { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("nodes")]
    public System.Collections.Generic.IDictionary<string, JsonNode> Nodes { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("edges")]
    public System.Collections.Generic.ICollection<JsonEdge> Edges { get; set; }

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
public partial class JsonNode
{
    [System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("label")]
    public string Label { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("metadata")]
    public object Metadata { get; set; }

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
public partial class JsonEdge
{

    [System.Text.Json.Serialization.JsonPropertyName("id")]
    public string Id { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("source")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Source { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("target")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Target { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("relation")]
    public string Relation { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("directed")]
    public bool? Directed { get; set; } = true;

    [System.Text.Json.Serialization.JsonPropertyName("label")]
    public string Label { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("metadata")]
    public object Metadata { get; set; }

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.5.1.0 (Newtonsoft.Json v13.0.0.0)")]
public partial class JsonRoot
{

    [System.Text.Json.Serialization.JsonPropertyName("graph")]
    [System.ComponentModel.DataAnnotations.Required]
    public JsonGraph Graph { get; set; } = new JsonGraph();

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }

}
