using AlttpRandomizer.Graph;

namespace RandomizerTests.Logic.Inverted.NoGlitches;

[TestClass]
public class GanonsTowerTest
{
    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Ganon's Tower - Bob's Torch", false, new string[] {  } },
        new object[] { "Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "AgahnimDefeated", "PegasusBoots", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "PegasusBoots", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "PegasusBoots", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "PegasusBoots", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Torch", true, new string[] { "MoonPearl", "TitansMitt", "PegasusBoots", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - DMs Room - Top Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - DMs Room - Top Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Top Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - DMs Room - Bottom Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - DMs Room - Bottom Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - DMs Room - Bottom Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Randomizer Room - Top Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Randomizer Room - Top Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Randomizer Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Firesnake Room", false, new string[] {  } },
        new object[] { "Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Firesnake Room", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Map Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Map Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Big Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Chest", true, new string[] { "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Hope Room - Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Left", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Hope Room - Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Hope Room - Right", true, new string[] { "MoonPearl", "TitansMitt", "Hookshot", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Bob's Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Bob's Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Tile Room Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Tile Room Chest", true, new string[] { "MoonPearl", "TitansMitt", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Compass Room - Top Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Compass Room - Top Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Top Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Compass Room - Bottom Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Compass Room - Bottom Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Compass Room - Bottom Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "CaneOfSomaria", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Big Key Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Chest", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Big Key Room - Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Left", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Big Key Room - Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "UncleSword", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "CaneOfSomaria", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Big Key Room - Right", true, new string[] { "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Hammer", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", false, new string[] {  } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Left", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", false, new string[] {  } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Mini Helmasaur Room - Right", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Pre-Moldorm Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Pre-Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },

        new object[] { "Ganon's Tower - Moldorm Chest", false, new string[] {  } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "Lamp", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "AgahnimDefeated", "Hookshot", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hookshot", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
        new object[] { "Ganon's Tower - Moldorm Chest", true, new string[] { "BowAndArrows", "UncleSword", "BigKeyA2", "KeyA2", "KeyA2", "KeyA2", "KeyA2", "MoonPearl", "TitansMitt", "Hookshot", "FireRod", "Crystal1", "Crystal2", "Crystal3", "Crystal4", "Crystal5", "Crystal6", "Crystal7" } },
    };
    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void TestLogic(string location, bool expected, string[] inventory)
    {
        var randomizer = new Randomizer(new[]
        {
            new RandomizerConfig
            {
                Glitches = GlitchesOption.None,
                State = StateOption.Inverted,
            }
        });
        randomizer.AssumeItems(inventory.Select(i => Item.Get(i, 0)));
        Assert.AreEqual(expected, randomizer.CanReachLocation($"{location}:0"));
    }
}
