namespace RandomizerTests.Logic.Inverted.NoGlitches;

[TestClass]
public class LightWorldTest : InvertedNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Master Sword Pedestal", false, new string[] {  }],
        ["Master Sword Pedestal", false, new string[] { "PendantOfWisdom", "PendantOfPower", "AgahnimDefeated" }],
        ["Master Sword Pedestal", false, new string[] { "PendantOfCourage", "PendantOfPower", "AgahnimDefeated" }],
        ["Master Sword Pedestal", false, new string[] { "PendantOfCourage", "PendantOfWisdom", "AgahnimDefeated" }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "AgahnimDefeated" }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "TitansMitt" }],

        ["Link's Uncle", false, new string[] {  }],
        ["Link's Uncle", false, new string[] { "AgahnimDefeated" }],
        ["Link's Uncle", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Link's Uncle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Link's Uncle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Link's Uncle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Link's Uncle", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Secret Passage", false, new string[] {  }],
        ["Secret Passage", false, new string[] { "AgahnimDefeated" }],
        ["Secret Passage", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Secret Passage", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Secret Passage", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Secret Passage", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Secret Passage", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["King's Tomb Chest", false, new string[] {  }],
        ["King's Tomb Chest", false, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["King's Tomb Chest", false, new string[] { "PegasusBoots", "ProgressiveGlove", "MoonPearl" }],
        ["King's Tomb Chest", false, new string[] { "PegasusBoots", "ProgressiveGlove", "ProgressiveGlove" }],
        ["King's Tomb Chest", true, new string[] { "PegasusBoots", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["King's Tomb Chest", true, new string[] { "PegasusBoots", "TitansMitt", "MoonPearl" }],

        ["Floodgate Chest", false, new string[] {  }],
        ["Floodgate Chest", false, new string[] { "AgahnimDefeated" }],
        ["Floodgate Chest", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Floodgate Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Floodgate Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Floodgate Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Floodgate Chest", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Tavern Item", false, new string[] {  }],
        ["Kakariko Tavern Item", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Tavern Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Tavern Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Tavern Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Tavern Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Tavern Item", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Chicken House Item", false, new string[] {  }],
        ["Chicken House Item", false, new string[] { "AgahnimDefeated" }],
        ["Chicken House Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Chicken House Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Chicken House Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Chicken House Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Chicken House Item", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Aginah's Cave - Chest", false, new string[] {  }],
        ["Aginah's Cave - Chest", false, new string[] { "AgahnimDefeated" }],
        ["Aginah's Cave - Chest", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Aginah's Cave - Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Aginah's Cave - Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Aginah's Cave - Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Aginah's Cave - Chest", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Sahasrahla's Hut - Left", false, new string[] {  }],
        ["Sahasrahla's Hut - Left", false, new string[] { "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Sahasrahla's Hut - Middle", false, new string[] {  }],
        ["Sahasrahla's Hut - Middle", false, new string[] { "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Sahasrahla's Hut - Right", false, new string[] {  }],
        ["Sahasrahla's Hut - Right", false, new string[] { "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Well - Top", false, new string[] {  }],
        ["Kakariko Well - Top", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Well - Left", false, new string[] {  }],
        ["Kakariko Well - Left", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Well - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Well - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Well - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Well - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Well - Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Well - Middle", false, new string[] {  }],
        ["Kakariko Well - Middle", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Well - Middle", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Well - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Well - Middle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Well - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Well - Middle", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Well - Right", false, new string[] {  }],
        ["Kakariko Well - Right", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Well - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Well - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Well - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Well - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Well - Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Kakariko Well - Bottom", false, new string[] {  }],
        ["Kakariko Well - Bottom", false, new string[] { "AgahnimDefeated" }],
        ["Kakariko Well - Bottom", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Kakariko Well - Bottom", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Kakariko Well - Bottom", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Kakariko Well - Bottom", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Kakariko Well - Bottom", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Blind's Hideout - Top", false, new string[] {  }],
        ["Blind's Hideout - Top", false, new string[] { "AgahnimDefeated" }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Blind's Hideout - Left", false, new string[] {  }],
        ["Blind's Hideout - Left", false, new string[] { "AgahnimDefeated" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Blind's Hideout - Right", false, new string[] {  }],
        ["Blind's Hideout - Right", false, new string[] { "AgahnimDefeated" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Blind's Hideout - Far Left", false, new string[] {  }],
        ["Blind's Hideout - Far Left", false, new string[] { "AgahnimDefeated" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Blind's Hideout - Far Right", false, new string[] {  }],
        ["Blind's Hideout - Far Right", false, new string[] { "AgahnimDefeated" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Bonk Rocks Item", false, new string[] {  }],
        ["Bonk Rocks Item", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Bonk Rocks Item", false, new string[] { "PegasusBoots", "AgahnimDefeated" }],
        ["Bonk Rocks Item", true, new string[] { "PegasusBoots", "MoonPearl", "AgahnimDefeated" }],
        ["Bonk Rocks Item", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Bonk Rocks Item", true, new string[] { "PegasusBoots", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Bonk Rocks Item", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Bonk Rocks Item", true, new string[] { "PegasusBoots", "MoonPearl", "TitansMitt" }],

        ["Mini Moldorm Cave - Far Left", false, new string[] {  }],
        ["Mini Moldorm Cave - Far Left", false, new string[] { "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Mini Moldorm Cave - Left", false, new string[] {  }],
        ["Mini Moldorm Cave - Left", false, new string[] { "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Mini Moldorm Cave - Right", false, new string[] {  }],
        ["Mini Moldorm Cave - Right", false, new string[] { "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Mini Moldorm Cave - Far Right", false, new string[] {  }],
        ["Mini Moldorm Cave - Far Right", false, new string[] { "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Ice Rod Cave Item", false, new string[] {  }],
        ["Ice Rod Cave Item", false, new string[] { "AgahnimDefeated" }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Bottle Merchant Item", false, new string[] {  }],
        ["Bottle Merchant Item", true, new string[] { "AgahnimDefeated" }],
        ["Bottle Merchant Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Bottle Merchant Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Bottle Merchant Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Bottle Merchant Item", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Sahasrahla's Hut - Sahasrahla", false, new string[] {  }],
        ["Sahasrahla's Hut - Sahasrahla", false, new string[] { "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "AgahnimDefeated" }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "TitansMitt" }],

        ["Magic Bat Item", false, new string[] {  }],
        ["Magic Bat Item", false, new string[] { "Powder", "Hammer", "MoonPearl" }],
        ["Magic Bat Item", true, new string[] { "Powder", "Hammer", "MoonPearl", "AgahnimDefeated" }],
        ["Magic Bat Item", true, new string[] { "Powder", "Hammer", "MoonPearl", "ProgressiveGlove" }],
        ["Magic Bat Item", true, new string[] { "Powder", "Hammer", "MoonPearl", "PowerGlove" }],
        ["Magic Bat Item", true, new string[] { "Powder", "Hammer", "MoonPearl", "TitansMitt" }],

        ["Sick Kid Item", false, new string[] {  }],
        ["Sick Kid Item", false, new string[] { "BottleWithBee" }],
        ["Sick Kid Item", false, new string[] { "BottleWithFairy" }],
        ["Sick Kid Item", false, new string[] { "BottleWithRedPotion" }],
        ["Sick Kid Item", false, new string[] { "BottleWithGreenPotion" }],
        ["Sick Kid Item", false, new string[] { "BottleWithBluePotion" }],
        ["Sick Kid Item", false, new string[] { "Bottle" }],
        ["Sick Kid Item", false, new string[] { "BottleWithGoldBee" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "Bottle", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "Bottle", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "Bottle", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "Bottle", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "Bottle", "MoonPearl", "TitansMitt" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee", "AgahnimDefeated" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee", "MoonPearl", "TitansMitt" }],

        ["Hobo", false, new string[] {  }],
        ["Hobo", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Hobo", false, new string[] { "Flippers", "AgahnimDefeated" }],
        ["Hobo", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],
        ["Hobo", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Hobo", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Hobo", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Hobo", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" }],

        ["Bombos Tablet", false, new string[] {  }],
        ["Bombos Tablet", false, new string[] { "AgahnimDefeated", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", false, new string[] { "AgahnimDefeated", "BookOfMudora", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L4Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L4Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L4Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L4Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L4Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L4Sword" }],

        ["King Zora", false, new string[] {  }],
        ["King Zora", false, new string[] { "Flippers", "AgahnimDefeated" }],
        ["King Zora", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],
        ["King Zora", true, new string[] { "ProgressiveGlove", "MoonPearl", "Hammer" }],
        ["King Zora", true, new string[] { "PowerGlove", "MoonPearl", "Hammer" }],
        ["King Zora", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["King Zora", true, new string[] { "TitansMitt", "MoonPearl" }],

        ["Lost Woods Hideout Item", false, new string[] {  }],
        ["Lost Woods Hideout Item", false, new string[] { "AgahnimDefeated" }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Lumberjack Tree", false, new string[] {  }],
        ["Lumberjack Tree", false, new string[] { "AgahnimDefeated", "MoonPearl" }],
        ["Lumberjack Tree", false, new string[] { "PegasusBoots", "MoonPearl" }],
        ["Lumberjack Tree", false, new string[] { "PegasusBoots", "AgahnimDefeated" }],
        ["Lumberjack Tree", true, new string[] { "PegasusBoots", "AgahnimDefeated", "MoonPearl" }],

        ["Cave 45 Item", false, new string[] {  }],
        ["Cave 45 Item", false, new string[] { "ProgressiveGlove", "ProgressiveGlove" }],
        ["Cave 45 Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Cave 45 Item", true, new string[] { "MoonPearl",  "TitansMitt" }],
        ["Cave 45 Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Cave 45 Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Cave 45 Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],

        ["Graveyard Cave Item", false, new string[] {  }],
        ["Graveyard Cave Item", false, new string[] { "ProgressiveGlove", "ProgressiveGlove" }],
        ["Graveyard Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Graveyard Cave Item", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Graveyard Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Graveyard Cave Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Graveyard Cave Item", true, new string[] { "MoonPearl", "AgahnimDefeated" }],

        ["Checkerboard Cave Item", false, new string[] {  }],
        ["Checkerboard Cave Item", false, new string[] { "AgahnimDefeated", "MoonPearl" }],
        ["Checkerboard Cave Item", false, new string[] { "ProgressiveGlove", "AgahnimDefeated" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "AgahnimDefeated", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "Hammer", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "MoonPearl" }],

        ["Mini Moldorm Cave - NPC", false, new string[] {  }],
        ["Mini Moldorm Cave - NPC", false, new string[] { "AgahnimDefeated" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Library Item", false, new string[] {  }],
        ["Library Item", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Library Item", false, new string[] { "PegasusBoots", "AgahnimDefeated" }],
        ["Library Item", true, new string[] { "PegasusBoots", "MoonPearl", "AgahnimDefeated" }],
        ["Library Item", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Library Item", true, new string[] { "PegasusBoots", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Library Item", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Library Item", true, new string[] { "PegasusBoots", "MoonPearl", "TitansMitt" }],

        ["Mushroom", false, new string[] {  }],
        ["Mushroom", false, new string[] { "AgahnimDefeated" }],
        ["Mushroom", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Mushroom", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Mushroom", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Mushroom", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Mushroom", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Potion Shop Item", false, new string[] {  }],
        ["Potion Shop Item", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Potion Shop Item", false, new string[] { "Mushroom", "AgahnimDefeated" }],
        ["Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "AgahnimDefeated" }],
        ["Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "TitansMitt" }],

        ["Maze Race", false, new string[] {  }],
        ["Maze Race", false, new string[] { "AgahnimDefeated" }],
        ["Maze Race", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Maze Race", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Maze Race", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Maze Race", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Maze Race", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Desert Ledge - Item", false, new string[] {  }],
        ["Desert Ledge - Item", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Desert Ledge - Item", false, new string[] { "BookOfMudora", "AgahnimDefeated" }],
        ["Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "AgahnimDefeated" }],
        ["Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "TitansMitt" }],

        ["Lake Hylia Island Item", false, new string[] {  }],
        ["Lake Hylia Island Item", false, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Lake Hylia Island Item", false, new string[] { "Flippers", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Lake Hylia Island Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Lake Hylia Island Item", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" }],
        ["Lake Hylia Island Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Lake Hylia Island Item", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Lake Hylia Island Item", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],

        ["Sunken Treasure", false, new string[] {  }],
        ["Sunken Treasure", false, new string[] { "AgahnimDefeated" }],
        ["Sunken Treasure", true, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Sunken Treasure", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Sunken Treasure", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Sunken Treasure", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Sunken Treasure", true, new string[] { "MoonPearl", "TitansMitt" }],

        ["Zora's Domain Ledge Item", false, new string[] {  }],
        ["Zora's Domain Ledge Item", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Zora's Domain Ledge Item", false, new string[] { "Flippers", "AgahnimDefeated" }],
        ["Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],
        ["Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" }],

        ["Flute Spot", false, new string[] {  }],
        ["Flute Spot", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Flute Spot", false, new string[] { "Shovel", "AgahnimDefeated" }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl", "AgahnimDefeated" }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl", "TitansMitt" }],

        ["Waterfall Fairy - Left", false, new string[] {  }],
        ["Waterfall Fairy - Left", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Waterfall Fairy - Left", false, new string[] { "Flippers", "AgahnimDefeated" }],
        ["Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],
        ["Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" }],

        ["Waterfall Fairy - Right", false, new string[] {  }],
        ["Waterfall Fairy - Right", false, new string[] { "MoonPearl", "AgahnimDefeated" }],
        ["Waterfall Fairy - Right", false, new string[] { "Flippers", "AgahnimDefeated" }],
        ["Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" }],
        ["Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" }],
        ["Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" }],

        ["Ganon", false, new string[] {  }],
        // @todo need to update Ganon Reqs
        // new object[] { "Ganon", true, new string[] { "MoonPearl", "AgahnimDefeated2" } },
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
