using AlttpRandomizer.Graph;

namespace RandomizerTests.Logic.Inverted.NoGlitches;

[TestClass]
public class LightWorldTest
{
    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Master Sword Pedestal", false, new string[] {  } },
        new object[] { "Master Sword Pedestal", false, new string[] { "PendantOfWisdom", "PendantOfPower", "AgahnimDefeated" } },
        new object[] { "Master Sword Pedestal", false, new string[] { "PendantOfCourage", "PendantOfPower", "AgahnimDefeated" } },
        new object[] { "Master Sword Pedestal", false, new string[] { "PendantOfCourage", "PendantOfWisdom", "AgahnimDefeated" } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "AgahnimDefeated" } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower", "MoonPearl", "TitansMitt" } },

        new object[] { "Link's Uncle", false, new string[] {  } },
        new object[] { "Link's Uncle", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Secret Passage", false, new string[] {  } },
        new object[] { "Secret Passage", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "King's Tomb Chest", false, new string[] {  } },
        new object[] { "King's Tomb Chest", false, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" } },
        new object[] { "King's Tomb Chest", false, new string[] { "PegasusBoots", "ProgressiveGlove", "MoonPearl" } },
        new object[] { "King's Tomb Chest", false, new string[] { "PegasusBoots", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "King's Tomb Chest", true, new string[] { "PegasusBoots", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" } },
        new object[] { "King's Tomb Chest", true, new string[] { "PegasusBoots", "TitansMitt", "MoonPearl" } },

        new object[] { "Floodgate Chest", false, new string[] {  } },
        new object[] { "Floodgate Chest", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Tavern", false, new string[] {  } },
        new object[] { "Kakariko Tavern", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Tavern", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Tavern", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Tavern", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Tavern", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Tavern", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Chicken House", false, new string[] {  } },
        new object[] { "Chicken House", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Chicken House", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Chicken House", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Chicken House", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Chicken House", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Chicken House", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Aginah's Cave", false, new string[] {  } },
        new object[] { "Aginah's Cave", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Sahasrahla's Hut - Left", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Sahasrahla's Hut - Middle", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Middle", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Sahasrahla's Hut - Right", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Well - Top", false, new string[] {  } },
        new object[] { "Kakariko Well - Top", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Well - Left", false, new string[] {  } },
        new object[] { "Kakariko Well - Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Well - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Well - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Well - Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Well - Middle", false, new string[] {  } },
        new object[] { "Kakariko Well - Middle", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Middle", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Well - Middle", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Well - Middle", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Well - Middle", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Well - Right", false, new string[] {  } },
        new object[] { "Kakariko Well - Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Well - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Well - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Well - Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Kakariko Well - Bottom", false, new string[] {  } },
        new object[] { "Kakariko Well - Bottom", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Bottom", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Kakariko Well - Bottom", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Kakariko Well - Bottom", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Kakariko Well - Bottom", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Kakariko Well - Bottom", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Blind's Hideout - Top", false, new string[] {  } },
        new object[] { "Blind's Hideout - Top", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Blind's Hideout - Left", false, new string[] {  } },
        new object[] { "Blind's Hideout - Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Blind's Hideout - Right", false, new string[] {  } },
        new object[] { "Blind's Hideout - Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Blind's Hideout - Far Left", false, new string[] {  } },
        new object[] { "Blind's Hideout - Far Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Blind's Hideout - Far Right", false, new string[] {  } },
        new object[] { "Blind's Hideout - Far Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Pegasus Rocks", false, new string[] {  } },
        new object[] { "Pegasus Rocks", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Pegasus Rocks", false, new string[] { "PegasusBoots", "AgahnimDefeated" } },
        new object[] { "Pegasus Rocks", true, new string[] { "PegasusBoots", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Pegasus Rocks", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Pegasus Rocks", true, new string[] { "PegasusBoots", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Pegasus Rocks", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Pegasus Rocks", true, new string[] { "PegasusBoots", "MoonPearl", "TitansMitt" } },

        new object[] { "Mini Moldorm Cave - Far Left", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Far Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Mini Moldorm Cave - Left", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Left", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Mini Moldorm Cave - Right", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Mini Moldorm Cave - Far Right", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Far Right", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Ice Rod Cave", false, new string[] {  } },
        new object[] { "Ice Rod Cave", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Ice Rod Cave", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Ice Rod Cave", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Ice Rod Cave", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Ice Rod Cave", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Ice Rod Cave", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Bottle Merchant", false, new string[] {  } },
        new object[] { "Bottle Merchant", true, new string[] { "AgahnimDefeated" } },
        new object[] { "Bottle Merchant", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Bottle Merchant", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Bottle Merchant", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Bottle Merchant", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Sahasrahla's Hut - Sahasrahla", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "AgahnimDefeated" } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage", "MoonPearl", "TitansMitt" } },

        new object[] { "Magic Bat", false, new string[] {  } },
        new object[] { "Magic Bat", false, new string[] { "Powder", "Hammer", "MoonPearl" } },
        new object[] { "Magic Bat", true, new string[] { "Powder", "Hammer", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Magic Bat", true, new string[] { "Powder", "Hammer", "MoonPearl", "ProgressiveGlove" } },
        new object[] { "Magic Bat", true, new string[] { "Powder", "Hammer", "MoonPearl", "PowerGlove" } },
        new object[] { "Magic Bat", true, new string[] { "Powder", "Hammer", "MoonPearl", "TitansMitt" } },

        new object[] { "Sick Kid", false, new string[] {  } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithBee" } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithFairy" } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sick Kid", false, new string[] { "Bottle" } },
        new object[] { "Sick Kid", false, new string[] { "BottleWithGoldBee" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBee", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBee", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBee", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBee", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBee", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithFairy", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithFairy", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithFairy", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithFairy", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithFairy", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithRedPotion", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithRedPotion", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithRedPotion", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithRedPotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithRedPotion", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGreenPotion", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGreenPotion", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBluePotion", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBluePotion", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBluePotion", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBluePotion", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithBluePotion", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "Bottle", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "Bottle", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "Bottle", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "Bottle", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "Bottle", "MoonPearl", "TitansMitt" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGoldBee", "AgahnimDefeated" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGoldBee", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGoldBee", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGoldBee", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sick Kid", true, new string[] { "BottleWithGoldBee", "MoonPearl", "TitansMitt" } },

        new object[] { "Hobo", false, new string[] {  } },
        new object[] { "Hobo", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Hobo", false, new string[] { "Flippers", "AgahnimDefeated" } },
        new object[] { "Hobo", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Hobo", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Hobo", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Hobo", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Hobo", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" } },

        new object[] { "Bombos Tablet", false, new string[] {  } },
        new object[] { "Bombos Tablet", false, new string[] { "AgahnimDefeated", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", false, new string[] { "AgahnimDefeated", "BookOfMudora", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "AgahnimDefeated", "BookOfMudora", "L4Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "ProgressiveGlove", "L4Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "TitansMitt", "L4Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "ProgressiveGlove", "Hammer", "L4Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "PowerGlove", "Hammer", "L4Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "MoonPearl", "BookOfMudora", "AgahnimDefeated", "L4Sword" } },

        new object[] { "King Zora", false, new string[] {  } },
        new object[] { "King Zora", false, new string[] { "Flippers", "AgahnimDefeated" } },
        new object[] { "King Zora", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "King Zora", true, new string[] { "ProgressiveGlove", "MoonPearl", "Hammer" } },
        new object[] { "King Zora", true, new string[] { "PowerGlove", "MoonPearl", "Hammer" } },
        new object[] { "King Zora", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" } },
        new object[] { "King Zora", true, new string[] { "TitansMitt", "MoonPearl" } },

        new object[] { "Lost Woods Hideout", false, new string[] {  } },
        new object[] { "Lost Woods Hideout", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Lost Woods Hideout", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Lost Woods Hideout", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Lost Woods Hideout", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Lost Woods Hideout", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Lost Woods Hideout", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Lumberjack Tree", false, new string[] {  } },
        new object[] { "Lumberjack Tree", false, new string[] { "AgahnimDefeated", "MoonPearl" } },
        new object[] { "Lumberjack Tree", false, new string[] { "PegasusBoots", "MoonPearl" } },
        new object[] { "Lumberjack Tree", false, new string[] { "PegasusBoots", "AgahnimDefeated" } },
        new object[] { "Lumberjack Tree", true, new string[] { "PegasusBoots", "AgahnimDefeated", "MoonPearl" } },

        new object[] { "Cave 45", false, new string[] {  } },
        new object[] { "Cave 45", false, new string[] { "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Cave 45", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Cave 45", true, new string[] { "MoonPearl",  "TitansMitt" } },
        new object[] { "Cave 45", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Cave 45", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Cave 45", true, new string[] { "MoonPearl", "AgahnimDefeated" } },

        new object[] { "Graveyard Cave Item", false, new string[] {  } },
        new object[] { "Graveyard Cave Item", false, new string[] { "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Graveyard Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Graveyard Cave Item", true, new string[] { "MoonPearl", "TitansMitt" } },
        new object[] { "Graveyard Cave Item", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Graveyard Cave Item", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Graveyard Cave Item", true, new string[] { "MoonPearl", "AgahnimDefeated" } },

        new object[] { "Checkerboard Cave", false, new string[] {  } },
        new object[] { "Checkerboard Cave", false, new string[] { "AgahnimDefeated", "MoonPearl" } },
        new object[] { "Checkerboard Cave", false, new string[] { "ProgressiveGlove", "AgahnimDefeated" } },
        new object[] { "Checkerboard Cave", true, new string[] { "ProgressiveGlove", "AgahnimDefeated", "MoonPearl" } },
        new object[] { "Checkerboard Cave", true, new string[] { "ProgressiveGlove", "Hammer", "MoonPearl" } },
        new object[] { "Checkerboard Cave", true, new string[] { "PowerGlove", "Hammer", "MoonPearl" } },
        new object[] { "Checkerboard Cave", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" } },
        new object[] { "Checkerboard Cave", true, new string[] { "TitansMitt", "MoonPearl" } },

        new object[] { "Mini Moldorm Cave - NPC", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - NPC", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Library", false, new string[] {  } },
        new object[] { "Library", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Library", false, new string[] { "PegasusBoots", "AgahnimDefeated" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl", "TitansMitt" } },

        new object[] { "Mushroom", false, new string[] {  } },
        new object[] { "Mushroom", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Mushroom", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Mushroom", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Mushroom", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Mushroom", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Mushroom", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Potion Shop Item", false, new string[] {  } },
        new object[] { "Potion Shop Item", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Potion Shop Item", false, new string[] { "Mushroom", "AgahnimDefeated" } },
        new object[] { "Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Potion Shop Item", true, new string[] { "Mushroom", "MoonPearl", "TitansMitt" } },

        new object[] { "Maze Race", false, new string[] {  } },
        new object[] { "Maze Race", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Maze Race", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Maze Race", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Maze Race", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Maze Race", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Maze Race", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Desert Ledge - Item", false, new string[] {  } },
        new object[] { "Desert Ledge - Item", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Desert Ledge - Item", false, new string[] { "BookOfMudora", "AgahnimDefeated" } },
        new object[] { "Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Desert Ledge - Item", true, new string[] { "BookOfMudora", "MoonPearl", "TitansMitt" } },

        new object[] { "Lake Hylia Island", false, new string[] {  } },
        new object[] { "Lake Hylia Island", false, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Lake Hylia Island", false, new string[] { "Flippers", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Lake Hylia Island", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Lake Hylia Island", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" } },
        new object[] { "Lake Hylia Island", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Lake Hylia Island", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Lake Hylia Island", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },

        new object[] { "Sunken Treasure", false, new string[] {  } },
        new object[] { "Sunken Treasure", false, new string[] { "AgahnimDefeated" } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl", "TitansMitt" } },

        new object[] { "Zora's Domain Ledge Item", false, new string[] {  } },
        new object[] { "Zora's Domain Ledge Item", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Zora's Domain Ledge Item", false, new string[] { "Flippers", "AgahnimDefeated" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" } },

        new object[] { "Flute Spot", false, new string[] {  } },
        new object[] { "Flute Spot", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Flute Spot", false, new string[] { "Shovel", "AgahnimDefeated" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl", "TitansMitt" } },

        new object[] { "Waterfall Fairy - Left", false, new string[] {  } },
        new object[] { "Waterfall Fairy - Left", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Left", false, new string[] { "Flippers", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" } },

        new object[] { "Waterfall Fairy - Right", false, new string[] {  } },
        new object[] { "Waterfall Fairy - Right", false, new string[] { "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Right", false, new string[] { "Flippers", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "AgahnimDefeated" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Flippers", "MoonPearl", "TitansMitt" } },

        new object[] { "Ganon", false, new string[] {  } },
        // @todo need to update Ganon Reqs
        // new object[] { "Ganon", true, new string[] { "MoonPearl", "AgahnimDefeated2" } },
    };
    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void TestLogic(string location, bool expected, string[] inventory)
    {
        var randomizer = new Randomizer(new[]
        {
            new Dictionary<string, object>()
            {
                { "mode.state", "inverted" },
                { "logic", "NoGlitches" },
            }
        });
        randomizer.AssumeItems(inventory.Select(i => Item.Get(i, 0)));
        Assert.AreEqual(expected, randomizer.CanReachLocation($"{location}:0"));
    }
}
