using AlttpRandomizer.Graph;

namespace RandomizerTests.Logic.Inverted.NoGlitches;

[TestClass]
public class MiseryMireTest
{
    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Misery Mire - Big Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Big Chest", false, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Main Lobby Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Big Key Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Compass Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Bridge Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Map Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Spike Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },

        new object[] { "Misery Mire - Boss", false, new string[] {  } },
        new object[] { "Misery Mire - Boss", false, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", false, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", false, new string[] { "KeyD6", "KeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaInactive", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "ProgressiveGlove", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "MagicMirror", "ProgressiveGlove", "Hammer", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MagicMirror", "AgahnimDefeated", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MagicMirror", "AgahnimDefeated", "Ether", "ProgressiveSword", "Hookshot" } },
    };
    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void TestLogic(string location, bool expected, string[] inventory)
    {
        var randomizer = new Randomizer(new[]
        {
            new Dictionary<string, object>()
            {
                { "mode.state", "inverted" },
                { "logic", "NoGlitches" },
            }
        });
        randomizer.AssumeItems(inventory.Select(i => Item.Get(i, 0)));
        Assert.AreEqual(expected, randomizer.CanReachLocation($"{location}:0"));
    }
}
