namespace Randomizer.RomModifications;
/// <summary>
/// Overwrite all the text in the main portion of the ROM
/// from: 0xE0000 to: 0xE7355
/// 394 required things in table
/// but extended a bit by the randomizer
/// </summary>
internal sealed class Text
{
    private readonly Dictionary<string, byte[]> _texts;
    private readonly Dialog _converter;

    // Numbers in comments refer to US text numbers. Except for
    // the first few entries, JP1.0 text numbers are smaller by 2
    private static readonly string[] _dialogOrder = [
        "set_cursor",
        "set_cursor2",
        "game_over_menu",
        "var_test",
        "follower_no_enter",
        "choice_1_3",
        "choice_2_3",
        "choice_3_3",
        "choice_1_2",
        "choice_2_2",
        "uncle_leaving_text",
        "uncle_dying_sewer",
        // 0x10
        "tutorial_guard_1",
        "tutorial_guard_2",
        "tutorial_guard_3",
        "tutorial_guard_4",
        "tutorial_guard_5",
        "tutorial_guard_6",
        "tutorial_guard_7",
        "priest_sanctuary_before_leave",
        "sanctuary_enter",
        "zelda_sanctuary_story",
        "priest_sanctuary_before_pendants",
        "priest_sanctuary_after_pendants_before_master_sword",
        "priest_sanctuary_dying",
        "zelda_save_sewers",
        "priest_info",
        "zelda_sanctuary_before_leave",
        "telepathic_intro",
        // 0x20
        "telepathic_reminder",
        "zelda_go_to_throne",
        "zelda_push_throne",
        "zelda_switch_room_pull",
        "zelda_save_lets_go",
        "zelda_save_repeat",
        "zelda_before_pendants",
        "zelda_after_pendants_before_master_sword",
        "telepathic_zelda_right_after_master_sword",
        "zelda_sewers",
        "zelda_switch_room",
        "kakariko_saharalasa_wife",
        "kakariko_saharalasa_wife_sword_story",
        "kakariko_saharalasa_wife_closing",
        "kakariko_saharalasa_after_master_sword",
        "kakariko_alert_guards",
        // 0x30
        "sahasrahla_quest_have_pendants",
        "sahasrahla_quest_have_master_sword",
        "sahasrahla_quest_information",
        "sahasrahla_bring_courage",
        "sahasrahla_have_ice_rod",
        "telepathic_sahasrahla_beat_agahnim",
        "telepathic_sahasrahla_beat_agahnim_no_pearl",
        "sahasrahla_have_boots_no_icerod",
        "sahasrahla_have_courage",
        "sahasrahla_found",
        "sign_rain_north_of_links_house",
        "sign_north_of_links_house",
        "sign_path_to_death_mountain",
        "sign_lost_woods",
        "sign_zoras",
        "sign_outside_magic_shop",
        // 0x40
        "sign_death_mountain_cave_back",
        "sign_east_of_links_house",
        "sign_south_of_lumberjacks",
        "sign_east_of_desert",
        "sign_east_of_sanctuary",
        "sign_east_of_castle",
        "sign_north_of_lake",
        "sign_desert_thief",
        "sign_lumberjacks_house",
        "sign_north_kakariko",
        "witch_bring_mushroom",
        "witch_brewing_the_item",
        "witch_assistant_no_bottle",
        "witch_assistant_no_empty_bottle",
        "witch_assistant_informational",
        "witch_assistant_no_bottle_buying",
        // 0x50
        "potion_shop_no_empty_bottles",
        "item_get_lamp",
        "item_get_boomerang",
        "item_get_bow",
        "item_get_shovel",
        "item_get_magic_cape",
        "item_get_powder",
        "item_get_flippers",
        "item_get_power_gloves",
        "item_get_pendant_courage",
        "item_get_pendant_power",
        "item_get_pendant_wisdom",
        "item_get_mushroom",
        "item_get_book",
        "item_get_moonpearl",
        "item_get_compass",
        // 0x60
        "item_get_map",
        "item_get_ice_rod",
        "item_get_fire_rod",
        "item_get_ether",
        "item_get_bombos",
        "item_get_quake",
        "item_get_hammer",
        "item_get_ocarina",
        "item_get_cane_of_somaria",
        "item_get_hookshot",
        "item_get_bombs",
        "item_get_bottle",
        "item_get_big_key",
        "item_get_titans_mitts",
        "item_get_magic_mirror",
        "item_get_fake_mastersword",
        // 0x70
        "post_item_get_mastersword",
        "item_get_red_potion",
        "item_get_green_potion",
        "item_get_blue_potion",
        "item_get_bug_net",
        "item_get_blue_mail",
        "item_get_red_mail",
        "item_get_temperedsword",
        "item_get_mirror_shield",
        "item_get_cane_of_byrna",
        "missing_big_key",
        "missing_magic",
        "item_get_pegasus_boots",
        "talking_tree_info_start",
        "talking_tree_info_1",
        "talking_tree_info_2",
        // 0x80
        "talking_tree_info_3",
        "talking_tree_info_4",
        "talking_tree_other",
        "item_get_pendant_power_alt",
        "item_get_pendant_wisdom_alt",
        "game_shooting_choice",
        "game_shooting_yes",
        "game_shooting_no",
        "game_shooting_continue",
        "pond_of_wishing",
        "pond_item_select",
        "pond_item_test",
        "pond_will_upgrade",
        "pond_item_test_no",
        "pond_item_test_no_no",
        "pond_item_boomerang",
        // 0x90
        "pond_item_shield",
        "pond_item_silvers",
        "pond_item_bottle_filled",
        "pond_item_sword",
        "pond_of_wishing_happiness",
        "pond_of_wishing_choice",
        "pond_of_wishing_bombs",
        "pond_of_wishing_arrows",
        "pond_of_wishing_full_upgrades",
        "mountain_old_man_first",
        "mountain_old_man_deadend",
        "mountain_old_man_turn_right",
        "mountain_old_man_lost_and_alone",
        "mountain_old_man_drop_off",
        "mountain_old_man_in_his_cave_pre_agahnim",
        "mountain_old_man_in_his_cave",
        // 0xA0
        "mountain_old_man_in_his_cave_post_agahnim",
        "tavern_old_man_awake",
        "tavern_old_man_unactivated_flute",
        "tavern_old_man_know_tree_unactivated_flute",
        "tavern_old_man_have_flute",
        "chicken_hut_lady",
        "running_man",
        "game_race_sign",
        "sign_bumper_cave",
        "sign_catfish",
        "sign_north_village_of_outcasts",
        "sign_south_of_bumper_cave",
        "sign_east_of_pyramid",
        "sign_east_of_bomb_shop",
        "sign_east_of_mire",
        "sign_village_of_outcasts",
        // 0xB0
        "sign_before_wishing_pond",
        "sign_before_catfish_area",
        "castle_wall_guard",
        "gate_guard",
        "telepathic_tile_eastern_palace",
        "telepathic_tile_tower_of_hera_floor_4",
        "hylian_text_1",
        "mastersword_pedestal_translated",
        "telepathic_tile_spectacle_rock",
        "telepathic_tile_swamp_entrance",
        "telepathic_tile_thieves_town_upstairs",
        "telepathic_tile_misery_mire",
        "hylian_text_2",
        "desert_entry_translated",
        "telepathic_tile_under_ganon",
        "telepathic_tile_palace_of_darkness",
        // 0xC0
        "telepathic_tile_desert_bonk_torch_room",
        "telepathic_tile_castle_tower",
        "telepathic_tile_ice_large_room",
        "telepathic_tile_turtle_rock",
        "telepathic_tile_ice_entrace",
        "telepathic_tile_ice_stalfos_knights_room",
        "telepathic_tile_tower_of_hera_entrance",
        "houlihan_room",
        "caught_a_bee",
        "caught_a_fairy",
        "no_empty_bottles",
        "game_race_boy_time",
        "game_race_girl",
        "game_race_boy_success",
        "game_race_boy_failure",
        "game_race_boy_already_won",
        // 0xD0
        "game_race_boy_sneaky",
        "bottle_vendor_choice",
        "bottle_vendor_get",
        "bottle_vendor_no",
        "bottle_vendor_already_collected",
        "bottle_vendor_bee",
        "bottle_vendor_fish",
        "hobo_item_get_bottle",
        "blacksmiths_what_you_want",
        "blacksmiths_paywall",
        "blacksmiths_extra_okay",
        "blacksmiths_tempered_already",
        "blacksmiths_temper_no",
        "blacksmiths_bogart_sword",
        "blacksmiths_get_sword",
        "blacksmiths_shop_before_saving",
        // 0xE0
        "blacksmiths_shop_saving",
        "blacksmiths_collect_frog",
        "blacksmiths_still_working",
        "blacksmiths_saving_bows",
        "blacksmiths_hammer_anvil",
        "dark_flute_boy_storytime",
        "dark_flute_boy_get_shovel",
        "dark_flute_boy_no_get_shovel",
        "dark_flute_boy_flute_not_found",
        "dark_flute_boy_after_shovel_get",
        "shop_fortune_teller_lw_hint_0",
        "shop_fortune_teller_lw_hint_1",
        "shop_fortune_teller_lw_hint_2",
        "shop_fortune_teller_lw_hint_3",
        "shop_fortune_teller_lw_hint_4",
        "shop_fortune_teller_lw_hint_5",
        // 0xF0
        "shop_fortune_teller_lw_hint_6",
        "shop_fortune_teller_lw_hint_7",
        "shop_fortune_teller_lw_no_rupees",
        "shop_fortune_teller_lw",
        "shop_fortune_teller_lw_post_hint",
        "shop_fortune_teller_lw_no",
        "shop_fortune_teller_lw_hint_8",
        "shop_fortune_teller_lw_hint_9",
        "shop_fortune_teller_lw_hint_10",
        "shop_fortune_teller_lw_hint_11",
        "shop_fortune_teller_lw_hint_12",
        "shop_fortune_teller_lw_hint_13",
        "shop_fortune_teller_lw_hint_14",
        "shop_fortune_teller_lw_hint_15",
        "dark_sanctuary",
        "dark_sanctuary_hint_0",
        // 0x100
        "dark_sanctuary_no",
        "dark_sanctuary_hint_1",
        "dark_sanctuary_yes",
        "dark_sanctuary_hint_2",
        "sick_kid_no_bottle",
        "sick_kid_trade",
        "sick_kid_post_trade",
        "desert_thief_sitting",
        "desert_thief_following",
        "desert_thief_question",
        "desert_thief_question_yes",
        "desert_thief_after_item_get",
        "desert_thief_reassure",
        "hylian_text_3",
        "tablet_ether_book",
        "tablet_bombos_book",
        // 0x110
        "magic_bat_wake",
        "magic_bat_give_half_magic",
        "intro_main",
        "intro_throne_room",
        "intro_zelda_cell",
        "intro_agahnim",
        "pickup_purple_chest",
        "bomb_shop",
        "bomb_shop_big_bomb",
        "bomb_shop_big_bomb_buy",
        "item_get_big_bomb",
        "kiki_second_extortion",
        "kiki_second_extortion_no",
        "kiki_second_extortion_yes",
        "kiki_first_extortion",
        "kiki_first_extortion_yes",
        // 0x120
        "kiki_first_extortion_no",
        "kiki_leaving_screen",
        "blind_in_the_cell",
        "blind_by_the_light",
        "blind_not_that_way",
        "aginah_l1sword_no_book",
        "aginah_l1sword_with_pendants",
        "aginah",
        "aginah_need_better_sword",
        "aginah_have_better_sword",
        "catfish",
        "catfish_after_item",
        // 0x12C
        "lumberjack_right",
        "lumberjack_left",
        "lumberjack_left_post_agahnim",
        "fighting_brothers_right",
        // 0x130
        "fighting_brothers_right_opened",
        "fighting_brothers_left",
        "maiden_crystal_1",
        "maiden_crystal_2",
        "maiden_crystal_3",
        "maiden_crystal_4",
        "maiden_crystal_5",
        "maiden_crystal_6",
        "maiden_crystal_7",
        "maiden_ending",
        "maiden_confirm_undersood",
        "barrier_breaking",
        "maiden_crystal_7_again",
        "agahnim_zelda_teleport",
        "agahnim_magic_running_away",
        "agahnim_hide_and_seek_found",
        // 0x140
        "agahnim_defeated",
        "agahnim_final_meeting",
        // 0x142
        "zora_meeting",
        "zora_tells_cost",
        "zora_get_flippers",
        "zora_no_cash",
        "zora_no_buy_item",
        "kakariko_saharalasa_grandson",
        "kakariko_saharalasa_grandson_next",
        "dark_palace_tree_dude",
        "fairy_wishing_ponds",
        "fairy_wishing_ponds_no",
        "pond_of_wishing_no",
        "pond_of_wishing_return_item",
        "pond_of_wishing_throw",
        "pond_pre_item_silvers",
        // 0x150
        "pond_of_wishing_great_luck",
        "pond_of_wishing_good_luck",
        "pond_of_wishing_meh_luck",
        // Repurposed to no items in Randomizer
        "pond_of_wishing_bad_luck",
        "pond_of_wishing_fortune",
        "item_get_14_heart",
        "item_get_24_heart",
        "item_get_34_heart",
        "item_get_whole_heart",
        "item_get_sanc_heart",
        "fairy_fountain_refill",
        "death_mountain_bullied_no_pearl",
        "death_mountain_bullied_with_pearl",
        "death_mountain_bully_no_pearl",
        "death_mountain_bully_with_pearl",
        "shop_darkworld_enter",
        // 0x160
        "game_chest_village_of_outcasts",
        "game_chest_no_cash",
        "game_chest_not_played",
        "game_chest_played",
        "game_chest_village_of_outcasts_play",
        "shop_first_time",
        "shop_already_have",
        "shop_buy_shield",
        "shop_buy_red_potion",
        "shop_buy_arrows",
        "shop_buy_bombs",
        "shop_buy_bee",
        "shop_buy_heart",
        "shop_first_no_bottle_buy",
        "shop_buy_no_space",
        "ganon_fall_in",
        // 0x170
        "ganon_phase_3",
        "lost_woods_thief",
        "blinds_hut_dude",
        "end_triforce",
        // 0x174
        "toppi_fallen",
        "kakariko_tavern_fisherman",
        "thief_money",
        "thief_desert_rupee_cave",
        "thief_ice_rupee_cave",
        "telepathic_tile_south_east_darkworld_cave",
        // 0x17A
        "cukeman",
        "cukeman_2",
        "potion_shop_no_cash",
        "kakariko_powdered_chicken",
        "game_chest_south_of_kakariko",
        "game_chest_play_yes",
        // 0x180
        "game_chest_play_no",
        "game_chest_lost_woods",
        "kakariko_flophouse_man_no_flippers",
        "kakariko_flophouse_man",
        "menu_start_2",
        "menu_start_3",
        "menu_pause",
        "game_digging_choice",
        "game_digging_start",
        "game_digging_no_cash",
        "game_digging_end_time",
        "game_digging_come_back_later",
        "game_digging_no_follower",
        "menu_start_4",
        "ganon_fall_in_alt",
        "ganon_phase_3_alt",
        // 0x190
        "sign_east_death_mountain_bridge",
        "fish_money",
        "sign_ganons_tower",
        "sign_ganon",
        "ganon_phase_3_no_bow",
        "ganon_phase_3_no_silvers_alt",
        "ganon_phase_3_no_silvers",
        "ganon_phase_3_silvers",
        "murahdahla",
        "end_pad_data",
        "terminator",
    ];

    public Text(string translation = "en")
    {
        _converter = new();
        // TODO: use the translation parameter and load this from elsewhere (YAML?)
        if (translation != "en")
            throw new NotSupportedException($"Sorry, we don't have a translation for '{translation}'");
        _texts = En();
    }

    /// <summary>Updates a specific string in the table, including encoding the string.</summary>
    /// <param name="id">The ID of the string to update</param>
    /// <param name="value">the string to add to the table</param>
    public void SetString(string id, string value, bool pause = true, int maxBytes = 2046, int wrap = 19)
    {
        // TODO: should we be checking against _dialogOrder instead, since the data is keyed?
        if (!_texts.ContainsKey(id))
            throw new Exception($"Attempted to update a non-existant text id ({id}).");

        _texts[id] = _converter.ConvertDialogCompressed(value, pause, maxBytes, wrap);
    }

    /// <summary>Updates a specific string in the table, given the raw bytes</summary>
    /// <param name="id">The ID of the string to update</param>
    /// <param name="rawvalue">The raw bytes to add to the table</param>
    public void SetStringRaw(string id, byte[] rawvalue)
    {
        // TODO: SetString throws, this just adds the key and doesn't care if the key is part of _dialogOrder
        _texts[id] = rawvalue;
    }

    public byte[] GetByteArray(bool pad = false)
    {
        var data = new List<byte>();
        foreach (string dialogKey in _dialogOrder)
            data.AddRange(_texts[dialogKey]);

        //Log::debug(sprintf("Localization free space: %s", 0x7355 - data.Count));

        if (data.Count > 0x7355)
            throw new Exception("Too BIG");
        if (pad)
            data.AddRange(Enumerable.Repeat((byte)0xFF, 0x7355 - data.Count));

        return [.. data];
    }

    // TODO: this should really come from elsewhere, like a YAML file (and be translatable rather than hardcoded/fixed to english)
    private Dictionary<string, byte[]> En() => new()
    {
        { "set_cursor", [0xFB, 0xFC, 0x00, 0xF9, 0xFF, 0xFF, 0xFF, 0xF8, 0xFF, 0xFF, 0x99, 0xFE, 0x68] },
        { "set_cursor2", [0xFB, 0xFC, 0x00, 0xF8, 0xFF, 0xFF, 0xFF, 0xF9, 0xFF, 0xFF, 0x99, 0xFE, 0x68] },
        { "game_over_menu", _converter.ConvertDialogCompressed("{SPEED0}\nSave-Continue\nSave-Quit\nContinue", false) },
        { "var_test", _converter.ConvertDialogCompressed("0= ᚋ, 1= ᚌ\n2= ᚍ, 3= ᚎ", false) },
        { "follower_no_enter", _converter.ConvertDialogCompressed("Can't you take me some place nice.") },
        { "choice_1_3", [0xFB, 0xFC, 0x00, 0xF7, 0x99, 0xF8, 0xFF, 0xF9, 0xFF, 0xFE, 0x71] },
        { "choice_2_3", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0x99, 0xF9, 0xFF, 0xFE, 0x71] },
        { "choice_3_3", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0xFF, 0xF9, 0x99, 0xFE, 0x71] },
        { "choice_1_2", [0xFB, 0xFC, 0x00, 0xF7, 0x99, 0xF8, 0xFF, 0xFE, 0x72] },
        { "choice_2_2", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0x99, 0xFE, 0x72] },
        { "uncle_leaving_text", _converter.ConvertDialogCompressed("I'm just going out for a pack of smokes.") },
        { "uncle_dying_sewer", _converter.ConvertDialogCompressed("I've fallen and I can't get up, take this.") },
        // 0x10
        { "tutorial_guard_1", _converter.ConvertDialogCompressed("Only adults should travel at night.") },
        { "tutorial_guard_2", _converter.ConvertDialogCompressed("You can press X to see the Map.") },
        { "tutorial_guard_3", _converter.ConvertDialogCompressed("Press the A button to lift things by you.") },
        { "tutorial_guard_4", _converter.ConvertDialogCompressed("When you has a sword, press B to slash it.") },
        { "tutorial_guard_5", _converter.ConvertDialogCompressed("このメッセージはニホンゴでそのまま") }, // on purpose
        { "tutorial_guard_6", _converter.ConvertDialogCompressed("Are we really still reading these?") },
        { "tutorial_guard_7", _converter.ConvertDialogCompressed("Jeeze! There really are a lot of things.") },
        { "priest_sanctuary_before_leave", _converter.ConvertDialogCompressed("Go be a hero!") },
        { "sanctuary_enter", _converter.ConvertDialogCompressed("YAY!\nYou saved Zelda!") },
        { "zelda_sanctuary_story", _converter.ConvertDialogCompressed("Do you want to hear me say this again?\n{HARP}\n  ≥ No\n    Yes\n{CHOICE}") },
        { "priest_sanctuary_before_pendants", _converter.ConvertDialogCompressed("Go'on and get them pendants so you can beat up Agahnim.") },
        { "priest_sanctuary_after_pendants_before_master_sword", _converter.ConvertDialogCompressed("Kudos! But seriously, you should be getting the Master Sword, not having a kegger in here.") },
        { "priest_sanctuary_dying", _converter.ConvertDialogCompressed("They took her to the castle! Take your sword and save her!") },
        { "zelda_save_sewers", _converter.ConvertDialogCompressed("You saved me!") },
        { "priest_info", _converter.ConvertDialogCompressed("So, I'm the dude that will protect Zelda. Don't worry, I got this covered.") },
        { "zelda_sanctuary_before_leave", _converter.ConvertDialogCompressed("Be careful!") },
        { "telepathic_intro", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\nHey, come find me and help me!") },
        // 0x20
        { "telepathic_reminder", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\nI'm in the castle basement.") },
        { "zelda_go_to_throne", _converter.ConvertDialogCompressed("Go north to the throne.") },
        { "zelda_push_throne", _converter.ConvertDialogCompressed("Let's push it from the left!") },
        { "zelda_switch_room_pull", _converter.ConvertDialogCompressed("Pull this lever using A.") },
        { "zelda_save_lets_go", _converter.ConvertDialogCompressed("Let's get out of here!") },
        { "zelda_save_repeat", _converter.ConvertDialogCompressed("I like talking, do you?\n  ≥ No\n    Yes\n{CHOICE}") },
        { "zelda_before_pendants", _converter.ConvertDialogCompressed("You need to find all the pendants…\n\n\nNumpty.") },
        { "zelda_after_pendants_before_master_sword", _converter.ConvertDialogCompressed("Very pretty pendants, but really you should be getting that sword in the forest!") },
        { "telepathic_zelda_right_after_master_sword", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\nHi @,\nHave you been thinking about me?\narrrrrgghh…\n… … …") },
        { "zelda_sewers", _converter.ConvertDialogCompressed("Just a little further to the Sanctuary.") },
        { "zelda_switch_room", _converter.ConvertDialogCompressed("The Sanctuary!\n\nPull my finger") },
        { "kakariko_saharalasa_wife", _converter.ConvertDialogCompressed("Heya, @!\nLong time no see.\nYou want a Master Sword?\n\nWell good luck with that.") },
        { "kakariko_saharalasa_wife_sword_story", _converter.ConvertDialogCompressed("It occurs to me that I like toast and jam, but cheese and crackers is better.\nYou like?\n  ≥ Cheese\n    Jam\n{CHOICE}") },
        { "kakariko_saharalasa_wife_closing", _converter.ConvertDialogCompressed("Anywho, I have things to do. You see those 2 ovens?\n\nYeah, 2!\nWho has 2 ovens nowadays?!") },
        { "kakariko_saharalasa_after_master_sword", _converter.ConvertDialogCompressed("Cool sword!\n\n\n…\n\n\n…\n\n\nPlease save us") },
        { "kakariko_alert_guards", _converter.ConvertDialogCompressed("Guards! Help!\nThe creeper\n@ is here!") },
        // 0x30
        { "sahasrahla_quest_have_pendants", _converter.ConvertDialogCompressed("{BOTTOM}\nCool beans, but I think you should mosey on over to the Lost Woods.") },
        { "sahasrahla_quest_have_master_sword", _converter.ConvertDialogCompressed("{BOTTOM}\nThat's a pretty sword, but I'm old, forgetful, and old. Why don't you go do all the hard work while I hang out in this hut.") },
        {  "sahasrahla_quest_information", _converter.ConvertDialogCompressed("{BOTTOM}\n"
            + "Sahasrahla, I am. You would do well to find the 3 pendants from the 3 dungeons in the Light World.\n"
            + "Understand?\n  ≥ yes\n    no\n{CHOICE}") },
        {  "sahasrahla_bring_courage", _converter.ConvertDialogCompressed("{BOTTOM}\n"
            + "While you're here, could you do me a solid and get the green pendant from that dungeon?\n"
            + "{HARP}\nI'll give you a present if you do.") },
        { "sahasrahla_have_ice_rod", _converter.ConvertDialogCompressed("{BOTTOM}\nLike, I sit here, and tell you what to do?\n\n\nAlright, go and find all the maidens, there are, like, maybe 7 of them. I dunno anymore. I'm old.") },
        { "telepathic_sahasrahla_beat_agahnim", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\nNice, so you beat Agahnim. Now you must beat Ganon. Good Luck!") },
        { "telepathic_sahasrahla_beat_agahnim_no_pearl", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\nOh, also you forgot the Moon Pearl, dingus. Go back and find it!") },
        { "sahasrahla_have_boots_no_icerod", _converter.ConvertDialogCompressed("{BOTTOM}\nCave in South East has a cool item.") },
        { "sahasrahla_have_courage", _converter.ConvertDialogCompressed("{BOTTOM}\nLook, you have the green pendant! I'll give you something. Go kill the other two bosses for more pendant fun!") },
        { "sahasrahla_found", _converter.ConvertDialogCompressed("{BOTTOM}\nYup!\n\nI'm the old man you are looking for. I'll keep it short and sweet: Go into that dungeon, then bring me the green pendant and talk to me again.") },
        { "sign_rain_north_of_links_house", _converter.ConvertDialogCompressed("↑ Dying Uncle\n  This way…") },
        { "sign_north_of_links_house", _converter.ConvertDialogCompressed("> Randomizer The telepathic tiles can have hints!") },
        { "sign_path_to_death_mountain", _converter.ConvertDialogCompressed("Cave to lost, old man.\nGood luck.") },
        { "sign_lost_woods", _converter.ConvertDialogCompressed("\n↑ Lost Woods") },
        { "sign_zoras", _converter.ConvertDialogCompressed("Danger!\nDeep water!\nZoras!") },
        { "sign_outside_magic_shop", _converter.ConvertDialogCompressed("Welcome to the Magic Shoppe") },
        // 0x40
        { "sign_death_mountain_cave_back", _converter.ConvertDialogCompressed("Cave away from sky cabbages") },
        { "sign_east_of_links_house", _converter.ConvertDialogCompressed("↓ Lake Hylia\n\n Also, a shop") },
        { "sign_south_of_lumberjacks", _converter.ConvertDialogCompressed("← Kakariko\n  Village") },
        { "sign_east_of_desert", _converter.ConvertDialogCompressed("← Desert\n\n     It's hot.") },
        { "sign_east_of_sanctuary", _converter.ConvertDialogCompressed("↑→ Potions!\n\nWish Waterfall") },
        { "sign_east_of_castle", _converter.ConvertDialogCompressed("→ East Palace\n\n← Castle") },
        { "sign_north_of_lake", _converter.ConvertDialogCompressed("\n Lake  Hylia") },
        { "sign_desert_thief", _converter.ConvertDialogCompressed("Don't talk to me or touch my sign!") },
        { "sign_lumberjacks_house", _converter.ConvertDialogCompressed("Lumberjacks, Inc.\nYou see 'em, we saw 'em.") },
        { "sign_north_kakariko", _converter.ConvertDialogCompressed("↓ Kakariko\n  Village") },
        { "witch_bring_mushroom", _converter.ConvertDialogCompressed("Double, double toil and trouble!\nBring me a mushroom!") },
        { "witch_brewing_the_item", _converter.ConvertDialogCompressed("This mushroom is busy brewing. Come back later.") },
        { "witch_assistant_no_bottle", _converter.ConvertDialogCompressed("You got to give me the mushroom, Numpty.") },
        { "witch_assistant_no_empty_bottle", _converter.ConvertDialogCompressed("Gotta use your stuff before you can get more.") },
        { "witch_assistant_informational", _converter.ConvertDialogCompressed("Red is life\nGreen is magic\nBlue is both\nI'll heal you for free, though.") },
        { "witch_assistant_no_bottle_buying", _converter.ConvertDialogCompressed("If only you had something to put that in, like a bottle…") },
        // 0x50
        { "potion_shop_no_empty_bottles", _converter.ConvertDialogCompressed("Whoa, bucko!\nNo empty bottles.") },
        { "item_get_lamp", _converter.ConvertDialogCompressed("Lamp! You can see in the dark, and light torches.") },
        { "item_get_boomerang", _converter.ConvertDialogCompressed("Boomerang! Press START to select it.") },
        { "item_get_bow", _converter.ConvertDialogCompressed("You're in bow mode now!") },
        { "item_get_shovel", _converter.ConvertDialogCompressed("This is my new mop. My friend George, he gave me this mop. It's a pretty good mop. It's not as good as my old mop. I miss my old mop. But it's still a good mop.") },
        { "item_get_magic_cape", _converter.ConvertDialogCompressed("Finally! We get to play Invisible Man!") },
        { "item_get_powder", _converter.ConvertDialogCompressed("It's the powder. Let's cause some mischief!") },
        { "item_get_flippers", _converter.ConvertDialogCompressed("Splish! Splash! Let's go take a bath!") },
        { "item_get_power_gloves", _converter.ConvertDialogCompressed("Feel the power! You can now lift light rocks! Rock on!") },
        { "item_get_pendant_courage", _converter.ConvertDialogCompressed("We have the Pendant of Courage! How brave!") },
        { "item_get_pendant_power", _converter.ConvertDialogCompressed("We have the Pendant of Power! How robust!") },
        { "item_get_pendant_wisdom", _converter.ConvertDialogCompressed("We have the Pendant of Wisdom! How astute!") },
        { "item_get_mushroom", _converter.ConvertDialogCompressed("A Mushroom! Don't eat it. Find a witch.") },
        { "item_get_book", _converter.ConvertDialogCompressed("It book! U R now litterit!") },
        { "item_get_moonpearl", _converter.ConvertDialogCompressed("I found a shiny marble! No more hops!") },
        { "item_get_compass", _converter.ConvertDialogCompressed("A compass! I can now find the boss.") },
        // 0x60
        { "item_get_map", _converter.ConvertDialogCompressed("Yo! You found a MAP! Press X to see it.") },
        { "item_get_ice_rod", _converter.ConvertDialogCompressed("It's the Ice Rod! Freeze Ray time.") },
        { "item_get_fire_rod", _converter.ConvertDialogCompressed("A Rod that shoots fire? Let's burn all the things!") },
        { "item_get_ether", _converter.ConvertDialogCompressed("We can chill out with this!") },
        { "item_get_bombos", _converter.ConvertDialogCompressed("Let's set everything on fire, and melt things!") },
        { "item_get_quake", _converter.ConvertDialogCompressed("Time to make the earth shake, rattle, and roll!") },
        { "item_get_hammer", _converter.ConvertDialogCompressed("STOP!\n\nHammer Time!") },  // 66
        { "item_get_ocarina", _converter.ConvertDialogCompressed("Finally! We can play the Song of Time!") },
        { "item_get_cane_of_somaria", _converter.ConvertDialogCompressed("Make blocks!\nThrow blocks!\nSplode Blocks!") },
        { "item_get_hookshot", _converter.ConvertDialogCompressed("BOING!!!\nBOING!!!\nSay no more…") },
        { "item_get_bombs", _converter.ConvertDialogCompressed("BOMBS! Use A to pick 'em up, throw 'em, get hurt!") },
        { "item_get_bottle", _converter.ConvertDialogCompressed("It's a terrarium. I hope we find a lizard!") },
        { "item_get_big_key", _converter.ConvertDialogCompressed("Yo! You got a Big Key!") },
        { "item_get_titans_mitts", _converter.ConvertDialogCompressed("So, like, you can now lift anything.\nANYTHING!") },
        { "item_get_magic_mirror", _converter.ConvertDialogCompressed("We could stare at this all day or, you know, beat Ganon…") },
        { "item_get_fake_mastersword", _converter.ConvertDialogCompressed("It's the Master Sword! …or not…\n\n         FOOL!") },
        // 0x70
        { "post_item_get_mastersword", _converter.ConvertDialogCompressed("{NOBORDER}\n{SPEED6}\n@, you got the sword!\n{CHANGEMUSIC}\nNow let's go beat up Agahnim!") },
        { "item_get_red_potion", _converter.ConvertDialogCompressed("Red goo to go! Nice!") },
        { "item_get_green_potion", _converter.ConvertDialogCompressed("Green goo to go! Nice!") },
        { "item_get_blue_potion", _converter.ConvertDialogCompressed("Blue goo to go! Nice!") },
        { "item_get_bug_net", _converter.ConvertDialogCompressed("Surprise Net! Let's catch stuff!") },
        { "item_get_blue_mail", _converter.ConvertDialogCompressed("Blue threads? Less damage activated!") },
        { "item_get_red_mail", _converter.ConvertDialogCompressed("You feel the power of the eggplant on your head.") },
        { "item_get_temperedsword", _converter.ConvertDialogCompressed("Nice… I now have a craving for Cheetos.") },
        { "item_get_mirror_shield", _converter.ConvertDialogCompressed("Pit would be proud!") },
        { "item_get_cane_of_byrna", _converter.ConvertDialogCompressed("It's the Blue Cane. You can now protect yourself with lag!") },
        { "missing_big_key", _converter.ConvertDialogCompressed("Something is missing…\nThe Big Key?") },
        { "missing_magic", _converter.ConvertDialogCompressed("Something is missing…\nMagic meter?") },
        { "item_get_pegasus_boots", _converter.ConvertDialogCompressed("Finally, it's bonking time!\nHold A to dash") },
        { "talking_tree_info_start", _converter.ConvertDialogCompressed("Whoa! I can talk again!") },
        { "talking_tree_info_1", _converter.ConvertDialogCompressed("Have you heard the good word about tree warp?") },
        { "talking_tree_info_2", _converter.ConvertDialogCompressed("Yank on the pitchfork in the center of town, ya heard it here.") },
        // 0x80
        { "talking_tree_info_3", _converter.ConvertDialogCompressed("There is a portal near the Lost Woods, ya heard it here.") },
        { "talking_tree_info_4", _converter.ConvertDialogCompressed("Use bombs to quickly kill the Hinox, ya heard it here.") },
        { "talking_tree_other", _converter.ConvertDialogCompressed("I can breathe!") },
        { "item_get_pendant_power_alt", _converter.ConvertDialogCompressed("We have the Pendant of Power! How robust!") },
        { "item_get_pendant_wisdom_alt", _converter.ConvertDialogCompressed("We have the Pendant of Wisdom! How astute!") },
        { "game_shooting_choice", _converter.ConvertDialogCompressed("20 rupees.\n5 arrows.\nWin rupees!\nWant to play?\n  ≥ Yes\n    No\n{CHOICE}") },
        { "game_shooting_yes", _converter.ConvertDialogCompressed("Let's do this!") },
        { "game_shooting_no", _converter.ConvertDialogCompressed("Where are you going? Straight up!") },
        { "game_shooting_continue", _converter.ConvertDialogCompressed("Keep playing?\n  ≥ Yes\n    No\n{CHOICE}") },
        { "pond_of_wishing", _converter.ConvertDialogCompressed("-Wishing Pond-\n\n On Vacation") },
        { "pond_item_select", _converter.ConvertDialogCompressed("Pick something\nto throw in.\n{ITEMSELECT}") },
        { "pond_item_test", _converter.ConvertDialogCompressed("You toss this?\n  ≥ Yup\n    Wrong\n{CHOICE}") },
        { "pond_will_upgrade", _converter.ConvertDialogCompressed("You're honest, so I'll give you a present.") },
        { "pond_item_test_no", _converter.ConvertDialogCompressed("You sure?\n  ≥ Oh yeah\n    Um…\n{CHOICE}") },
        { "pond_item_test_no_no", _converter.ConvertDialogCompressed("Well, I don't want it, so take it back.") },
        { "pond_item_boomerang", _converter.ConvertDialogCompressed("I don't much like you, so have this worse Boomerang.") },
        // 0x90
        { "pond_item_shield", _converter.ConvertDialogCompressed("I grant you the ability to block fireballs. Don't lose this to a Pikit!") },
        { "pond_item_silvers", _converter.ConvertDialogCompressed("So, wouldn't it be nice to kill Ganon? These should help in the final phase.") },
        { "pond_item_bottle_filled", _converter.ConvertDialogCompressed("Bottle filled!\nMoney saved!") },
        { "pond_item_sword", _converter.ConvertDialogCompressed("Thank you for the sword, here is a stick of butter.") },
        { "pond_of_wishing_happiness", _converter.ConvertDialogCompressed("Happiness up!\nYou are now\nᚌᚋ happy!") },
        { "pond_of_wishing_choice", _converter.ConvertDialogCompressed("Your wish?\n  ≥More bombs\n   More arrows\n{CHOICE}") },
        { "pond_of_wishing_bombs", _converter.ConvertDialogCompressed("Woo-hoo!\nYou can now\ncarry ᚌᚋ bombs") },
        { "pond_of_wishing_arrows", _converter.ConvertDialogCompressed("Woo-hoo!\nYou can now\nhold ᚌᚋ arrows") },
        { "pond_of_wishing_full_upgrades", _converter.ConvertDialogCompressed("You have all I can give you, here are your rupees back.") },
        { "mountain_old_man_first", _converter.ConvertDialogCompressed("Look out for holes, and monsters.") },
        { "mountain_old_man_deadend", _converter.ConvertDialogCompressed("Oh, goody, hearts in jars! This place is creepy.") },
        { "mountain_old_man_turn_right", _converter.ConvertDialogCompressed("Turn right. Let's get out of this place.") },
        { "mountain_old_man_lost_and_alone", _converter.ConvertDialogCompressed("Hello. I can't see anything. Take me with you.") },
        { "mountain_old_man_drop_off", _converter.ConvertDialogCompressed("Here's a thing to help you, good luck!") },
        { "mountain_old_man_in_his_cave_pre_agahnim", _converter.ConvertDialogCompressed("You need to beat the tower at the top of the mountain.") },
        { "mountain_old_man_in_his_cave", _converter.ConvertDialogCompressed("You can find stuff in the tower at the top of this mountain.\nCome see me if you'd like to be healed.") },
        // 0xA0
        { "mountain_old_man_in_his_cave_post_agahnim", _converter.ConvertDialogCompressed("You should be heading to the castle… you have a portal there now.\nSay hi anytime you like.") },
        { "tavern_old_man_awake", _converter.ConvertDialogCompressed("Life? Love? Happiness? The question you should really ask is: Was this generated by Stoops Alu or Stoops Jet?") },
        { "tavern_old_man_unactivated_flute", _converter.ConvertDialogCompressed("You should play that flute for the weathervane, cause reasons.") },
        { "tavern_old_man_know_tree_unactivated_flute", _converter.ConvertDialogCompressed("You should play that flute for the weathervane, cause reasons.") },
        { "tavern_old_man_have_flute", _converter.ConvertDialogCompressed("Life? Love? Happiness? The question you should really ask is: Was this generated by Stoops Alu or Stoops Jet?") },
        { "chicken_hut_lady", _converter.ConvertDialogCompressed("This is\nChristos' hut.\n\nHe's out, searching for a bow.") },
        { "running_man", _converter.ConvertDialogCompressed("Hi, Do you\nknow Veetorp?\n\nYou really\nshould. And\nall the other great guys who made this possible.\nGo thank them.\n\n\nIf you can catch them…") },
        { "game_race_sign", _converter.ConvertDialogCompressed("Why are you reading this sign? Run!!!") },
        { "sign_bumper_cave", _converter.ConvertDialogCompressed("You need Cape, but not Hookshot") },
        { "sign_catfish", _converter.ConvertDialogCompressed("Toss rocks\nToss items\nToss cookies") },
        { "sign_north_village_of_outcasts", _converter.ConvertDialogCompressed("↑ Skull Woods\n\n↓ Steve's Town") },
        { "sign_south_of_bumper_cave", _converter.ConvertDialogCompressed("\n→ Kat's cave") },
        { "sign_east_of_pyramid", _converter.ConvertDialogCompressed("\n→ Dark Palace") },
        { "sign_east_of_bomb_shop", _converter.ConvertDialogCompressed("\n← Bomb Shoppe") },
        { "sign_east_of_mire", _converter.ConvertDialogCompressed("\n← Misery Mire\n No way in.\n No way out.") },
        { "sign_village_of_outcasts", _converter.ConvertDialogCompressed("Have a Trulie Awesome Day!") },
        // 0xB0
        { "sign_before_wishing_pond", _converter.ConvertDialogCompressed("Waterfall\nup ahead\nMake wishes") },
        { "sign_before_catfish_area", _converter.ConvertDialogCompressed("→↑ Have you met Woeful Ike?") },
        { "castle_wall_guard", _converter.ConvertDialogCompressed("Looking for a Princess? Look downstairs.") },
        { "gate_guard", _converter.ConvertDialogCompressed("No Lonks Allowed!") },
        { "telepathic_tile_eastern_palace", _converter.ConvertDialogCompressed("{NOBORDER}\nYou need a Bow to get past the red Eyegore. derpy") },
        { "telepathic_tile_tower_of_hera_floor_4", _converter.ConvertDialogCompressed("{NOBORDER}\nIf you find a shiny ball, you can be you in the Dark World.") },
        { "hylian_text_1", _converter.ConvertDialogCompressed("%== %== %==\n ^ %==% ^\n%== ^%%^ ==^") },
        { "mastersword_pedestal_translated", _converter.ConvertDialogCompressed("A test of strength: If you have 3 pendants, I'm yours.") },
        { "telepathic_tile_spectacle_rock", _converter.ConvertDialogCompressed("{NOBORDER}\nUse the Mirror, or the Hookshot and Hammer, to get to Tower of Hera!") },
        { "telepathic_tile_swamp_entrance", _converter.ConvertDialogCompressed("{NOBORDER}\nDrain the floodgate to raise the water here!") },
        { "telepathic_tile_thieves_town_upstairs", _converter.ConvertDialogCompressed("{NOBORDER}\nBlind hates bright light.") },
        { "telepathic_tile_misery_mire", _converter.ConvertDialogCompressed("{NOBORDER}\nLighting 4 torches will open your way forward!") },
        { "hylian_text_2", _converter.ConvertDialogCompressed("%%^= %==%\n ^ =%^=\n==%= ^^%^") },
        { "desert_entry_translated", _converter.ConvertDialogCompressed("Kneel before this stone, and magic will move around you.") },
        {  "telepathic_tile_under_ganon", _converter.ConvertDialogCompressed(
                "   ALTTPR League"
            + "          Winners\n{HARP}\n\n"
            + "  ~~~Season 5~~~\n     OKDUDES: \n  GanonsGoneWild\n     Telethar\n   Hitsuyan1337\n\n"
            + "  ~~~Season 4~~~\nThe Titan's Mitts:\n    SailorNep\n     Relkin\n     Daaanty\n\n"
            + "  ~~~Season 3~~~\nPhendrana Drifters:\n     Megawott\n   Frostbite3030\n      Jet082\n\n"
            + "  ~~~Season 2~~~\n    Team すごい:\n    IIYoshiII\n   Hitsuyan1337\n     Ramond\n\n"
            + "  ~~~Season 1~~~\n    Team すごい:\n    IIYoshiII\n      Thalane\n   Hitsuyan1337\n\n"
            ) },
        { "telepathic_tile_palace_of_darkness", _converter.ConvertDialogCompressed("{NOBORDER}\nThis is a funny looking Enemizer.") },
        // 0xC0
        { "telepathic_tile_desert_bonk_torch_room", _converter.ConvertDialogCompressed("{NOBORDER}\nThings can be knocked down, if you fancy yourself a dashing dude.") },
        { "telepathic_tile_castle_tower", _converter.ConvertDialogCompressed("{NOBORDER}\nYou can reflect Agahnim's energy with Sword, Bug-net or Hammer.") },
        { "telepathic_tile_ice_large_room", _converter.ConvertDialogCompressed("{NOBORDER}\nAll right stop collaborate and listen\nIce is back with my brand new invention.") },
        { "telepathic_tile_turtle_rock", _converter.ConvertDialogCompressed("{NOBORDER}\nYou Shall Not Pass… without the Red Cane.") },
        { "telepathic_tile_ice_entrace", _converter.ConvertDialogCompressed("{NOBORDER}\nYou can use Fire Rod or Bombos to pass.") },
        { "telepathic_tile_ice_stalfos_knights_room", _converter.ConvertDialogCompressed("{NOBORDER}\nKnock 'em down and then bomb them dead.") },
        { "telepathic_tile_tower_of_hera_entrance", _converter.ConvertDialogCompressed("{NOBORDER}\nThis is a bad place, with a guy who will make you fall…\n\n\na lot.") },
        {  "houlihan_room", _converter.ConvertDialogCompressed(
                "     Randomizer\n"
            + "Tournament Winners\n\n{HARP}\n"
            + "    ~~~2023~~~\n  GanonsGoneWild\n\n"
            + "    ~~~2022~~~\n      Obscure\n\n"
            + "    ~~~2021~~~\n      Daaanty\n\n"
            + "    ~~~2019~~~\n      Jet082\n\n"
            + "    ~~~2018~~~\n      S: Andy\n      A: Andy\n"
            + "    ~~~2017~~~\n    S: ajneb174\n    A: ajneb174"
        ) },
        { "caught_a_bee", _converter.ConvertDialogCompressed("Caught a Bee\n  ≥ Keep\n    Release\n{CHOICE}") },
        { "caught_a_fairy", _converter.ConvertDialogCompressed("Caught Fairy!\n  ≥ Keep\n    Release\n{CHOICE}") },
        { "no_empty_bottles", _converter.ConvertDialogCompressed("Whoa, bucko!\nNo empty bottles.") },
        { "game_race_boy_time", _converter.ConvertDialogCompressed("Your time was\nᚎᚍ min ᚌᚋ sec.") },
        { "game_race_girl", _converter.ConvertDialogCompressed("You have 15 seconds,\nGo… Go… Go…") },
        { "game_race_boy_success", _converter.ConvertDialogCompressed("Nice!\nYou can have this trash!") },
        { "game_race_boy_failure", _converter.ConvertDialogCompressed("Too slow!\nI keep my\nprecious!") },
        { "game_race_boy_already_won", _converter.ConvertDialogCompressed("You already have your prize, dingus!") },
        // 0xD0
        { "game_race_boy_sneaky", _converter.ConvertDialogCompressed("Thought you could sneak in, eh?") },
        { "bottle_vendor_choice", _converter.ConvertDialogCompressed("I gots bottles.\nYous gots 100 rupees?\n  ≥ I want\n    No way!") },
        { "bottle_vendor_get", _converter.ConvertDialogCompressed("Nice! Hold it up son! Show the world what you got!") },
        { "bottle_vendor_no", _converter.ConvertDialogCompressed("Fine! I didn't want your money anyway.") },
        { "bottle_vendor_already_collected", _converter.ConvertDialogCompressed("Dude! You already have it.") },
        { "bottle_vendor_bee", _converter.ConvertDialogCompressed("Cool! A bee! Here's 100 rupees.") },
        { "bottle_vendor_fish", _converter.ConvertDialogCompressed("Whoa! A fish! You walked this all the way here?") },
        { "hobo_item_get_bottle", _converter.ConvertDialogCompressed("You think life is rough? I guess you can take my last item. Except this tent. That's MY tent!") },
        { "blacksmiths_what_you_want", _converter.ConvertDialogCompressed("Nice of you to come back!\nWould you like us mess with your sword?\n  ≥ Temper\n    It's fine\n{CHOICE}") },
        { "blacksmiths_paywall", _converter.ConvertDialogCompressed("It's 10 rupees\n  ≥ Easy\n    Hang on…\n{CHOICE}") },
        { "blacksmiths_extra_okay", _converter.ConvertDialogCompressed("Are you sure you're sure ?\n  ≥ Ah, yup\n    Hang on…\n{CHOICE}") },
        { "blacksmiths_tempered_already", _converter.ConvertDialogCompressed("Whelp… We can't make this any better.") },
        { "blacksmiths_temper_no", _converter.ConvertDialogCompressed("Oh, come by any time!") },
        { "blacksmiths_bogart_sword", _converter.ConvertDialogCompressed("We're going to have to take it to work on it.") },
        { "blacksmiths_get_sword", _converter.ConvertDialogCompressed("Sword is done. Now, back to our bread!") },
        { "blacksmiths_shop_before_saving", _converter.ConvertDialogCompressed("I lost my friend. Help me find him!") },
        // 0xE0
        { "blacksmiths_shop_saving", _converter.ConvertDialogCompressed("You found him! Colour me happy! Come back right away and we will bang on your sword.") },
        { "blacksmiths_collect_frog", _converter.ConvertDialogCompressed("Ribbit! Ribbit! Let's find my partner. To the shop!") },
        { "blacksmiths_still_working", _converter.ConvertDialogCompressed("Something this precious takes time… Come back later.") },
        { "blacksmiths_saving_bows", _converter.ConvertDialogCompressed("Thanks!\n\nThanks!") },
        { "blacksmiths_hammer_anvil", _converter.ConvertDialogCompressed("Dernt Take Er Jerbs!") },
        { "dark_flute_boy_storytime", _converter.ConvertDialogCompressed("Hi!\nI'm Stumpy!\nI've been chillin' in this world for a while now, but I miss my flute.If I gave you a shovel, would you go digging for it ?\n  ≥ Sure\n    Nahh\n{CHOICE}") },
        { "dark_flute_boy_get_shovel", _converter.ConvertDialogCompressed("Schaweet! Here you go. Happy digging!") },
        { "dark_flute_boy_no_get_shovel", _converter.ConvertDialogCompressed("Oh I see, not good enough for you… FINE!") },
        { "dark_flute_boy_flute_not_found", _converter.ConvertDialogCompressed("Still haven't found the item? Dig in the Light World around here, dingus!") },
        { "dark_flute_boy_after_shovel_get", _converter.ConvertDialogCompressed("So I gave you an item, and you're still here.\n\n\n\n\n\nI mean, we can sit here and stare at each other, if you like…\n\n\n\n\n\n\n\nFine, I guess you should just go.") },
        { "shop_fortune_teller_lw_hint_0", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, the book opens the desert") },
        { "shop_fortune_teller_lw_hint_1", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, nothing doing") },
        { "shop_fortune_teller_lw_hint_2", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, I'm cheap") },
        { "shop_fortune_teller_lw_hint_3", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, am I cheap?") },
        { "shop_fortune_teller_lw_hint_4", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, Zora lives at the end of the river") },
        { "shop_fortune_teller_lw_hint_5", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, The Cape can pass through the barrier") },
        // 0xF0
        { "shop_fortune_teller_lw_hint_6", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, Spin, Hammer, or Net to hurt Agahnim") },
        { "shop_fortune_teller_lw_hint_7", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, You can jump in the well by the blacksmiths") },
        { "shop_fortune_teller_lw_no_rupees", _converter.ConvertDialogCompressed("{BOTTOM}\nThe black cats are hungry, come back with rupees") },
        { "shop_fortune_teller_lw", _converter.ConvertDialogCompressed("{BOTTOM}\nWelcome to the Fortune Shoppe!\nFancy a read?\n  ≥I must know\n   Negative\n{CHOICE}") },
        { "shop_fortune_teller_lw_post_hint", _converter.ConvertDialogCompressed("{BOTTOM}\nFor ᚋᚌ rupees\nIt is done.\nBe gone!") },
        { "shop_fortune_teller_lw_no", _converter.ConvertDialogCompressed("{BOTTOM}\nWell then, why did you even come in here?") },
        { "shop_fortune_teller_lw_hint_8", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, why you do?") },
        { "shop_fortune_teller_lw_hint_9", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, panda crackers") },
        { "shop_fortune_teller_lw_hint_10", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, the missing blacksmith is south of the Village of Outcasts") },
        { "shop_fortune_teller_lw_hint_11", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, open chests to get stuff") },
        { "shop_fortune_teller_lw_hint_12", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, you can buy a new bomb at the Bomb Shoppe") },
        { "shop_fortune_teller_lw_hint_13", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, big bombs blow up cracked walls in pyramids") },
        { "shop_fortune_teller_lw_hint_14", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, you need all the crystals to open Ganon's Tower") },
        { "shop_fortune_teller_lw_hint_15", _converter.ConvertDialogCompressed("{BOTTOM}\nBy the black cats, Silver Arrows will defeat Ganon in his final phase") },
        { "dark_sanctuary", _converter.ConvertDialogCompressed("For 20 rupees I'll tell you something?\nHow about it?\n  ≥ Yes\n    No\n{CHOICE}") },
        { "dark_sanctuary_hint_0", _converter.ConvertDialogCompressed("I once was a tea kettle, but then I moved up in the world, and now you can see me as this. Makes you wonder what I could be next time.") },
        // 0x100
        { "dark_sanctuary_no", _converter.ConvertDialogCompressed("Then go away!") },
        { "dark_sanctuary_hint_1", _converter.ConvertDialogCompressed("There is a thief in the desert, he can open creepy chests that follow you. But now that we have that out of the way, do you like my hair? I've spent eons getting it this way.") },
        { "dark_sanctuary_yes", _converter.ConvertDialogCompressed("With Crystals 5&6, you can find a great fairy in the pyramid.\n\nFlomp Flomp, Whizzle Whomp") },
        { "dark_sanctuary_hint_2", _converter.ConvertDialogCompressed("All I can say is that my life is pretty plain\n"
            + "I like watchin' the puddles gather rain,\n"
            + "And all I can do is just pour some tea for two,\n"
            + "And speak my point of view but it's not sane,\n"
            + "It's not sane") },
        { "sick_kid_no_bottle", _converter.ConvertDialogCompressed("{BOTTOM}\nI'm sick! Show me a bottle, get something!") },
        { "sick_kid_trade", _converter.ConvertDialogCompressed("{BOTTOM}\nCool bottle! Here's something for you.") },
        { "sick_kid_post_trade", _converter.ConvertDialogCompressed("{BOTTOM}\nLeave me alone\nI'm sick. You have my item.") },
        { "desert_thief_sitting", _converter.ConvertDialogCompressed("………………………") },
        { "desert_thief_following", _converter.ConvertDialogCompressed("Why……………") },
        { "desert_thief_question", _converter.ConvertDialogCompressed("I was a thief. I open purple chests!\nKeep secret?\n  ≥ Sure thing\n    Never!\n{CHOICE}") },
        { "desert_thief_question_yes", _converter.ConvertDialogCompressed("Cool, bring me any purple chests you find.") },
        { "desert_thief_after_item_get", _converter.ConvertDialogCompressed("You tell anyone and I will give you such a pinch!") },
        { "desert_thief_reassure", _converter.ConvertDialogCompressed("Bring chests. It's a secret to everyone.") },
        { "hylian_text_3", _converter.ConvertDialogCompressed("^^ ^%=^= =%=\n=%% =%%=^\n==%^= %=^^%") },
        { "tablet_ether_book", _converter.ConvertDialogCompressed("Can you make things fall out of the sky? With the Master Sword, you can!") },
        { "tablet_bombos_book", _converter.ConvertDialogCompressed("Can you make things fall out of the sky? With the Master Sword, you can!") },
        // 0x110
        { "magic_bat_wake", _converter.ConvertDialogCompressed("You bum! I was sleeping! Where's my magic bolts?") },
        { "magic_bat_give_half_magic", _converter.ConvertDialogCompressed("How you like me now?") },
        {  "intro_main", _converter.ConvertDialogCompressed("{INTRO}\n Episode  III\n{PAUSE3}\n A Link to\n   the Past\n"
            + "{PAUSE3}\n  Randomizer\n{PAUSE3}\nAfter mostly disregarding what happened in the first two games.\n"
            + "{PAUSE3}\nLink awakens to his uncle leaving the house.\n{PAUSE3}\nHe just runs out the door,\n"
            + "{PAUSE3}\ninto the rainy night.\n{PAUSE3}\n{CHANGEPIC}\nGanon has moved around all the items in Hyrule.\n"
            + "{PAUSE7}\nYou will have to find all the items necessary to beat Ganon.\n"
            + "{PAUSE7}\nThis is your chance to be a hero.\n{PAUSE3}\n{CHANGEPIC}\n"
            + "You must get enough crystals to beat Ganon.\n{PAUSE9}\n{CHANGEPIC}", false) },
        { "intro_throne_room", _converter.ConvertDialogCompressed("{IBOX}\nLook at this Stalfos on the throne.", false) },
        { "intro_zelda_cell", _converter.ConvertDialogCompressed("{IBOX}\nIt is your time to shine!", false) },
        { "intro_agahnim", _converter.ConvertDialogCompressed("{IBOX}\nAlso, you need to defeat this guy!", false) },
        { "pickup_purple_chest", _converter.ConvertDialogCompressed("A curious box. Let's take it with us!") },
        { "bomb_shop", _converter.ConvertDialogCompressed("30 bombs for 100 rupees. Good deals all day!") },
        { "bomb_shop_big_bomb", _converter.ConvertDialogCompressed("30 bombs for 100 rupees, 100 rupees 1 BIG bomb. Good deals all day!") },
        { "bomb_shop_big_bomb_buy", _converter.ConvertDialogCompressed("Thanks!\nBoom goes the dynamite!") },
        { "item_get_big_bomb", _converter.ConvertDialogCompressed("YAY! Press A to 'splode it!") },
        { "kiki_second_extortion", _converter.ConvertDialogCompressed("For 100 more, I'll open this place.\nHow about it?\n  ≥ Open\n    Nah\n{CHOICE}") },
        { "kiki_second_extortion_no", _converter.ConvertDialogCompressed("Heh, good luck getting in.") },
        { "kiki_second_extortion_yes", _converter.ConvertDialogCompressed("Yay! Rupees!\nOkay, let's do this!") },
        { "kiki_first_extortion", _converter.ConvertDialogCompressed("I'm Kiki. I like rupees, may I have 10?\nHow about it?\n  ≥ Yes\n    No\n{CHOICE}") },
        { "kiki_first_extortion_yes", _converter.ConvertDialogCompressed("Nice. I'll tag along with you for a bit.") },
        // 0x120
        { "kiki_first_extortion_no", _converter.ConvertDialogCompressed("Pfft. I have no reason to hang. See ya!") },
        { "kiki_leaving_screen", _converter.ConvertDialogCompressed("No no no no no! We should play by my rules! Goodbye…") },
        { "blind_in_the_cell", _converter.ConvertDialogCompressed("You saved me!\nPlease get me out of here!") },
        { "blind_by_the_light", _converter.ConvertDialogCompressed("Aaaahhhh~!\nS-so bright~!") },
        { "blind_not_that_way", _converter.ConvertDialogCompressed("No! Don't go that way!") },
        { "aginah_l1sword_no_book", _converter.ConvertDialogCompressed("I once had a fish dinner. I still remember it to this day.") },
        { "aginah_l1sword_with_pendants", _converter.ConvertDialogCompressed("Do you remember when I was young?\n\nI sure don't.") },
        { "aginah", _converter.ConvertDialogCompressed("So, I've been living in this cave for years, and you think you can just come along and bomb open walls?") },
        { "aginah_need_better_sword", _converter.ConvertDialogCompressed("Once, I farted in this cave so bad all the jazz hands guys ran away and hid in the sand.") },
        { "aginah_have_better_sword", _converter.ConvertDialogCompressed("Pandas are very vicious animals. Never forget…\n\n\n\n\nI never will…") },
        { "catfish", _converter.ConvertDialogCompressed("You woke me from my nap! Take this, and get out!") },
        { "catfish_after_item", _converter.ConvertDialogCompressed("I don't have anything else for you!\nTake this!") },
        // 12C
        { "lumberjack_right", _converter.ConvertDialogCompressed("One of us always lies.") },
        { "lumberjack_left", _converter.ConvertDialogCompressed("One of us always tells the truth.") },
        { "lumberjack_left_post_agahnim", _converter.ConvertDialogCompressed("One of us likes peanut butter.") },
        { "fighting_brothers_right", _converter.ConvertDialogCompressed("I walled off my brother Leo.\n\nWhat a dingus.") },
        // 0x130
        { "fighting_brothers_right_opened", _converter.ConvertDialogCompressed("Now I should probably talk to him…") },
        { "fighting_brothers_left", _converter.ConvertDialogCompressed("Did you come from my brother's room?\n\nAre we cool?") },
        { "maiden_crystal_1", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty red dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_2", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty blue dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_3", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty gold dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_4", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty redder dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_5", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty green dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_6", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nI have a pretty green dress.\n{SPEED1}\n{SPEED2}Just thought I would tell you.") },
        { "maiden_crystal_7", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nIt's about friggin time.\n{SPEED1}\n{SPEED2}Do you know how long I've been waiting?!") },
        { "maiden_ending", _converter.ConvertDialogCompressed("May the way of the hero lead to the Triforce.") },
        { "maiden_confirm_undersood", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nCapisce?\n  ≥ Yes\n    No\n{CHOICE}") },
        { "barrier_breaking", _converter.ConvertDialogCompressed("What did the seven crystals say to Ganon's Tower ? ") },
        { "maiden_crystal_7_again", _converter.ConvertDialogCompressed("{SPEED2}\n{BOTTOM}\n{NOBORDER}\nIt's about friggin time.\n{SPEED1}\n{SPEED2}Do you know how long I've been waiting?!") },
        { "agahnim_zelda_teleport", _converter.ConvertDialogCompressed("I am a magician, and this is my act. Watch as I make this girl disappear!") },
        { "agahnim_magic_running_away", _converter.ConvertDialogCompressed("And now, the end is near\nAnd so I face the final curtain\nMy friend, I'll say it clear\nI'll state my case, of which I'm certain\nI've lived a life that's full\nI've traveled each and every highway\nBut more, much more than this\nI did it my way") },
        { "agahnim_hide_and_seek_found", _converter.ConvertDialogCompressed("Peek-a-boo!") },
        // 0x140
        { "agahnim_defeated", _converter.ConvertDialogCompressed("Arrrgggghhh. Well you're coming with me!") },
        { "agahnim_final_meeting", _converter.ConvertDialogCompressed("You have done well to come this far. Now, die!") },
        // 0x142
        { "zora_meeting", _converter.ConvertDialogCompressed("What do you want?\n  ≥ Flippers\n    Nothin'\n{CHOICE}") },
        { "zora_tells_cost", _converter.ConvertDialogCompressed("Fine! But they aren't cheap.You got 500 rupees?\n  ≥ Duh\n    Oh carp\n{CHOICE}") },
        { "zora_get_flippers", _converter.ConvertDialogCompressed("Here's some Flippers for you! Swim little fish, swim.") },
        { "zora_no_cash", _converter.ConvertDialogCompressed("Fine!\nGo get some more money first.") },
        { "zora_no_buy_item", _converter.ConvertDialogCompressed("Wah hoo! Well, whenever you want to see these gills, stop on by.") },
        { "kakariko_saharalasa_grandson", _converter.ConvertDialogCompressed("My grandpa is over in the East. I'm bad with directions. I'll mark your map. Best of luck!\n{HARP}") },
        { "kakariko_saharalasa_grandson_next", _converter.ConvertDialogCompressed("Someday I'll be in a high school band!") },
        { "dark_palace_tree_dude", _converter.ConvertDialogCompressed("Did you know…\n\n\nA tree typically has many secondary branches supported clear of the ground by the trunk. This trunk typically contains woody tissue for strength, and vascular tissue to carry materials from one part of the tree to another.") },
        { "fairy_wishing_ponds", _converter.ConvertDialogCompressed("\n-Wishing pond-\n\nThrow item in?\n  ≥ Yesh\n    No\n{CHOICE}") },
        { "fairy_wishing_ponds_no", _converter.ConvertDialogCompressed("\n   Stop it!") },
        { "pond_of_wishing_no", _converter.ConvertDialogCompressed("\n  Fine then!") },
        { "pond_of_wishing_return_item", _converter.ConvertDialogCompressed("Okay. Here's your item back, 'cause I can't use it. I'm stuck in this fountain.") },
        { "pond_of_wishing_throw", _converter.ConvertDialogCompressed("How many?\n  ≥ᚌᚋ rupees\n   ᚎᚍ rupees\n{CHOICE}") },
        { "pond_pre_item_silvers", _converter.ConvertDialogCompressed("I like you, so here's a thing you can use to beat up Ganon.") },
        // 0x150
        { "pond_of_wishing_great_luck", _converter.ConvertDialogCompressed("\nis great luck") },
        { "pond_of_wishing_good_luck", _converter.ConvertDialogCompressed("\n is good luck") },
        { "pond_of_wishing_meh_luck", _converter.ConvertDialogCompressed("\n is meh luck") },
        // Repurposed to no items in Randomizer
        { "pond_of_wishing_bad_luck", _converter.ConvertDialogCompressed("Why you come in here and pretend like you have something this fountain wants? Come back with bottles!") },
        { "pond_of_wishing_fortune", _converter.ConvertDialogCompressed("By the way, your fortune,") },
        { "item_get_14_heart", _converter.ConvertDialogCompressed("3 more to go\n      ¼\nYay!") },
        { "item_get_24_heart", _converter.ConvertDialogCompressed("2 more to go\n      ½\nWhee!") },
        { "item_get_34_heart", _converter.ConvertDialogCompressed("1 more to go\n      ¾\nGood job!") },
        { "item_get_whole_heart", _converter.ConvertDialogCompressed("You got a whole ♥!!\nGo you!") },
        { "item_get_sanc_heart", _converter.ConvertDialogCompressed("You got a whole ♥!\nGo you!") },
        { "fairy_fountain_refill", _converter.ConvertDialogCompressed("Well done, lettuce have a cup of tea…") },
        { "death_mountain_bullied_no_pearl", _converter.ConvertDialogCompressed("I wrote a word. Just one. On a stone and threw it into the ocean. It was my word. It was what would save me. I hope someday someone finds that word and brings it to me. The word is the beginning of my song.") },
        { "death_mountain_bullied_with_pearl", _converter.ConvertDialogCompressed("I wrote a song. Just one. On a guitar and threw it into the sky. It was my song. It could tame beasts and free minds. It flitters on the wind and lurks in our minds. It is the song of nature, of humanity, of dreams and dreamers.") },
        { "death_mountain_bully_no_pearl", _converter.ConvertDialogCompressed("Add garlic, ginger and apple and cook for 2 minutes. Add carrots, potatoes, garam masala and curry powder and stir well. Add tomato paste, stir well and slowly add red wine and bring to a boil. Add sugar, soy sauce and water, stir and bring to a boil again.") },
        { "death_mountain_bully_with_pearl", _converter.ConvertDialogCompressed("I think I forgot how to smile…") },
        { "shop_darkworld_enter",  _converter.ConvertDialogCompressed("It's dangerous outside, buy my crap for safety.") },
        // 0x160
        { "game_chest_village_of_outcasts", _converter.ConvertDialogCompressed("Pay 30 rupees, open 2 chests. Are you lucky?\nSo, play game?\n  ≥ Play\n    Never!\n{CHOICE}") },
        { "game_chest_no_cash", _converter.ConvertDialogCompressed("So, like, you need 30 rupees.\nSilly!") },
        { "game_chest_not_played", _converter.ConvertDialogCompressed("You want to play a game?\nTalk to me.") },
        { "game_chest_played", _converter.ConvertDialogCompressed("You've opened the chests!\nTime to go.") },
        { "game_chest_village_of_outcasts_play", _converter.ConvertDialogCompressed("Alright, brother!\nGo play!") },
        { "shop_first_time", _converter.ConvertDialogCompressed("Welcome to my shop! Select stuff with A.\nDO IT NOW!") },
        { "shop_already_have", _converter.ConvertDialogCompressed("So, like, you already have one of those.") },
        { "shop_buy_shield", _converter.ConvertDialogCompressed("Thanks! Now you can block fire balls.") },
        { "shop_buy_red_potion", _converter.ConvertDialogCompressed("Red goo, so good! It's like a fairy in a bottle, except you have to activate it yourself.") },
        { "shop_buy_arrows", _converter.ConvertDialogCompressed("Arrows! Cause you were too lazy to look under some pots!") },
        { "shop_buy_bombs", _converter.ConvertDialogCompressed("You bought bombs. What, couldn't find any under bushes?") },
        { "shop_buy_bee", _converter.ConvertDialogCompressed("He's my best friend.Please take care of him, and never lose him.") },
        { "shop_buy_heart", _converter.ConvertDialogCompressed("You really just bought this?") },
        { "shop_first_no_bottle_buy", _converter.ConvertDialogCompressed("Why does no one own bottles? Go find one first!") },
        { "shop_buy_no_space", _converter.ConvertDialogCompressed("You are carrying to much crap, go use some of it first!") },
        { "ganon_fall_in", _converter.ConvertDialogCompressed("You drove\naway my other\nself, Agahnim,\ntwo times…\nBut, I won't\ngive you the\nTriforce.\nI'll defeat\nyou!") },
        // 0x170
        { "ganon_phase_3", _converter.ConvertDialogCompressed("Can you beat\nmy darkness\ntechnique?") },
        { "lost_woods_thief", _converter.ConvertDialogCompressed("Have you seen Andy?\n\nHe was out looking for our prized Ether medallion.\nI wonder when he will be back?") },
        { "blinds_hut_dude", _converter.ConvertDialogCompressed("I'm just some dude. This is Blind's hut.") },
        { "end_triforce", _converter.ConvertDialogCompressed("{SPEED2}\n{MENU}\n{NOBORDER}\n     G G") },
        // 0x174
        { "toppi_fallen", _converter.ConvertDialogCompressed("Ouch!\n\nYou jerk!") },
        { "kakariko_tavern_fisherman", _converter.ConvertDialogCompressed("Don't argue\nwith a frozen\nDeadrock.\nHe'll never\nchange his\nposition!") },
        { "thief_money", _converter.ConvertDialogCompressed("It's a secret to everyone.") },
        { "thief_desert_rupee_cave", _converter.ConvertDialogCompressed("So you, like, busted down my door, and are being a jerk by talking to me? Normally I would be angry and make you pay for it, but I bet you're just going to break all my pots and steal my 50 rupees.") },
        { "thief_ice_rupee_cave", _converter.ConvertDialogCompressed("I'm a rupee pot farmer. One day I will take over the world with my skillz. Have you met my brother in the desert? He's way richer than I am.") },
        { "telepathic_tile_south_east_darkworld_cave", _converter.ConvertDialogCompressed("~~ dev cave ~~\n  no farming\n   required") },
        // 0x17A
        { "cukeman", _converter.ConvertDialogCompressed("Did you hear that Veetorp beat ajneb174 in a 1 on 1 race at AGDQ?") },
        { "cukeman_2", _converter.ConvertDialogCompressed("You found Shabadoo, huh?\nNiiiiice.") },
        { "potion_shop_no_cash", _converter.ConvertDialogCompressed("Yo! I'm not running a charity here.") },
        { "kakariko_powdered_chicken", _converter.ConvertDialogCompressed("Smallhacker…\n\n\nWas hiding, you found me!\n\n\nOkay, you can leave now.") },
        { "game_chest_south_of_kakariko", _converter.ConvertDialogCompressed("Pay 20 rupees, open 1 chest. Are you lucky?\nSo, play game?\n  ≥ Play\n    Never!\n{CHOICE}") },
        { "game_chest_play_yes", _converter.ConvertDialogCompressed("Good luck then.") },
        // 0x180
        { "game_chest_play_no", _converter.ConvertDialogCompressed("Well fine, I didn't want your rupees.") },
        { "game_chest_lost_woods", _converter.ConvertDialogCompressed("Pay 100 rupees open 1 chest. Are you lucky?\nSo, play game?\n  ≥ Play\n    Never!\n{CHOICE}") },
        { "kakariko_flophouse_man_no_flippers", _converter.ConvertDialogCompressed("I sure do have a lot of beds.\n\nZora is a cheapskate and will try to sell you his trash for 500 rupees…") },
        { "kakariko_flophouse_man", _converter.ConvertDialogCompressed("I sure do have a lot of beds.\n\nDid you know if you played the flute in the center of town things could happen?") },
        { "menu_start_2", _converter.ConvertDialogCompressed("{MENU}\n{SPEED0}\n≥@'s House\n Sanctuary\n{CHOICE3}", false) },
        { "menu_start_3", _converter.ConvertDialogCompressed("{MENU}\n{SPEED0}\n≥@'s House\n Sanctuary\n Mountain Cave\n{CHOICE2}", false) },
        { "menu_pause", _converter.ConvertDialogCompressed("{SPEED0}\n≥Continue\n Save and Quit\n{CHOICE3}", false) },
        { "game_digging_choice", _converter.ConvertDialogCompressed("Have 80 Rupees? Want to play digging game?\n  ≥Yes\n   No\n{CHOICE}") },
        { "game_digging_start", _converter.ConvertDialogCompressed("Okay, use the shovel with Y!") },
        { "game_digging_no_cash", _converter.ConvertDialogCompressed("Shovel rental is 80 rupees.\nI have all day") },
        { "game_digging_end_time", _converter.ConvertDialogCompressed("Time's up!\nTime for you to go.") },
        { "game_digging_come_back_later", _converter.ConvertDialogCompressed("Come back later, I have to bury things.") },
        { "game_digging_no_follower", _converter.ConvertDialogCompressed("Something is following you. I don't like.") },
        { "menu_start_4", _converter.ConvertDialogCompressed("{MENU}\n{SPEED0}\n≥@'s House\n Mountain Cave\n{CHOICE3}", false) },
        { "ganon_fall_in_alt", _converter.ConvertDialogCompressed("You think you\nare ready to\nface me?\n\nI will not die\n\nunless you\ncomplete your\ngoals. Dingus!") },
        { "ganon_phase_3_alt", _converter.ConvertDialogCompressed("Got wax in your ears? I cannot die!") },
        // 0x190
        { "sign_east_death_mountain_bridge", _converter.ConvertDialogCompressed("Glitched\ntournament\nwinners\n{HARP}\n~~~HMG 2023~~~\ntam\n\n~~~No Logic 2022~~~\nChexhuman\n\n~~~HMG 2021~~~\nKrithel\n\n~~~OWG 2019~~~\nGlan\n\n~~~OWG 2018~~~\nChristosOwen\nthe numpty") },
        { "fish_money", _converter.ConvertDialogCompressed("It's a secret to everyone.") },
        { "sign_ganons_tower", _converter.ConvertDialogCompressed("You need all 7 crystals to enter.") },
        { "sign_ganon", _converter.ConvertDialogCompressed("You need all 7 crystals to beat Ganon.") },
        { "ganon_phase_3_no_bow", _converter.ConvertDialogCompressed("You have no bow. Dingus!") },
        { "ganon_phase_3_no_silvers_alt", _converter.ConvertDialogCompressed("You can't best me without silver arrows!") },
        { "ganon_phase_3_no_silvers", _converter.ConvertDialogCompressed("You can't best me without silver arrows!") },
        { "ganon_phase_3_silvers", _converter.ConvertDialogCompressed("Oh no! Silver! My one true weakness!") },
        { "murahdahla", _converter.ConvertDialogCompressed("Hello @. I\nam Murahdahla, brother of\nSahasrahla and Aginah. Behold the power of\ninvisibility.\n{PAUSE3}\n… … …\nWait! you can see me? I knew I should have\nhidden in  a hollow tree.") },
        { "end_pad_data", _converter.ConvertDialogCompressed("") },
        { "terminator", [0xFF,  0xFF] }
    };

    /// <summary>
    /// Removing the various string that we don't want to actually appear in the randomizer.
    /// </summary>
    public void RemoveUnwanted()
    {
        string[] messages_to_zero = [
            // escort Messages
            "zelda_go_to_throne",
            "zelda_push_throne",
            "zelda_switch_room_pull",
            "zelda_switch_room",
            "zelda_sewers",
            "mountain_old_man_first",
            "mountain_old_man_deadend",
            "mountain_old_man_turn_right",
            "blind_not_that_way",

            // Note: Maiden text gets skipped by a change we will keep, so technically we don't need to replace them
            // Replacing them anyway to make more room in translation table
            "maiden_crystal_1",
            "maiden_crystal_2",
            "maiden_crystal_3",
            "maiden_crystal_4",
            "maiden_crystal_5",
            "maiden_crystal_6",
            "maiden_crystal_7",
            "maiden_ending",
            "maiden_confirm_undersood",
            "maiden_crystal_7_again",

            // Note: Item pickup text is skipped by a change we will keep, so technically we don't need to replace them
            // Replacing them anyway to make more room in translation table
            "item_get_lamp",
            "item_get_boomerang",
            "item_get_bow",
            "item_get_shovel",
            "item_get_magic_cape",
            "item_get_powder",
            "item_get_flippers",
            "item_get_power_gloves",
            "item_get_pendant_courage",
            "item_get_pendant_power",
            "item_get_pendant_wisdom",
            "item_get_mushroom",
            "item_get_book",
            "item_get_moonpearl",
            "item_get_compass",
            "item_get_map",
            "item_get_ice_rod",
            "item_get_fire_rod",
            "item_get_ether",
            "item_get_bombos",
            "item_get_quake",
            "item_get_hammer",
            "item_get_ocarina",
            "item_get_cane_of_somaria",
            "item_get_hookshot",
            "item_get_bombs",
            "item_get_bottle",
            "item_get_big_key",
            "item_get_titans_mitts",
            "item_get_magic_mirror",
            "item_get_fake_mastersword",
            "post_item_get_mastersword",
            "item_get_red_potion",
            "item_get_green_potion",
            "item_get_blue_potion",
            "item_get_bug_net",
            "item_get_blue_mail",
            "item_get_red_mail",
            "item_get_temperedsword",
            "item_get_mirror_shield",
            "item_get_cane_of_byrna",
            "item_get_pegasus_boots",
            "item_get_pendant_wisdom_alt",
            "item_get_pendant_power_alt",
            "pond_item_boomerang",
            "pond_item_bottle_filled",
            "blacksmiths_tempered_already",
            "item_get_whole_heart",
            "item_get_sanc_heart",
            "item_get_14_heart",
            "item_get_24_heart",
            "item_get_34_heart",
            "pond_item_test",
            "pond_will_upgrade",

            // misc
            "agahnim_final_meeting",
            "agahnim_hide_and_seek_found",
            "telepathic_sahasrahla_beat_agahnim",
            "telepathic_sahasrahla_beat_agahnim_no_pearl",
            "magic_bat_wake",
            "magic_bat_give_half_magic",
            "mountain_old_man_in_his_cave_pre_agahnim",
            "mountain_old_man_in_his_cave",
            "mountain_old_man_in_his_cave_post_agahnim",
            "priest_sanctuary_before_leave",
            "priest_sanctuary_before_pendants",
            "priest_sanctuary_after_pendants_before_master_sword",
            "zelda_sanctuary_before_leave",
            "zelda_before_pendants",
            "zelda_after_pendants_before_master_sword",
            "zelda_save_sewers",
            "zelda_save_lets_go",
            "zelda_save_repeat",
            "priest_info",
            "sanctuary_enter",
            "zelda_sanctuary_story",
            "sick_kid_trade",
            "hobo_item_get_bottle",
            "sahasrahla_have_courage",
            "sahasrahla_found",
            "sahasrahla_have_boots_no_icerod",
            "sahasrahla_bring_courage",
            "sahasrahla_quest_have_master_sword",
            "shop_darkworld_enter",
            "shop_first_time",
            "shop_buy_shield",
            "shop_buy_red_potion",
            "shop_buy_arrows",
            "shop_buy_bombs",
            "shop_buy_bee",
            "shop_buy_heart",
            "bomb_shop_big_bomb_buy",
            "item_get_big_bomb",
            "catfish",
            "catfish_after_item",
            "zora_meeting",
            "zora_tells_cost",
            "zora_get_flippers",
            //"zora_no_cash",
            "zora_no_buy_item",
            "agahnim_zelda_teleport",
            "agahnim_magic_running_away",
            "blind_in_the_cell",
            "kiki_first_extortion",
            "kiki_first_extortion_yes",
            "kiki_second_extortion",
            "kiki_second_extortion_yes",
            "witch_brewing_the_item",
            "barrier_breaking",
            "mountain_old_man_lost_and_alone",
            "mountain_old_man_drop_off",
            "pickup_purple_chest",
            "agahnim_defeated",
            "blacksmiths_collect_frog",
            "blacksmiths_what_you_want",
            "blacksmiths_get_sword",
            "blacksmiths_shop_saving",
            "blacksmiths_paywall",
            "blacksmiths_extra_okay",
            "blacksmiths_bogart_sword",
            "blacksmiths_tempered_already",
            "missing_magic",
            "witch_assistant_no_empty_bottle",
            "witch_assistant_informational",
            "bottle_vendor_choice",
            "bottle_vendor_get",
            "game_digging_choice",
            "game_digging_start",
            "dark_flute_boy_storytime",
            "dark_flute_boy_get_shovel",
            "thief_money",
            "game_chest_village_of_outcasts",
            "game_chest_village_of_outcasts_play",
            "hylian_text_2",
            "desert_entry_translated",
            "uncle_dying_sewer",
            "telepathic_intro",
            "desert_thief_sitting",
            "desert_thief_following",
            "desert_thief_question",
            "desert_thief_question_yes",
            "desert_thief_after_item_get",
            "desert_thief_reassure"
        ];

        foreach (string msg in messages_to_zero)
            _texts[msg] = _converter.ConvertDialogCompressed("{NOTEXT}", false);
    }
}
