namespace Randomizer.RomModifications;

using Randomizer.Graph;

/// <summary>
/// Overwrite all the text in the main portion of the ROM
/// from: 0xE0000 to: 0xE7355
/// 394 required things in table
/// but extended a bit by the randomizer
/// </summary>
internal sealed class Text
{
    private readonly Dictionary<string, byte[]> _texts;
    private readonly Dialog _converter;

    // Numbers in comments refer to US text numbers. Except for
    // the first few entries, JP1.0 text numbers are smaller by 2
    private static readonly string[] _dialogOrder =
    [
        "set_cursor",
        "set_cursor2",
        "game_over_menu",
        "var_test",
        "follower_no_enter",
        "choice_1_3",
        "choice_2_3",
        "choice_3_3",
        "choice_1_2",
        "choice_2_2",
        "uncle_leaving_text",
        "uncle_dying_sewer",
        // 0x10
        "tutorial_guard_1",
        "tutorial_guard_2",
        "tutorial_guard_3",
        "tutorial_guard_4",
        "tutorial_guard_5",
        "tutorial_guard_6",
        "tutorial_guard_7",
        "priest_sanctuary_before_leave",
        "sanctuary_enter",
        "zelda_sanctuary_story",
        "priest_sanctuary_before_pendants",
        "priest_sanctuary_after_pendants_before_master_sword",
        "priest_sanctuary_dying",
        "zelda_save_sewers",
        "priest_info",
        "zelda_sanctuary_before_leave",
        "telepathic_intro",
        // 0x20
        "telepathic_reminder",
        "zelda_go_to_throne",
        "zelda_push_throne",
        "zelda_switch_room_pull",
        "zelda_save_lets_go",
        "zelda_save_repeat",
        "zelda_before_pendants",
        "zelda_after_pendants_before_master_sword",
        "telepathic_zelda_right_after_master_sword",
        "zelda_sewers",
        "zelda_switch_room",
        "kakariko_saharalasa_wife",
        "kakariko_saharalasa_wife_sword_story",
        "kakariko_saharalasa_wife_closing",
        "kakariko_saharalasa_after_master_sword",
        "kakariko_alert_guards",
        // 0x30
        "sahasrahla_quest_have_pendants",
        "sahasrahla_quest_have_master_sword",
        "sahasrahla_quest_information",
        "sahasrahla_bring_courage",
        "sahasrahla_have_ice_rod",
        "telepathic_sahasrahla_beat_agahnim",
        "telepathic_sahasrahla_beat_agahnim_no_pearl",
        "sahasrahla_have_boots_no_icerod",
        "sahasrahla_have_courage",
        "sahasrahla_found",
        "sign_rain_north_of_links_house",
        "sign_north_of_links_house",
        "sign_path_to_death_mountain",
        "sign_lost_woods",
        "sign_zoras",
        "sign_outside_magic_shop",
        // 0x40
        "sign_death_mountain_cave_back",
        "sign_east_of_links_house",
        "sign_south_of_lumberjacks",
        "sign_east_of_desert",
        "sign_east_of_sanctuary",
        "sign_east_of_castle",
        "sign_north_of_lake",
        "sign_desert_thief",
        "sign_lumberjacks_house",
        "sign_north_kakariko",
        "witch_bring_mushroom",
        "witch_brewing_the_item",
        "witch_assistant_no_bottle",
        "witch_assistant_no_empty_bottle",
        "witch_assistant_informational",
        "witch_assistant_no_bottle_buying",
        // 0x50
        "potion_shop_no_empty_bottles",
        "item_get_lamp",
        "item_get_boomerang",
        "item_get_bow",
        "item_get_shovel",
        "item_get_magic_cape",
        "item_get_powder",
        "item_get_flippers",
        "item_get_power_gloves",
        "item_get_pendant_courage",
        "item_get_pendant_power",
        "item_get_pendant_wisdom",
        "item_get_mushroom",
        "item_get_book",
        "item_get_moonpearl",
        "item_get_compass",
        // 0x60
        "item_get_map",
        "item_get_ice_rod",
        "item_get_fire_rod",
        "item_get_ether",
        "item_get_bombos",
        "item_get_quake",
        "item_get_hammer",
        "item_get_ocarina",
        "item_get_cane_of_somaria",
        "item_get_hookshot",
        "item_get_bombs",
        "item_get_bottle",
        "item_get_big_key",
        "item_get_titans_mitts",
        "item_get_magic_mirror",
        "item_get_fake_mastersword",
        // 0x70
        "post_item_get_mastersword",
        "item_get_red_potion",
        "item_get_green_potion",
        "item_get_blue_potion",
        "item_get_bug_net",
        "item_get_blue_mail",
        "item_get_red_mail",
        "item_get_temperedsword",
        "item_get_mirror_shield",
        "item_get_cane_of_byrna",
        "missing_big_key",
        "missing_magic",
        "item_get_pegasus_boots",
        "talking_tree_info_start",
        "talking_tree_info_1",
        "talking_tree_info_2",
        // 0x80
        "talking_tree_info_3",
        "talking_tree_info_4",
        "talking_tree_other",
        "item_get_pendant_power_alt",
        "item_get_pendant_wisdom_alt",
        "game_shooting_choice",
        "game_shooting_yes",
        "game_shooting_no",
        "game_shooting_continue",
        "pond_of_wishing",
        "pond_item_select",
        "pond_item_test",
        "pond_will_upgrade",
        "pond_item_test_no",
        "pond_item_test_no_no",
        "pond_item_boomerang",
        // 0x90
        "pond_item_shield",
        "pond_item_silvers",
        "pond_item_bottle_filled",
        "pond_item_sword",
        "pond_of_wishing_happiness",
        "pond_of_wishing_choice",
        "pond_of_wishing_bombs",
        "pond_of_wishing_arrows",
        "pond_of_wishing_full_upgrades",
        "mountain_old_man_first",
        "mountain_old_man_deadend",
        "mountain_old_man_turn_right",
        "mountain_old_man_lost_and_alone",
        "mountain_old_man_drop_off",
        "mountain_old_man_in_his_cave_pre_agahnim",
        "mountain_old_man_in_his_cave",
        // 0xA0
        "mountain_old_man_in_his_cave_post_agahnim",
        "tavern_old_man_awake",
        "tavern_old_man_unactivated_flute",
        "tavern_old_man_know_tree_unactivated_flute",
        "tavern_old_man_have_flute",
        "chicken_hut_lady",
        "running_man",
        "game_race_sign",
        "sign_bumper_cave",
        "sign_catfish",
        "sign_north_village_of_outcasts",
        "sign_south_of_bumper_cave",
        "sign_east_of_pyramid",
        "sign_east_of_bomb_shop",
        "sign_east_of_mire",
        "sign_village_of_outcasts",
        // 0xB0
        "sign_before_wishing_pond",
        "sign_before_catfish_area",
        "castle_wall_guard",
        "gate_guard",
        "telepathic_tile_eastern_palace",
        "telepathic_tile_tower_of_hera_floor_4",
        "hylian_text_1",
        "mastersword_pedestal_translated",
        "telepathic_tile_spectacle_rock",
        "telepathic_tile_swamp_entrance",
        "telepathic_tile_thieves_town_upstairs",
        "telepathic_tile_misery_mire",
        "hylian_text_2",
        "desert_entry_translated",
        "telepathic_tile_under_ganon",
        "telepathic_tile_palace_of_darkness",
        // 0xC0
        "telepathic_tile_desert_bonk_torch_room",
        "telepathic_tile_castle_tower",
        "telepathic_tile_ice_large_room",
        "telepathic_tile_turtle_rock",
        "telepathic_tile_ice_entrace",
        "telepathic_tile_ice_stalfos_knights_room",
        "telepathic_tile_tower_of_hera_entrance",
        "houlihan_room",
        "caught_a_bee",
        "caught_a_fairy",
        "no_empty_bottles",
        "game_race_boy_time",
        "game_race_girl",
        "game_race_boy_success",
        "game_race_boy_failure",
        "game_race_boy_already_won",
        // 0xD0
        "game_race_boy_sneaky",
        "bottle_vendor_choice",
        "bottle_vendor_get",
        "bottle_vendor_no",
        "bottle_vendor_already_collected",
        "bottle_vendor_bee",
        "bottle_vendor_fish",
        "hobo_item_get_bottle",
        "blacksmiths_what_you_want",
        "blacksmiths_paywall",
        "blacksmiths_extra_okay",
        "blacksmiths_tempered_already",
        "blacksmiths_temper_no",
        "blacksmiths_bogart_sword",
        "blacksmiths_get_sword",
        "blacksmiths_shop_before_saving",
        // 0xE0
        "blacksmiths_shop_saving",
        "blacksmiths_collect_frog",
        "blacksmiths_still_working",
        "blacksmiths_saving_bows",
        "blacksmiths_hammer_anvil",
        "dark_flute_boy_storytime",
        "dark_flute_boy_get_shovel",
        "dark_flute_boy_no_get_shovel",
        "dark_flute_boy_flute_not_found",
        "dark_flute_boy_after_shovel_get",
        "shop_fortune_teller_lw_hint_0",
        "shop_fortune_teller_lw_hint_1",
        "shop_fortune_teller_lw_hint_2",
        "shop_fortune_teller_lw_hint_3",
        "shop_fortune_teller_lw_hint_4",
        "shop_fortune_teller_lw_hint_5",
        // 0xF0
        "shop_fortune_teller_lw_hint_6",
        "shop_fortune_teller_lw_hint_7",
        "shop_fortune_teller_lw_no_rupees",
        "shop_fortune_teller_lw",
        "shop_fortune_teller_lw_post_hint",
        "shop_fortune_teller_lw_no",
        "shop_fortune_teller_lw_hint_8",
        "shop_fortune_teller_lw_hint_9",
        "shop_fortune_teller_lw_hint_10",
        "shop_fortune_teller_lw_hint_11",
        "shop_fortune_teller_lw_hint_12",
        "shop_fortune_teller_lw_hint_13",
        "shop_fortune_teller_lw_hint_14",
        "shop_fortune_teller_lw_hint_15",
        "dark_sanctuary",
        "dark_sanctuary_hint_0",
        // 0x100
        "dark_sanctuary_no",
        "dark_sanctuary_hint_1",
        "dark_sanctuary_yes",
        "dark_sanctuary_hint_2",
        "sick_kid_no_bottle",
        "sick_kid_trade",
        "sick_kid_post_trade",
        "desert_thief_sitting",
        "desert_thief_following",
        "desert_thief_question",
        "desert_thief_question_yes",
        "desert_thief_after_item_get",
        "desert_thief_reassure",
        "hylian_text_3",
        "tablet_ether_book",
        "tablet_bombos_book",
        // 0x110
        "magic_bat_wake",
        "magic_bat_give_half_magic",
        "intro_main",
        "intro_throne_room",
        "intro_zelda_cell",
        "intro_agahnim",
        "pickup_purple_chest",
        "bomb_shop",
        "bomb_shop_big_bomb",
        "bomb_shop_big_bomb_buy",
        "item_get_big_bomb",
        "kiki_second_extortion",
        "kiki_second_extortion_no",
        "kiki_second_extortion_yes",
        "kiki_first_extortion",
        "kiki_first_extortion_yes",
        // 0x120
        "kiki_first_extortion_no",
        "kiki_leaving_screen",
        "blind_in_the_cell",
        "blind_by_the_light",
        "blind_not_that_way",
        "aginah_l1sword_no_book",
        "aginah_l1sword_with_pendants",
        "aginah",
        "aginah_need_better_sword",
        "aginah_have_better_sword",
        "catfish",
        "catfish_after_item",
        // 0x12C
        "lumberjack_right",
        "lumberjack_left",
        "lumberjack_left_post_agahnim",
        "fighting_brothers_right",
        // 0x130
        "fighting_brothers_right_opened",
        "fighting_brothers_left",
        "maiden_crystal_1",
        "maiden_crystal_2",
        "maiden_crystal_3",
        "maiden_crystal_4",
        "maiden_crystal_5",
        "maiden_crystal_6",
        "maiden_crystal_7",
        "maiden_ending",
        "maiden_confirm_undersood",
        "barrier_breaking",
        "maiden_crystal_7_again",
        "agahnim_zelda_teleport",
        "agahnim_magic_running_away",
        "agahnim_hide_and_seek_found",
        // 0x140
        "agahnim_defeated",
        "agahnim_final_meeting",
        // 0x142
        "zora_meeting",
        "zora_tells_cost",
        "zora_get_flippers",
        "zora_no_cash",
        "zora_no_buy_item",
        "kakariko_saharalasa_grandson",
        "kakariko_saharalasa_grandson_next",
        "dark_palace_tree_dude",
        "fairy_wishing_ponds",
        "fairy_wishing_ponds_no",
        "pond_of_wishing_no",
        "pond_of_wishing_return_item",
        "pond_of_wishing_throw",
        "pond_pre_item_silvers",
        // 0x150
        "pond_of_wishing_great_luck",
        "pond_of_wishing_good_luck",
        "pond_of_wishing_meh_luck",
        // Repurposed to no items in Randomizer
        "pond_of_wishing_bad_luck",
        "pond_of_wishing_fortune",
        "item_get_14_heart",
        "item_get_24_heart",
        "item_get_34_heart",
        "item_get_whole_heart",
        "item_get_sanc_heart",
        "fairy_fountain_refill",
        "death_mountain_bullied_no_pearl",
        "death_mountain_bullied_with_pearl",
        "death_mountain_bully_no_pearl",
        "death_mountain_bully_with_pearl",
        "shop_darkworld_enter",
        // 0x160
        "game_chest_village_of_outcasts",
        "game_chest_no_cash",
        "game_chest_not_played",
        "game_chest_played",
        "game_chest_village_of_outcasts_play",
        "shop_first_time",
        "shop_already_have",
        "shop_buy_shield",
        "shop_buy_red_potion",
        "shop_buy_arrows",
        "shop_buy_bombs",
        "shop_buy_bee",
        "shop_buy_heart",
        "shop_first_no_bottle_buy",
        "shop_buy_no_space",
        "ganon_fall_in",
        // 0x170
        "ganon_phase_3",
        "lost_woods_thief",
        "blinds_hut_dude",
        "end_triforce",
        // 0x174
        "toppi_fallen",
        "kakariko_tavern_fisherman",
        "thief_money",
        "thief_desert_rupee_cave",
        "thief_ice_rupee_cave",
        "telepathic_tile_south_east_darkworld_cave",
        // 0x17A
        "cukeman",
        "cukeman_2",
        "potion_shop_no_cash",
        "kakariko_powdered_chicken",
        "game_chest_south_of_kakariko",
        "game_chest_play_yes",
        // 0x180
        "game_chest_play_no",
        "game_chest_lost_woods",
        "kakariko_flophouse_man_no_flippers",
        "kakariko_flophouse_man",
        "menu_start_2",
        "menu_start_3",
        "menu_pause",
        "game_digging_choice",
        "game_digging_start",
        "game_digging_no_cash",
        "game_digging_end_time",
        "game_digging_come_back_later",
        "game_digging_no_follower",
        "menu_start_4",
        "ganon_fall_in_alt",
        "ganon_phase_3_alt",
        // 0x190
        "sign_east_death_mountain_bridge",
        "fish_money",
        "sign_ganons_tower",
        "sign_ganon",
        "ganon_phase_3_no_bow",
        "ganon_phase_3_no_silvers_alt",
        "ganon_phase_3_no_silvers",
        "ganon_phase_3_silvers",
        "murahdahla",
        "end_pad_data",
        "terminator",
    ];

    // text that should not pause/wait for user input
    private static readonly string[] _noPauseDialog =
    [
        "game_over_menu",
        "var_test",
        "intro_main",
        "intro_throne_room",
        "intro_zelda_cell",
        "intro_agahnim",
        "menu_pause",
        "menu_start_2",
        "menu_start_3",
        "menu_start_4",
    ];

    public string Language { get; }

    public Text(string language)
    {
        Language = language;
        _converter = new();
        _texts = LoadTranslation(language);
    }

    public static bool IsValidKey(string key) => _dialogOrder.Contains(key);

    /// <summary>Updates a specific string in the table, including encoding the string.</summary>
    /// <param name="id">The ID of the string to update</param>
    /// <param name="value">the string to add to the table</param>
    public void SetString(string id, string value, bool pause = true, int maxBytes = 2046, int wrap = 19)
    {
        if (!IsValidKey(id))
            throw new Exception($"Attempted to update a non-existant text id ({id}).");

        _texts[id] = _converter.ConvertDialogCompressed(value, pause, maxBytes, wrap);
    }

    /// <summary>Updates a specific string in the table, given the raw bytes</summary>
    /// <param name="id">The ID of the string to update</param>
    /// <param name="rawvalue">The raw bytes to add to the table</param>
    public void SetStringRaw(string id, byte[] rawvalue)
    {
        // TODO: SetString throws, this just adds the key and doesn't care if the key is part of _dialogOrder
        _texts[id] = rawvalue;
    }

    public byte[] GetByteArray(bool pad = false)
    {
        var data = new List<byte>();
        foreach (string dialogKey in _dialogOrder)
            data.AddRange(_texts[dialogKey]);

        //Log::debug(sprintf("Localization free space: %s", 0x7355 - data.Count));

        if (data.Count > 0x7355)
            throw new Exception("Too BIG");
        if (pad)
            data.AddRange(Enumerable.Repeat((byte)0xFF, 0x7355 - data.Count));

        return [.. data];
    }

    private Dictionary<string, byte[]> LoadTranslation(string language)
    {
        var baseText = YamlReader.LoadDialogText(language);
        var compressedDialog = new Dictionary<string, byte[]>
        {
            // fixed data; language agnostic.
            { "set_cursor", [0xFB, 0xFC, 0x00, 0xF9, 0xFF, 0xFF, 0xFF, 0xF8, 0xFF, 0xFF, 0x99, 0xFE, 0x68] },
            { "set_cursor2", [0xFB, 0xFC, 0x00, 0xF8, 0xFF, 0xFF, 0xFF, 0xF9, 0xFF, 0xFF, 0x99, 0xFE, 0x68] },
            { "choice_1_3", [0xFB, 0xFC, 0x00, 0xF7, 0x99, 0xF8, 0xFF, 0xF9, 0xFF, 0xFE, 0x71] },
            { "choice_2_3", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0x99, 0xF9, 0xFF, 0xFE, 0x71] },
            { "choice_3_3", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0xFF, 0xF9, 0x99, 0xFE, 0x71] },
            { "choice_1_2", [0xFB, 0xFC, 0x00, 0xF7, 0x99, 0xF8, 0xFF, 0xFE, 0x72] },
            { "choice_2_2", [0xFB, 0xFC, 0x00, 0xF7, 0xFF, 0xF8, 0x99, 0xFE, 0x72] },
            { "end_pad_data", _converter.ConvertDialogCompressed("") },
            { "terminator", [0xFF, 0xFF] },
        };

        foreach (var (key, text) in baseText)
        {
            bool pause = !IsNoPause(key);
            compressedDialog[key] = _converter.ConvertDialogCompressed(text, pause);
        }

        return compressedDialog;
    }

    public static bool IsNoPause(string key) => _noPauseDialog.Contains(key);

    /// <summary>
    /// Removing the various string that we don't want to actually appear in the randomizer.
    /// </summary>
    public void RemoveUnwanted()
    {
        string[] messages_to_zero = [
            // escort Messages
            "zelda_go_to_throne",
            "zelda_push_throne",
            "zelda_switch_room_pull",
            "zelda_switch_room",
            "zelda_sewers",
            "mountain_old_man_first",
            "mountain_old_man_deadend",
            "mountain_old_man_turn_right",
            "blind_not_that_way",

            // Note: Maiden text gets skipped by a change we will keep, so technically we don't need to replace them
            // Replacing them anyway to make more room in translation table
            "maiden_crystal_1",
            "maiden_crystal_2",
            "maiden_crystal_3",
            "maiden_crystal_4",
            "maiden_crystal_5",
            "maiden_crystal_6",
            "maiden_crystal_7",
            "maiden_ending",
            "maiden_confirm_undersood",
            "maiden_crystal_7_again",

            // Note: Item pickup text is skipped by a change we will keep, so technically we don't need to replace them
            // Replacing them anyway to make more room in translation table
            "item_get_lamp",
            "item_get_boomerang",
            "item_get_bow",
            "item_get_shovel",
            "item_get_magic_cape",
            "item_get_powder",
            "item_get_flippers",
            "item_get_power_gloves",
            "item_get_pendant_courage",
            "item_get_pendant_power",
            "item_get_pendant_wisdom",
            "item_get_mushroom",
            "item_get_book",
            "item_get_moonpearl",
            "item_get_compass",
            "item_get_map",
            "item_get_ice_rod",
            "item_get_fire_rod",
            "item_get_ether",
            "item_get_bombos",
            "item_get_quake",
            "item_get_hammer",
            "item_get_ocarina",
            "item_get_cane_of_somaria",
            "item_get_hookshot",
            "item_get_bombs",
            "item_get_bottle",
            "item_get_big_key",
            "item_get_titans_mitts",
            "item_get_magic_mirror",
            "item_get_fake_mastersword",
            "post_item_get_mastersword",
            "item_get_red_potion",
            "item_get_green_potion",
            "item_get_blue_potion",
            "item_get_bug_net",
            "item_get_blue_mail",
            "item_get_red_mail",
            "item_get_temperedsword",
            "item_get_mirror_shield",
            "item_get_cane_of_byrna",
            "item_get_pegasus_boots",
            "item_get_pendant_wisdom_alt",
            "item_get_pendant_power_alt",
            "pond_item_boomerang",
            "pond_item_bottle_filled",
            "blacksmiths_tempered_already",
            "item_get_whole_heart",
            "item_get_sanc_heart",
            "item_get_14_heart",
            "item_get_24_heart",
            "item_get_34_heart",
            "pond_item_test",
            "pond_will_upgrade",

            // misc
            "agahnim_final_meeting",
            "agahnim_hide_and_seek_found",
            "telepathic_sahasrahla_beat_agahnim",
            "telepathic_sahasrahla_beat_agahnim_no_pearl",
            "magic_bat_wake",
            "magic_bat_give_half_magic",
            "mountain_old_man_in_his_cave_pre_agahnim",
            "mountain_old_man_in_his_cave",
            "mountain_old_man_in_his_cave_post_agahnim",
            "priest_sanctuary_before_leave",
            "priest_sanctuary_before_pendants",
            "priest_sanctuary_after_pendants_before_master_sword",
            "zelda_sanctuary_before_leave",
            "zelda_before_pendants",
            "zelda_after_pendants_before_master_sword",
            "zelda_save_sewers",
            "zelda_save_lets_go",
            "zelda_save_repeat",
            "priest_info",
            "sanctuary_enter",
            "zelda_sanctuary_story",
            "sick_kid_trade",
            "hobo_item_get_bottle",
            "sahasrahla_have_courage",
            "sahasrahla_found",
            "sahasrahla_have_boots_no_icerod",
            "sahasrahla_bring_courage",
            "sahasrahla_quest_have_master_sword",
            "shop_darkworld_enter",
            "shop_first_time",
            "shop_buy_shield",
            "shop_buy_red_potion",
            "shop_buy_arrows",
            "shop_buy_bombs",
            "shop_buy_bee",
            "shop_buy_heart",
            "bomb_shop_big_bomb_buy",
            "item_get_big_bomb",
            "catfish",
            "catfish_after_item",
            "zora_meeting",
            "zora_tells_cost",
            "zora_get_flippers",
            //"zora_no_cash",
            "zora_no_buy_item",
            "agahnim_zelda_teleport",
            "agahnim_magic_running_away",
            "blind_in_the_cell",
            "kiki_first_extortion",
            "kiki_first_extortion_yes",
            "kiki_second_extortion",
            "kiki_second_extortion_yes",
            "witch_brewing_the_item",
            "barrier_breaking",
            "mountain_old_man_lost_and_alone",
            "mountain_old_man_drop_off",
            "pickup_purple_chest",
            "agahnim_defeated",
            "blacksmiths_collect_frog",
            "blacksmiths_what_you_want",
            "blacksmiths_get_sword",
            "blacksmiths_shop_saving",
            "blacksmiths_paywall",
            "blacksmiths_extra_okay",
            "blacksmiths_bogart_sword",
            "blacksmiths_tempered_already",
            "missing_magic",
            "witch_assistant_no_empty_bottle",
            "witch_assistant_informational",
            "bottle_vendor_choice",
            "bottle_vendor_get",
            "game_digging_choice",
            "game_digging_start",
            "dark_flute_boy_storytime",
            "dark_flute_boy_get_shovel",
            "thief_money",
            "game_chest_village_of_outcasts",
            "game_chest_village_of_outcasts_play",
            "hylian_text_2",
            "desert_entry_translated",
            "uncle_dying_sewer",
            "telepathic_intro",
            "desert_thief_sitting",
            "desert_thief_following",
            "desert_thief_question",
            "desert_thief_question_yes",
            "desert_thief_after_item_get",
            "desert_thief_reassure"
        ];

        foreach (string msg in messages_to_zero)
            _texts[msg] = _converter.ConvertDialogCompressed("{NOTEXT}", false);
    }
}
