namespace RandomizerTests.Logic.Open.NoGlitches;

[TestClass]
public class IcePalaceTest : OpenNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Ice Palace - Big Key Chest", false, new string[] {  }],
        ["Ice Palace - Big Key Chest", false, new string[] { "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" }],

        ["Ice Palace - Compass Chest", false, new string[] {  }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],

        ["Ice Palace - Map Chest", false, new string[] {  }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" }],
        // map chest requires Hammer (and Mitts), it is on the other side of the big block surrounded by pegs.
        ["Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hookshot", "KeyD5" }],

        ["Ice Palace - Spike Room", false, new string[] {  }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hookshot", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "KeyD5", "BigKeyD5" }],
        ["Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "KeyD5", "BigKeyD5" }],


        ["Ice Palace - Freezor Chest", false, new string[] {  }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],

        ["Ice Palace - Iced T Room", false, new string[] {  }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],
        ["Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],

        ["Ice Palace - Big Chest", false, new string[] {  }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" }],

        ["Ice Palace - Boss", false, new string[] {  }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
