using AlttpRandomizer.Graph;

namespace RandomizerTests.Logic.Open.NoGlitches;

[TestClass]
public class IcePalaceTest
{
    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Ice Palace - Big Key Chest", false, new string[] {  } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Big Key Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" } },

        new object[] { "Ice Palace - Compass Chest", false, new string[] {  } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },

        new object[] { "Ice Palace - Map Chest", false, new string[] {  } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Map Chest", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "BigKeyD5" } },

        new object[] { "Ice Palace - Spike Room", false, new string[] {  } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hookshot", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "KeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hookshot", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "KeyD5", "BigKeyD5" } },
        new object[] { "Ice Palace - Spike Room", false, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "KeyD5", "BigKeyD5" } },


        new object[] { "Ice Palace - Freezor Chest", false, new string[] {  } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Freezor Chest", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },

        new object[] { "Ice Palace - Iced T Room", false, new string[] {  } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Iced T Room", true, new string[] { "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },

        new object[] { "Ice Palace - Big Chest", false, new string[] {  } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },
        new object[] { "Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword" } },

        new object[] { "Ice Palace - Boss", false, new string[] {  } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" } },
        new object[] { "Ice Palace - Boss", true, new string[] { "BigKeyD5", "MoonPearl", "Flippers", "TitansMitt", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" } },
    };
    [TestMethod]
    [DynamicData(nameof(TestData))]
    public void TestLogic(string location, bool expected, string[] inventory)
    {
        var randomizer = new Randomizer(new[]
        {
            new Dictionary<string, object>()
            {
                { "mode.state", "open" },
                { "logic", "NoGlitches" },
            }
        });
        randomizer.AssumeItems(inventory.Select(i => Item.Get(i, 0)));
        Assert.AreEqual(expected, randomizer.CanReachLocation($"{location}:0"));
    }
}
