namespace RandomizerTests.Logic.Open.NoGlitches;

[TestClass]
public class MiseryMireTest : OpenNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Misery Mire - Big Chest", false, new string[] {  }],
        ["Misery Mire - Big Chest", false, new string[] { "BigKeyD6", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Main Lobby Chest", false, new string[] {  }],
        ["Misery Mire - Main Lobby Chest", false, new string[] { "KeyD6", "MoonPearl", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Big Key Chest", false, new string[] {  }],
        ["Misery Mire - Big Key Chest", false, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Compass Chest", false, new string[] {  }],
        ["Misery Mire - Compass Chest", false, new string[] { "KeyD6", "KeyD6", "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Bridge Chest", false, new string[] {  }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Map Chest", false, new string[] {  }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Spike Chest", false, new string[] {  }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],

        ["Misery Mire - Boss", false, new string[] {  }],
        ["Misery Mire - Boss", false, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "UncleSword", "Hookshot" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "MasterSword", "Hookshot" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L3Sword", "Hookshot" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" }],
        ["Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "OcarinaActive", "TitansMitt", "Ether", "L4Sword", "Hookshot" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
