namespace RandomizerTests.Logic.Open.NoGlitches;

[TestClass]
public class ThievesTownTest : OpenNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Thieves' Town - Attic Chest", false, new string[] {  }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "TitansMitt", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "KeyD4", "BigKeyD4" }],

        ["Thieves' Town - Big Key Chest", false, new string[] {  }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Thieves' Town - Map Chest", false, new string[] {  }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Thieves' Town - Compass Chest", false, new string[] {  }],
        ["Thieves' Town - Compass Chest", false, new string[] { "TitansMitt" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Thieves' Town - Ambush Chest", false, new string[] {  }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "TitansMitt" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot" }],

        ["Thieves' Town - Big Chest", false, new string[] {  }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "TitansMitt", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hammer", "Hookshot", "KeyD4", "BigKeyD4" }],

        ["Thieves' Town - Blind's Cell", false, new string[] {  }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "TitansMitt", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "ProgressiveGlove", "Hammer", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "PowerGlove", "Hammer", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4" }],

        ["Thieves' Town - Boss", false, new string[] {  }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "PowerGlove", "Hammer", "BigKeyD4" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Hammer", "Hookshot", "BigKeyD4" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "Hammer", "BigKeyD4" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "TitansMitt", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "ProgressiveGlove", "Hookshot", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "PowerGlove", "Hookshot", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "AgahnimDefeated", "Flippers", "Hookshot", "BigKeyD4", "Hammer" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
