namespace RandomizerTests.Logic.Open.NoGlitches;

[TestClass]
public class TurtleRockTest : OpenNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Turtle Rock - Chain Chomps", false, new string[] {  }],
        ["Turtle Rock - Chain Chomps", false, new string[] { "OcarinaActive", "MagicMirror", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Quake", "UncleSword", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7" }],
        ["Turtle Rock - Chain Chomps", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7" }],

        ["Turtle Rock - Compass Chest", false, new string[] {  }],
        ["Turtle Rock - Compass Chest", false, new string[] { "OcarinaActive", "MagicMirror", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria" }],
        ["Turtle Rock - Compass Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria" }],

        ["Turtle Rock - Roller Room - Left", false, new string[] {  }],
        ["Turtle Rock - Roller Room - Left", false, new string[] { "OcarinaActive", "MagicMirror", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", false, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Left", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],

        ["Turtle Rock - Roller Room - Right", false, new string[] {  }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],
        ["Turtle Rock - Roller Room - Right", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "FireRod" }],

        ["Turtle Rock - Big Chest", false, new string[] {  }],
        ["Turtle Rock - Big Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Big Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Big Key Chest", false, new string[] {  }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],
        ["Turtle Rock - Big Key Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7" }],

        ["Turtle Rock - Crystaroller Room Chest", false, new string[] {  }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "OcarinaActive", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "OcarinaActive", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Crystaroller Room Chest", true, new string[] { "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Eye Bridge - Bottom Left", false, new string[] {  }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Eye Bridge - Bottom Right", false, new string[] {  }],
        ["Turtle Rock - Eye Bridge - Bottom Right", false, new string[] { "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Bottom Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Eye Bridge - Top Left", false, new string[] {  }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Left", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Eye Bridge - Top Right", false, new string[] {  }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "Cape", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "Cape", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "CaneOfByrna", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "CaneOfByrna", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "MirrorShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "MirrorShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Eye Bridge - Top Right", true, new string[] { "Lamp", "ProgressiveShield", "ProgressiveShield", "ProgressiveShield", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],

        ["Turtle Rock - Boss", false, new string[] {  }],
        ["Turtle Rock - Boss", false, new string[] { "FireRod", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Boss", false, new string[] { "IceRod", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Boss", true, new string[] { "HalfMagic", "Bottle", "IceRod", "FireRod", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Boss", true, new string[] { "HalfMagic", "Bottle", "IceRod", "FireRod", "Lamp", "MagicMirror", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Boss", true, new string[] { "HalfMagic", "Bottle", "IceRod", "FireRod", "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "UncleSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
        ["Turtle Rock - Boss", true, new string[] { "HalfMagic", "Bottle", "IceRod", "FireRod", "Lamp", "Hookshot", "MoonPearl", "TitansMitt", "Hammer", "Quake", "ProgressiveSword", "CaneOfSomaria", "KeyD7", "KeyD7", "KeyD7", "KeyD7", "BigKeyD7" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
