import { sql } from "drizzle-orm";
import { text, integer, sqliteTable } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("user", {
  id: text("id").notNull().primaryKey(),
  username: text("username").notNull().unique(),
  githubId: integer("github_id").unique(), // Assuming you might want GitHub OAuth later
  hashedPassword: text("hashed_password"), // For username/password auth
  role: text("role", { enum: ["user", "admin"] })
    .notNull()
    .default("user"),
});

export const sessions = sqliteTable("session", {
  id: text("id").notNull().primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id),
  expiresAt: integer("expires_at").notNull(),
});

// Holds immutable snapshots of randomizer option schemas and the base patch to ensure
// old permalinks render and patch correctly even after future updates.
export const randomizerVersions = sqliteTable("randomizer_version", {
  id: text("id").notNull().primaryKey(), // uuid
  // The randomizer/game identifier this snapshot targets (e.g., "alttpr", "z1r")
  randomizerId: text("randomizer_id"),
  // Human-readable tag or semver (e.g., "v1.2.3", "2025-09-11")
  versionTag: text("version_tag").notNull().unique(),
  // Full options metadata snapshot used at generation time (normalized MetadataSchema)
  optionsMetadata: text("options_metadata", { mode: "json" }).notNull(),
  // Post-generation settings snapshot keyed by game id
  postGenSettings: text("post_gen_settings", { mode: "json" }).notNull(),
  // Base patch (IPS/BPS) as base64 string (keeps it simple in SQLite)
  ipsBasePatchBase64: text("ips_base_patch_base64").notNull(),
  // Optional checksum for integrity/debugging
  basePatchSha256: text("base_patch_sha256"),
  // Git commit hash capturing the backend build used for this version
  gitCommitHash: text("git_commit_hash"),
  // Build timestamp recorded for the stored version artifact
  buildDate: integer("build_date", { mode: "timestamp" }),
  // Flag to indicate the currently active version (future seeds should use)
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

export const seeds = sqliteTable("seed", {
  id: text("id").notNull().primaryKey(), // This could be a unique ID generated by your backend or a hash
  options: text("options", { mode: "json" }).notNull(), // JSON object of options used
  patchData: text("patch_data", { mode: "json" }).notNull(), // Could be base64 string or other format for binary patch
  placementInfo: text("placement_info", { mode: "json" }).notNull(), // JSON object for item placement
  spoilerLog: text("spoiler_log", { mode: "json" }), // Optional spoiler log data
  // Optional reference to the randomizer version used when this seed was generated
  randomizerVersionId: text("randomizer_version_id").references(
    () => randomizerVersions.id,
  ),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

export const userSeeds = sqliteTable("user_seed", {
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  seedId: text("seed_id")
    .notNull()
    .references(() => seeds.id, { onDelete: "cascade" }),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

export const presets = sqliteTable("preset", {
  id: text("id").notNull().primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  options: text("options", { mode: "json" }).notNull(),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }),
  isSystem: integer("is_system", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});
