import { sql } from "drizzle-orm";
import {
  text,
  integer,
  sqliteTable,
  primaryKey,
  uniqueIndex,
  index,
} from "drizzle-orm/sqlite-core";

export const users = sqliteTable("user", {
  id: text("id").notNull().primaryKey(),
  username: text("username").notNull().unique(),
  githubId: integer("github_id").unique(), // Assuming you might want GitHub OAuth later
  hashedPassword: text("hashed_password"), // For username/password auth
  // Grants management of official seed presets (and future admin surfaces).
  isAdmin: integer("is_admin", { mode: "boolean" }).notNull().default(false),
});

// Personal access tokens for the public API. Only the SHA-256 hash of the
// secret is stored; the plain secret is shown once at creation time.
export const apiKeys = sqliteTable(
  "api_key",
  {
    id: text("id").notNull().primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    // First characters of the secret, for display/identification only.
    tokenPrefix: text("token_prefix").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(current_timestamp)`),
    lastUsedAt: integer("last_used_at", { mode: "timestamp" }),
    revokedAt: integer("revoked_at", { mode: "timestamp" }),
  },
  (t) => [index("api_key_user_idx").on(t.userId)],
);

export const sessions = sqliteTable("session", {
  id: text("id").notNull().primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => users.id),
  expiresAt: integer("expires_at").notNull(),
});

// Holds immutable snapshots of randomizer option schemas and the base patch to ensure
// old permalinks render and patch correctly even after future updates.
export const randomizerVersions = sqliteTable("randomizer_version", {
  id: text("id").notNull().primaryKey(), // uuid
  // The randomizer/game identifier this snapshot targets (e.g., "alttpr", "z1r")
  randomizerId: text("randomizer_id"),
  // Human-readable tag or semver (e.g., "v1.2.3", "2025-09-11")
  versionTag: text("version_tag").notNull().unique(),
  // Full options metadata snapshot used at generation time (normalized MetadataSchema)
  optionsMetadata: text("options_metadata", { mode: "json" }).notNull(),
  // Post-generation settings snapshot keyed by game id
  postGenSettings: text("post_gen_settings", { mode: "json" }).notNull(),
  // Base patch (IPS/BPS) as base64 string (keeps it simple in SQLite)
  ipsBasePatchBase64: text("ips_base_patch_base64").notNull(),
  // Optional checksum for integrity/debugging
  basePatchSha256: text("base_patch_sha256"),
  // Git commit hash capturing the backend build used for this version
  gitCommitHash: text("git_commit_hash"),
  // Build timestamp recorded for the stored version artifact
  buildDate: integer("build_date", { mode: "timestamp" }),
  // Flag to indicate the currently active version (future seeds should use)
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

export const seeds = sqliteTable("seed", {
  id: text("id").notNull().primaryKey(), // This could be a unique ID generated by your backend or a hash
  options: text("options", { mode: "json" }).notNull(), // JSON object of options used
  patchData: text("patch_data", { mode: "json" }).notNull(), // Could be base64 string or other format for binary patch
  placementInfo: text("placement_info", { mode: "json" }).notNull(), // JSON object for item placement
  spoilerLog: text("spoiler_log", { mode: "json" }), // Optional spoiler log data
  // Optional reference to the randomizer version used when this seed was generated
  randomizerVersionId: text("randomizer_version_id").references(
    () => randomizerVersions.id,
  ),
  // Optional seed-preset attribution. Intentionally no FKs: a seed's stored
  // configuration must never change when presets are edited or deleted.
  presetId: text("preset_id"),
  presetRevisionId: text("preset_revision_id"),
  // Whether the submitted configuration differed from the referenced revision
  // (computed server-side at generation time).
  differedFromRevision: integer("differed_from_revision", { mode: "boolean" }),
  configSchemaVersion: integer("config_schema_version"),
  // NormalizedConfig snapshot of the submitted configuration ("options" holds
  // the generator payload, which is lossy).
  settingsSnapshot: text("settings_snapshot", { mode: "json" }),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

// Named seed configurations. "official" presets are curated by admins and
// have no owner; "user" presets are private to their owner. Settings live in
// immutable revisions (configurationPresetRevisions); the preset points at
// its newest revision via currentRevisionId (no FK: circular reference with
// the revisions table — integrity is enforced in the presets service).
export const configurationPresets = sqliteTable(
  "configuration_preset",
  {
    id: text("id").notNull().primaryKey(),
    ownerUserId: text("owner_user_id").references(() => users.id, {
      onDelete: "cascade",
    }),
    scope: text("scope", { enum: ["official", "user"] }).notNull(),
    // Stable identifier for official presets; used as the seeding idempotency key.
    slug: text("slug").unique(),
    // Which config page this preset belongs to (canonical metadata id, e.g. "combo").
    configId: text("config_id").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    currentRevisionId: text("current_revision_id"),
    // Curation metadata for official presets.
    gameTags: text("game_tags", { mode: "json" }),
    difficultyTag: text("difficulty_tag"),
    isRecommended: integer("is_recommended", { mode: "boolean" })
      .notNull()
      .default(false),
    featured: integer("featured", { mode: "boolean" }).notNull().default(false),
    archived: integer("archived", { mode: "boolean" }).notNull().default(false),
    // Capability token for sharing a private preset by link; null = not
    // shared. Anyone with the token can load the preset's current revision.
    shareToken: text("share_token").unique(),
    displayOrder: integer("display_order").notNull().default(0),
    deletedAt: integer("deleted_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(current_timestamp)`),
    updatedAt: integer("updated_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (t) => [
    index("configuration_preset_owner_idx").on(t.ownerUserId),
    index("configuration_preset_config_idx").on(t.configId, t.scope),
  ],
);

// Immutable snapshots of a preset's settings. Rows are only ever inserted;
// "updating" a preset appends a new revision and moves currentRevisionId.
export const configurationPresetRevisions = sqliteTable(
  "configuration_preset_revision",
  {
    id: text("id").notNull().primaryKey(),
    presetId: text("preset_id")
      .notNull()
      .references(() => configurationPresets.id, { onDelete: "cascade" }),
    revisionNumber: integer("revision_number").notNull(),
    configSchemaVersion: integer("config_schema_version").notNull(),
    // NormalizedConfig JSON (see $lib/config/normalize).
    settings: text("settings", { mode: "json" }).notNull(),
    changeSummary: text("change_summary"),
    createdBy: text("created_by").references(() => users.id),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(current_timestamp)`),
    publishedAt: integer("published_at", { mode: "timestamp" }),
  },
  (t) => [
    uniqueIndex("configuration_preset_revision_unique").on(
      t.presetId,
      t.revisionNumber,
    ),
  ],
);

export const userPresetPreferences = sqliteTable("user_preset_preference", {
  userId: text("user_id")
    .notNull()
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  defaultPresetId: text("default_preset_id").references(
    () => configurationPresets.id,
    { onDelete: "set null" },
  ),
  lastUsedPresetId: text("last_used_preset_id").references(
    () => configurationPresets.id,
    { onDelete: "set null" },
  ),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});

export const userPresetFavorites = sqliteTable(
  "user_preset_favorite",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    presetId: text("preset_id")
      .notNull()
      .references(() => configurationPresets.id, { onDelete: "cascade" }),
    displayOrder: integer("display_order").notNull().default(0),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(current_timestamp)`),
  },
  (t) => [primaryKey({ columns: [t.userId, t.presetId] })],
);

export const userSeeds = sqliteTable("user_seed", {
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  seedId: text("seed_id")
    .notNull()
    .references(() => seeds.id, { onDelete: "cascade" }),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(current_timestamp)`),
});
