namespace RandomizerTests.Logic.Inverted.NoGlitches.DeathMountain;

[TestClass]
public class EastTest : InvertedNoGlitchesLogicTests
{
    public static IEnumerable<object[]> TestData => [
        ["Spiral Cave Item", false, new string[] {  }],
        ["Spiral Cave Item", false, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Spiral Cave Item", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Spiral Cave Item", false, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Spiral Cave Item", false, new string[] { "OcarinaInactive", "Hookshot", "MoonPearl" }],
        ["Spiral Cave Item", true, new string[] { "OcarinaInactive", "Hookshot", "MoonPearl", "ProgressiveGlove", "Hammer" }],
        ["Spiral Cave Item", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hookshot" }],
        ["Spiral Cave Item", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hookshot" }],
        ["Spiral Cave Item", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hookshot" }],
        ["Spiral Cave Item", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Spiral Cave Item", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Spiral Cave Item", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Spiral Cave Item", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Lower - Far Left", false, new string[] {  }],
        ["Paradox Cave Lower - Far Left", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Lower - Far Left", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Lower - Left", false, new string[] {  }],
        ["Paradox Cave Lower - Left", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Left", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Lower - Left", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Lower - Middle", false, new string[] {  }],
        ["Paradox Cave Lower - Middle", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Lower - Middle", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Lower - Right", false, new string[] {  }],
        ["Paradox Cave Lower - Right", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Right", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Lower - Right", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Lower - Far Right", false, new string[] {  }],
        ["Paradox Cave Lower - Far Right", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Lower - Far Right", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Upper - Left", false, new string[] {  }],
        ["Paradox Cave Upper - Left", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Left", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Upper - Left", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Paradox Cave Upper - Right", false, new string[] {  }],
        ["Paradox Cave Upper - Right", false, new string[] { "ProgressiveGlove", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Right", false, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "Hammer", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "ProgressiveGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "PowerGlove", "Lamp", "Hookshot", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "TitansMitt", "Lamp", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "OcarinaInactive", "ProgressiveGlove", "ProgressiveGlove", "MoonPearl" }],
        ["Paradox Cave Upper - Right", true, new string[] { "OcarinaInactive", "TitansMitt", "MoonPearl" }],

        ["Mimic Cave", false, new string[] {  }],
        ["Mimic Cave", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot" }],
        ["Mimic Cave", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot" }],
        ["Mimic Cave", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer" }],
        ["Mimic Cave", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer" }],
        ["Mimic Cave", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot" }],
        ["Mimic Cave", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot" }],
        ["Mimic Cave", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer" }],
        ["Mimic Cave", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer" }],

        ["Ether Tablet", false, new string[] {  }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L4Sword" }],
        ["Ether Tablet", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Ether Tablet", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L2Sword" }],
        ["Ether Tablet", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L3Sword" }],
        ["Ether Tablet", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer", "BookOfMudora", "L4Sword" }],

        ["Spectacle Rock", false, new string[] {  }],
        ["Spectacle Rock", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot" }],
        ["Spectacle Rock", true, new string[] { "OcarinaInactive", "MoonPearl", "PowerGlove", "Hammer", "Hookshot" }],
        ["Spectacle Rock", true, new string[] { "OcarinaInactive", "MoonPearl", "ProgressiveGlove", "ProgressiveGlove", "Hammer" }],
        ["Spectacle Rock", true, new string[] { "OcarinaInactive", "MoonPearl", "TitansMitt", "Hammer" }],
        ["Spectacle Rock", true, new string[] { "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot" }],
        ["Spectacle Rock", true, new string[] { "PowerGlove", "Lamp", "MoonPearl", "Hammer", "Hookshot" }],
        ["Spectacle Rock", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Lamp", "MoonPearl", "Hammer" }],
        ["Spectacle Rock", true, new string[] { "TitansMitt", "Lamp", "MoonPearl", "Hammer" }],
    ];

    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }
}
