namespace RandomizerTests.Logic.Standard.MajorGlitches;

[TestClass]
public sealed class IcePalaceTest : StandardMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Ice Palace - Big Key Chest", false, new string[] {  }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "MoonPearl", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Flippers", "Bottle", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "MagicMirror", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "CaneOfByrna", "TitansMitt", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Cape", "TitansMitt", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "TitansMitt", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "CaneOfByrna", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "Cape", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Big Key Chest", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],

        ["Ice Palace - Compass Chest", false, new string[] {  }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "MoonPearl" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bottle" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MagicMirror" }],
        ["Ice Palace - Compass Chest", true, new string[] { "TitansMitt" }],

        ["Ice Palace - Map Chest", false, new string[] {  }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "MoonPearl", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Flippers", "Bottle", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "CaneOfByrna", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "Cape", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "PowerGlove", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "CaneOfByrna", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "MagicMirror", "Cape", "PowerGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "CaneOfByrna", "TitansMitt", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Cape", "TitansMitt", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "TitansMitt", "Hammer", "Hookshot", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "CaneOfByrna", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "Cape", "ProgressiveGlove", "ProgressiveGlove", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Map Chest", true, new string[] { "ProgressiveGlove", "ProgressiveGlove", "Hammer", "Hookshot", "KeyD5" }],

        ["Ice Palace - Spike Room", false, new string[] {  }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "MoonPearl", "Hookshot", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "MoonPearl", "KeyD5", "KeyD5" }],
        ["Ice Palace - Spike Room", true, new string[] { "Flippers", "MoonPearl", "KeyD5", "KeyD5" }],

        ["Ice Palace - Freezor Chest", false, new string[] {  }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "FireRod" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "UncleSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "UncleSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "UncleSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "UncleSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "ProgressiveSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "ProgressiveSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "ProgressiveSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "ProgressiveSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "MasterSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "MasterSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "MasterSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "MasterSword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "L3Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "L3Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "L3Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "L3Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "MoonPearl", "L4Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "Flippers", "Bottle", "L4Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "MagicMirror", "L4Sword", "Bombos" }],
        ["Ice Palace - Freezor Chest", true, new string[] { "TitansMitt", "L4Sword", "Bombos" }],

        ["Ice Palace - Iced T Room", false, new string[] {  }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "MoonPearl" }],
        ["Ice Palace - Compass Chest", true, new string[] { "Flippers", "Bottle" }],
        ["Ice Palace - Compass Chest", true, new string[] { "MagicMirror" }],
        ["Ice Palace - Compass Chest", true, new string[] { "TitansMitt" }],

        ["Ice Palace - Big Chest", false, new string[] {  }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "Flippers", "Bottle" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "MagicMirror" }],
        ["Ice Palace - Big Chest", true, new string[] { "BigKeyD5", "TitansMitt" }],

        ["Ice Palace - Boss", false, new string[] {  }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "ProgressiveGlove", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "TitansMitt", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "MoonPearl", "PowerGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "Flippers", "Bottle", "PowerGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "ProgressiveGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "FireRod", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "FireRod", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "UncleSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "UncleSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "ProgressiveSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "MasterSword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "MasterSword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "L3Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "L3Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "L4Sword", "Hammer", "KeyD5", "KeyD5" }],
        ["Ice Palace - Boss", true, new string[] { "BigKeyD5", "MagicMirror", "PowerGlove", "Bombos", "L4Sword", "Hammer", "CaneOfSomaria", "KeyD5" }],
    ];
}
