namespace RandomizerTests.Logic.Standard.MajorGlitches;

[TestClass]
public sealed class MiseryMireTest : StandardMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory.Concat(new[] { "MireEntryEther" }).ToArray());
    }

    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Misery Mire - Big Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Chest", true, new string[] { "BigKeyD6", "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Main Lobby Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Main Lobby Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Big Key Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Big Key Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Compass Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "Lamp", "Bottle", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Compass Chest", true, new string[] { "KeyD6", "KeyD6", "KeyD6", "FireRod", "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Bridge Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Bridge Chest", true, new string[] { "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Map Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Map Chest", true, new string[] { "KeyD6", "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Spike Chest", false, new string[] {  } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "MoonPearl", "Ether", "L4Sword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Spike Chest", true, new string[] { "Bottle", "Ether", "L4Sword", "Hookshot" } },

        new object[] { "Misery Mire - Boss", false, new string[] {  } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "UncleSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "UncleSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "ProgressiveSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "ProgressiveSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "MasterSword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "MasterSword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "L3Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "L3Sword", "Hookshot" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "L4Sword", "PegasusBoots" } },
        new object[] { "Misery Mire - Boss", true, new string[] { "KeyD6", "KeyD6", "BigKeyD6", "Lamp", "CaneOfSomaria", "MoonPearl", "Flute", "TitansMitt", "Ether", "L4Sword", "Hookshot" } },

    };
}
