namespace RandomizerTests.Logic.Standard.MajorGlitches;

[TestClass]
public sealed class ThievesTownTest : StandardMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Thieves' Town - Attic", false, new string[] {  } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "MoonPearl", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithBee", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithFairy", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithRedPotion", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithGreenPotion", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithBluePotion", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "Bottle", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Attic", true, new string[] { "BottleWithGoldBee", "KeyD4", "BigKeyD4" } },

        new object[] { "Thieves' Town - Big Key Chest", false, new string[] {  } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithBee" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithFairy" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "Bottle" } },
        new object[] { "Thieves' Town - Big Key Chest", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Thieves' Town - Map Chest", false, new string[] {  } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "MoonPearl" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithBee" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithFairy" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "Bottle" } },
        new object[] { "Thieves' Town - Map Chest", true, new string[] { "BottleWithGoldBee" } },


        new object[] { "Thieves' Town - Compass Chest", false, new string[] {  } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "MoonPearl" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithBee" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithFairy" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "Bottle" } },
        new object[] { "Thieves' Town - Compass Chest", true, new string[] { "BottleWithGoldBee" } },


        new object[] { "Thieves' Town - Ambush Chest", false, new string[] {  } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithBee" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithFairy" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "Bottle" } },
        new object[] { "Thieves' Town - Ambush Chest", true, new string[] { "BottleWithGoldBee" } },


        new object[] { "Thieves' Town - Big Chest", false, new string[] {  } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithBee", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithFairy", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithRedPotion", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithGreenPotion", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithBluePotion", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "Bottle", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "BottleWithGoldBee", "Hammer", "KeyD4", "BigKeyD4" } },
        new object[] { "Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "Hammer", "KeyD4", "BigKeyD4" } },

        new object[] { "Thieves' Town - Blind's Cell", false, new string[] {  } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithBee", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithFairy", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithRedPotion", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithGreenPotion", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithBluePotion", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "Bottle", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "BottleWithGoldBee", "BigKeyD4" } },
        new object[] { "Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "BigKeyD4" } },

        new object[] { "Thieves' Town - Boss", false, new string[] {  } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "Hammer" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "ProgressiveSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "UncleSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "MasterSword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "L3Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "L4Sword" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "CaneOfByrna" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "CaneOfSomaria" } },
        new object[] { "Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "Hammer" } },
    };
}
