namespace RandomizerTests.Logic.Standard.MajorGlitches;

[TestClass]
public sealed class ThievesTownTest : StandardMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Thieves' Town - Attic Chest", false, new string[] {  }],
        ["Thieves' Town - Attic Chest", true, new string[] { "MoonPearl", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithBee", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithFairy", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithRedPotion", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithGreenPotion", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithBluePotion", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "Bottle", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Attic Chest", true, new string[] { "BottleWithGoldBee", "KeyD4", "BigKeyD4" }],

        ["Thieves' Town - Big Key Chest", false, new string[] {  }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "MoonPearl" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithBee" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithFairy" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "Bottle" }],
        ["Thieves' Town - Big Key Chest", true, new string[] { "BottleWithGoldBee" }],

        ["Thieves' Town - Map Chest", false, new string[] {  }],
        ["Thieves' Town - Map Chest", true, new string[] { "MoonPearl" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithBee" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithFairy" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Thieves' Town - Map Chest", true, new string[] { "Bottle" }],
        ["Thieves' Town - Map Chest", true, new string[] { "BottleWithGoldBee" }],


        ["Thieves' Town - Compass Chest", false, new string[] {  }],
        ["Thieves' Town - Compass Chest", true, new string[] { "MoonPearl" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithBee" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithFairy" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "Bottle" }],
        ["Thieves' Town - Compass Chest", true, new string[] { "BottleWithGoldBee" }],


        ["Thieves' Town - Ambush Chest", false, new string[] {  }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "MoonPearl" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithBee" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithFairy" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "Bottle" }],
        ["Thieves' Town - Ambush Chest", true, new string[] { "BottleWithGoldBee" }],


        ["Thieves' Town - Big Chest", false, new string[] {  }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithBee", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithFairy", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithRedPotion", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithGreenPotion", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithBluePotion", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "Bottle", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "BottleWithGoldBee", "Hammer", "KeyD4", "BigKeyD4" }],
        ["Thieves' Town - Big Chest", true, new string[] { "MoonPearl", "Hammer", "KeyD4", "BigKeyD4" }],

        ["Thieves' Town - Blind's Cell", false, new string[] {  }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithBee", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithFairy", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithRedPotion", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithGreenPotion", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithBluePotion", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "Bottle", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "BottleWithGoldBee", "BigKeyD4" }],
        ["Thieves' Town - Blind's Cell", true, new string[] { "MoonPearl", "BigKeyD4" }],

        ["Thieves' Town - Boss", false, new string[] {  }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "MoonPearl", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBee", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithFairy", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithRedPotion", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGreenPotion", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithBluePotion", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "Bottle", "BigKeyD4", "Hammer" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "ProgressiveSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "UncleSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "MasterSword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "L3Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "L4Sword" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "CaneOfByrna" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "CaneOfSomaria" }],
        ["Thieves' Town - Boss", true, new string[] { "KeyD4", "BottleWithGoldBee", "BigKeyD4", "Hammer" }],
    ];
}
