namespace RandomizerTests.Logic.Alttp.Inverted.MajorGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public sealed class LightWorldTest : InvertedMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Master Sword Pedestal", false, new string[] {  }],
        ["Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower" }],

        ["Link's Uncle", false, new string[] {  }],
        ["Link's Uncle", true, new string[] { "MoonPearl" }],
        ["Link's Uncle", true, new string[] { "BottleWithBee" }],
        ["Link's Uncle", true, new string[] { "BottleWithFairy" }],
        ["Link's Uncle", true, new string[] { "BottleWithRedPotion" }],
        ["Link's Uncle", true, new string[] { "BottleWithGreenPotion" }],
        ["Link's Uncle", true, new string[] { "BottleWithBluePotion" }],
        ["Link's Uncle", true, new string[] { "Bottle" }],
        ["Link's Uncle", true, new string[] { "BottleWithGoldBee" }],

        ["Secret Passage", false, new string[] {  }],
        ["Secret Passage", true, new string[] { "MoonPearl" }],
        ["Secret Passage", true, new string[] { "BottleWithBee" }],
        ["Secret Passage", true, new string[] { "BottleWithFairy" }],
        ["Secret Passage", true, new string[] { "BottleWithRedPotion" }],
        ["Secret Passage", true, new string[] { "BottleWithGreenPotion" }],
        ["Secret Passage", true, new string[] { "BottleWithBluePotion" }],
        ["Secret Passage", true, new string[] { "Bottle" }],
        ["Secret Passage", true, new string[] { "BottleWithGoldBee" }],

        ["King's Tomb", false, new string[] {  }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "MoonPearl" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithBee" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithFairy" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithRedPotion" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithGreenPotion" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithBluePotion" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "Bottle" }],
        ["King's Tomb", true, new string[] { "PegasusBoots", "BottleWithGoldBee" }],

        ["Floodgate Chest", false, new string[] {  }],
        ["Floodgate Chest", true, new string[] { "MoonPearl" }],
        ["Floodgate Chest", true, new string[] { "MagicMirror" }],
        ["Floodgate Chest", true, new string[] { "BottleWithBee" }],
        ["Floodgate Chest", true, new string[] { "BottleWithFairy" }],
        ["Floodgate Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Floodgate Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Floodgate Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Floodgate Chest", true, new string[] { "Bottle" }],
        ["Floodgate Chest", true, new string[] { "BottleWithGoldBee" }],

        ["Kakariko Tavern Item", true, new string[] {  }],

        ["Chicken House Item", false, new string[] {  }],
        ["Chicken House Item", true, new string[] { "MoonPearl" }],
        ["Chicken House Item", true, new string[] { "BottleWithBee" }],
        ["Chicken House Item", true, new string[] { "BottleWithFairy" }],
        ["Chicken House Item", true, new string[] { "BottleWithRedPotion" }],
        ["Chicken House Item", true, new string[] { "BottleWithGreenPotion" }],
        ["Chicken House Item", true, new string[] { "BottleWithBluePotion" }],
        ["Chicken House Item", true, new string[] { "Bottle" }],
        ["Chicken House Item", true, new string[] { "BottleWithGoldBee" }],

        ["Aginah's Cave", false, new string[] {  }],
        ["Aginah's Cave", true, new string[] { "MoonPearl" }],
        ["Aginah's Cave", true, new string[] { "BottleWithBee" }],
        ["Aginah's Cave", true, new string[] { "BottleWithFairy" }],
        ["Aginah's Cave", true, new string[] { "BottleWithRedPotion" }],
        ["Aginah's Cave", true, new string[] { "BottleWithGreenPotion" }],
        ["Aginah's Cave", true, new string[] { "BottleWithBluePotion" }],
        ["Aginah's Cave", true, new string[] { "Bottle" }],
        ["Aginah's Cave", true, new string[] { "BottleWithGoldBee" }],

        ["Sahasrahla's Hut - Left", false, new string[] {  }],
        ["Sahasrahla's Hut - Left", true, new string[] { "PegasusBoots" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "MoonPearl" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithBee" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithFairy" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithRedPotion" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithGreenPotion" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithBluePotion" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "Bottle" }],
        ["Sahasrahla's Hut - Left", true, new string[] { "BottleWithGoldBee" }],

        ["Sahasrahla's Hut - Middle", false, new string[] {  }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "PegasusBoots" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithBee" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithFairy" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithRedPotion" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithGreenPotion" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithBluePotion" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "Bottle" }],
        ["Sahasrahla's Hut - Middle", true, new string[] { "BottleWithGoldBee" }],

        ["Sahasrahla's Hut - Right", false, new string[] {  }],
        ["Sahasrahla's Hut - Right", true, new string[] { "PegasusBoots" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "MoonPearl" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithBee" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithFairy" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithRedPotion" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithGreenPotion" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithBluePotion" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "Bottle" }],
        ["Sahasrahla's Hut - Right", true, new string[] { "BottleWithGoldBee" }],

        ["Kakariko Well - Top", false, new string[] {  }],
        ["Kakariko Well - Top", true, new string[] { "MoonPearl" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithBee" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithFairy" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithRedPotion" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithGreenPotion" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithBluePotion" }],
        ["Kakariko Well - Top", true, new string[] { "Bottle" }],
        ["Kakariko Well - Top", true, new string[] { "BottleWithGoldBee" }],

        ["Kakariko Well - Left", true, new string[] {  }],

        ["Kakariko Well - Middle", true, new string[] {  }],

        ["Kakariko Well - Right", true, new string[] {  }],

        ["Kakariko Well - Bottom", true, new string[] {  }],

        ["Blind's Hideout - Top", false, new string[] {  }],
        ["Blind's Hideout - Top", true, new string[] { "MoonPearl" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithBee" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithFairy" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithRedPotion" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithGreenPotion" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithBluePotion" }],
        ["Blind's Hideout - Top", true, new string[] { "Bottle" }],
        ["Blind's Hideout - Top", true, new string[] { "BottleWithGoldBee" }],

        ["Blind's Hideout - Left", false, new string[] {  }],
        ["Blind's Hideout - Left", true, new string[] { "MagicMirror" }],
        ["Blind's Hideout - Left", true, new string[] { "MoonPearl" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithBee" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithFairy" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithRedPotion" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithGreenPotion" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithBluePotion" }],
        ["Blind's Hideout - Left", true, new string[] { "Bottle" }],
        ["Blind's Hideout - Left", true, new string[] { "BottleWithGoldBee" }],

        ["Blind's Hideout - Right", false, new string[] {  }],
        ["Blind's Hideout - Right", true, new string[] { "MagicMirror" }],
        ["Blind's Hideout - Right", true, new string[] { "MoonPearl" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithBee" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithFairy" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithRedPotion" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithGreenPotion" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithBluePotion" }],
        ["Blind's Hideout - Right", true, new string[] { "Bottle" }],
        ["Blind's Hideout - Right", true, new string[] { "BottleWithGoldBee" }],

        ["Blind's Hideout - Far Left", false, new string[] {  }],
        ["Blind's Hideout - Far Left", true, new string[] { "MagicMirror" }],
        ["Blind's Hideout - Far Left", true, new string[] { "MoonPearl" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithBee" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithFairy" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithRedPotion" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithGreenPotion" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithBluePotion" }],
        ["Blind's Hideout - Far Left", true, new string[] { "Bottle" }],
        ["Blind's Hideout - Far Left", true, new string[] { "BottleWithGoldBee" }],

        ["Blind's Hideout - Far Right", false, new string[] {  }],
        ["Blind's Hideout - Far Right", true, new string[] { "MoonPearl" }],
        ["Blind's Hideout - Far Right", true, new string[] { "MagicMirror" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithBee" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithFairy" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithRedPotion" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithGreenPotion" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithBluePotion" }],
        ["Blind's Hideout - Far Right", true, new string[] { "Bottle" }],
        ["Blind's Hideout - Far Right", true, new string[] { "BottleWithGoldBee" }],

        ["Bonk Rocks Item", false, new string[] {  }],
        ["Bonk Rocks Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithBee", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithFairy", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithRedPotion", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithBluePotion", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "Bottle", "PegasusBoots" }],
        ["Bonk Rocks Item", true, new string[] { "BottleWithGoldBee", "PegasusBoots" }],

        ["Mini Moldorm Cave - Far Left", false, new string[] {  }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithBee" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithFairy" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithRedPotion" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithGreenPotion" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithBluePotion" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "Bottle" }],
        ["Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithGoldBee" }],

        ["Mini Moldorm Cave - Left", false, new string[] {  }],
        ["Mini Moldorm Cave - Left", true, new string[] { "MoonPearl" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithBee" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithFairy" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithRedPotion" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithGreenPotion" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithBluePotion" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "Bottle" }],
        ["Mini Moldorm Cave - Left", true, new string[] { "BottleWithGoldBee" }],

        ["Mini Moldorm Cave - Right", false, new string[] {  }],
        ["Mini Moldorm Cave - Right", true, new string[] { "MoonPearl" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithBee" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithFairy" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithRedPotion" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithGreenPotion" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithBluePotion" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "Bottle" }],
        ["Mini Moldorm Cave - Right", true, new string[] { "BottleWithGoldBee" }],

        ["Mini Moldorm Cave - Far Right", false, new string[] {  }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithBee" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithFairy" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithRedPotion" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithGreenPotion" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithBluePotion" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "Bottle" }],
        ["Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithGoldBee" }],

        ["Ice Rod Cave Item", false, new string[] {  }],
        ["Ice Rod Cave Item", true, new string[] { "MoonPearl" }],
        ["Ice Rod Cave Item", true, new string[] { "BigRedBomb", "MagicMirror" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithBee" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithFairy" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithRedPotion" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithGreenPotion" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithBluePotion" }],
        ["Ice Rod Cave Item", true, new string[] { "Bottle" }],
        ["Ice Rod Cave Item", true, new string[] { "BottleWithGoldBee" }],

        ["Bottle Merchant", true, new string[] {  }],

        ["Sahasrahla's Hut - Sahasrahla", false, new string[] {  }],
        ["Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage" }],

        ["Magic Bat Item", false, new string[] {  }],
        ["Magic Bat Item", true, new string[] { "Powder", "MoonPearl" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithBee" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithFairy" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithRedPotion" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithGreenPotion" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithBluePotion" }],
        ["Magic Bat Item", true, new string[] { "Powder", "Bottle" }],
        ["Magic Bat Item", true, new string[] { "Powder", "BottleWithGoldBee" }],

        ["Sick Kid Item", false, new string[] {  }],
        ["Sick Kid Item", true, new string[] { "BottleWithBee" }],
        ["Sick Kid Item", true, new string[] { "BottleWithFairy" }],
        ["Sick Kid Item", true, new string[] { "BottleWithRedPotion" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGreenPotion" }],
        ["Sick Kid Item", true, new string[] { "BottleWithBluePotion" }],
        ["Sick Kid Item", true, new string[] { "Bottle" }],
        ["Sick Kid Item", true, new string[] { "BottleWithGoldBee" }],

        ["Hobo", false, new string[] {  }],
        ["Hobo", true, new string[] { "MoonPearl" }],
        ["Hobo", true, new string[] { "BottleWithBee" }],
        ["Hobo", true, new string[] { "BottleWithFairy" }],
        ["Hobo", true, new string[] { "BottleWithRedPotion" }],
        ["Hobo", true, new string[] { "BottleWithGreenPotion" }],
        ["Hobo", true, new string[] { "BottleWithBluePotion" }],
        ["Hobo", true, new string[] { "Bottle" }],
        ["Hobo", true, new string[] { "BottleWithGoldBee" }],

        ["Bombos Tablet", false, new string[] {  }],
        ["Bombos Tablet", true, new string[] { "BookOfMudora", "ProgressiveSword", "ProgressiveSword" }],
        ["Bombos Tablet", true, new string[] { "BookOfMudora", "L2Sword" }],
        ["Bombos Tablet", true, new string[] { "BookOfMudora", "L3Sword" }],
        ["Bombos Tablet", true, new string[] { "BookOfMudora", "L4Sword" }],

        ["King Zora", true, new string[] {  }],

        ["Lost Woods Hideout Item", false, new string[] {  }],
        ["Lost Woods Hideout Item", true, new string[] { "MoonPearl" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithBee" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithFairy" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithRedPotion" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithGreenPotion" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithBluePotion" }],
        ["Lost Woods Hideout Item", true, new string[] { "Bottle" }],
        ["Lost Woods Hideout Item", true, new string[] { "BottleWithGoldBee" }],

        ["Lumberjack Tree", false, new string[] {  }],
        ["Lumberjack Tree", true, new string[] { "DefeatAgahnim" }],

        ["Cave 45 Item", false, new string[] {  }],

        ["Graveyard Ledge", false, new string[] {  }],
        ["Graveyard Ledge", true, new string[] { "MoonPearl" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithBee" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithFairy" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithRedPotion" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithGreenPotion" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithBluePotion" }],
        ["Graveyard Ledge", true, new string[] { "Bottle" }],
        ["Graveyard Ledge", true, new string[] { "BottleWithGoldBee" }],

        ["Checkerboard Cave Item", false, new string[] {  }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "MoonPearl" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithBee" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithBee" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithBee" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithFairy" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithFairy" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithFairy" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithRedPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithRedPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithRedPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithGreenPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithGreenPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithGreenPotion" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithBluePotion" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithBluePotion" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithBluePotion" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "Bottle" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "Bottle" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "Bottle" }],
        ["Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithGoldBee" }],
        ["Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithGoldBee" }],
        ["Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithGoldBee" }],

        ["Mini Moldorm Cave - NPC", false, new string[] {  }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithBee" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithFairy" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithRedPotion" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithGreenPotion" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithBluePotion" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "Bottle" }],
        ["Mini Moldorm Cave - NPC", true, new string[] { "BottleWithGoldBee" }],

        ["Library", false, new string[] {  }],
        ["Library", true, new string[] { "PegasusBoots", "MoonPearl" }],
        ["Library", true, new string[] { "PegasusBoots", "MagicMirror" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithBee" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithFairy" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithRedPotion" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithGreenPotion" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithBluePotion" }],
        ["Library", true, new string[] { "PegasusBoots", "Bottle" }],
        ["Library", true, new string[] { "PegasusBoots", "BottleWithGoldBee" }],

        ["Mushroom", false, new string[] {  }],
        ["Mushroom", true, new string[] { "BottleWithBee" }],
        ["Mushroom", true, new string[] { "BottleWithFairy" }],
        ["Mushroom", true, new string[] { "BottleWithRedPotion" }],
        ["Mushroom", true, new string[] { "BottleWithGreenPotion" }],
        ["Mushroom", true, new string[] { "BottleWithBluePotion" }],
        ["Mushroom", true, new string[] { "Bottle" }],
        ["Mushroom", true, new string[] { "BottleWithGoldBee" }],

        ["Potion Shop", false, new string[] {  }],
        ["Potion Shop", true, new string[] { "Mushroom" }],

        ["Maze Race", true, new string[] {  }],

        ["Desert Ledge", true, new string[] {  }],

        ["Lake Hylia Island", true, new string[] {  }],

        ["Sunken Treasure", false, new string[] {  }],
        ["Sunken Treasure", true, new string[] { "MoonPearl" }],
        ["Sunken Treasure", true, new string[] { "MagicMirror" }],
        ["Sunken Treasure", true, new string[] { "BottleWithBee" }],
        ["Sunken Treasure", true, new string[] { "BottleWithFairy" }],
        ["Sunken Treasure", true, new string[] { "BottleWithRedPotion" }],
        ["Sunken Treasure", true, new string[] { "BottleWithGreenPotion" }],
        ["Sunken Treasure", true, new string[] { "BottleWithBluePotion" }],
        ["Sunken Treasure", true, new string[] { "Bottle" }],
        ["Sunken Treasure", true, new string[] { "BottleWithGoldBee" }],

        ["Zora's Domain Ledge Item", false, new string[] {  }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "Flippers" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],
        ["Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" }],

        ["Flute Spot", false, new string[] {  }],
        ["Flute Spot", true, new string[] { "Shovel", "MoonPearl" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithBee" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithFairy" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithRedPotion" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithGreenPotion" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithBluePotion" }],
        ["Flute Spot", true, new string[] { "Shovel", "Bottle" }],
        ["Flute Spot", true, new string[] { "Shovel", "BottleWithGoldBee" }],

        ["Waterfall Fairy - Left", false, new string[] {  }],
        ["Waterfall Fairy - Left", true, new string[] { "MoonPearl" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithBee", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithFairy", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithRedPotion", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithBluePotion", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "Bottle", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithGoldBee", "PegasusBoots" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithBee", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithFairy", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithRedPotion", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithGreenPotion", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithBluePotion", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "Bottle", "Flippers" }],
        ["Waterfall Fairy - Left", true, new string[] { "BottleWithGoldBee", "Flippers" }],

        ["Waterfall Fairy - Right", false, new string[] {  }],
        ["Waterfall Fairy - Right", true, new string[] { "MoonPearl" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithBee", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithFairy", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithRedPotion", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithBluePotion", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "Bottle", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithGoldBee", "PegasusBoots" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithBee", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithFairy", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithRedPotion", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithGreenPotion", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithBluePotion", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "Bottle", "Flippers" }],
        ["Waterfall Fairy - Right", true, new string[] { "BottleWithGoldBee", "Flippers" }],

        ["Bomb Shoppe Item", false, new string[] {  }],
        ["Bomb Shoppe Item", true, new string[] { "Crystal5", "Crystal6" }],

        ["Ganon", false, new string[] {  }],
    ];
}
