namespace RandomizerTests.Logic.Alttp.Inverted.MajorGlitches;

using RandomizerTests.Logic.Alttp;

[TestClass]
public sealed class SwampPalaceTest : InvertedMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Swamp Palace - Entrance Chest", false, new string[] {  }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "Flippers", "MagicMirror" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Entrance Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Big Chest", false, new string[] {  }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],

        ["Swamp Palace - Big Key Chest", false, new string[] {  }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Big Key Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Map Chest", false, new string[] {  }],
        ["Swamp Palace - Map Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Map Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - West Chest", false, new string[] {  }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - West Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Compass Chest", false, new string[] {  }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Compass Chest", true, new string[] { "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Flooded Room - Left", false, new string[] {  }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Left", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Flooded Room - Right", false, new string[] {  }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Flooded Room - Right", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Waterfall Room", false, new string[] {  }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "Hammer", "KeyD2", "BigKeyD2" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Waterfall Room", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],

        ["Swamp Palace - Boss", false, new string[] {  }],
        // AnyBottle Seems to not work with the code for canExtendMagic() right now.
        // Testing Instead via the Test below with both allowed Magical Weapons.
        ["Swamp Palace - Boss", false, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "IceRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "Hammer", "KeyD2" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BowAndArrows", "FireRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "HalfMagic", "FireRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "QuarterMagic", "FireRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "FireRod", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "BowAndArrows", "IceRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "HalfMagic", "IceRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "QuarterMagic", "IceRod", "MoonPearl", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithBee", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithFairy", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithRedPotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithBluePotion", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "Bottle", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "IceRod", "BottleWithGoldBee", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "UncleSword", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "ProgressiveSword", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "MasterSword", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L3Sword", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "Flippers", "MagicMirror", "KeyD2", "L4Sword", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
        ["Swamp Palace - Boss", true, new string[] { "Hookshot", "MoonPearl", "Flippers", "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyP3" }],
    ];
}
