version: "3.8"

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    build: null
    environment:
      - NODE_ENV=production
      - PRIVATE_DOTNET_API_BASE_URL=http://api:8080
      - DATABASE_URL=/data/production.db
      - PUBLIC_SPRITES_BASE_URL=${PUBLIC_SPRITES_BASE_URL:-https://alttpr.com/sprites}
    volumes:
      - frontend_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.front.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=letsencrypt
      - traefik.http.services.front.loadbalancer.server.port=3000
