namespace RandomizerTests.Logic.Inverted.MajorGlitches;

[TestClass]
public sealed class LightWorldTest : InvertedMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => new[]
    {
        new object[] { "Master Sword Pedestal", false, new string[] {  } },
        new object[] { "Master Sword Pedestal", true, new string[] { "PendantOfCourage", "PendantOfWisdom", "PendantOfPower" } },

        new object[] { "Link's Uncle", false, new string[] {  } },
        new object[] { "Link's Uncle", true, new string[] { "MoonPearl" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithBee" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithFairy" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Link's Uncle", true, new string[] { "Bottle" } },
        new object[] { "Link's Uncle", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Secret Passage", false, new string[] {  } },
        new object[] { "Secret Passage", true, new string[] { "MoonPearl" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithBee" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithFairy" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Secret Passage", true, new string[] { "Bottle" } },
        new object[] { "Secret Passage", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "King's Tomb", false, new string[] {  } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "MoonPearl" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithBee" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithFairy" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithRedPotion" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithGreenPotion" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithBluePotion" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "Bottle" } },
        new object[] { "King's Tomb", true, new string[] { "PegasusBoots", "BottleWithGoldBee" } },

        new object[] { "Floodgate Chest", false, new string[] {  } },
        new object[] { "Floodgate Chest", true, new string[] { "MoonPearl" } },
        new object[] { "Floodgate Chest", true, new string[] { "MagicMirror" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithBee" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithFairy" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Floodgate Chest", true, new string[] { "Bottle" } },
        new object[] { "Floodgate Chest", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Kakariko Tavern Item", true, new string[] {  } },

        new object[] { "Chicken House Item", false, new string[] {  } },
        new object[] { "Chicken House Item", true, new string[] { "MoonPearl" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithBee" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithFairy" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Chicken House Item", true, new string[] { "Bottle" } },
        new object[] { "Chicken House Item", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Aginah's Cave", false, new string[] {  } },
        new object[] { "Aginah's Cave", true, new string[] { "MoonPearl" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithBee" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithFairy" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Aginah's Cave", true, new string[] { "Bottle" } },
        new object[] { "Aginah's Cave", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Sahasrahla's Hut - Left", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "PegasusBoots" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "MoonPearl" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithBee" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithFairy" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "Bottle" } },
        new object[] { "Sahasrahla's Hut - Left", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Sahasrahla's Hut - Middle", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "PegasusBoots" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "MoonPearl" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithBee" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithFairy" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "Bottle" } },
        new object[] { "Sahasrahla's Hut - Middle", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Sahasrahla's Hut - Right", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "PegasusBoots" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "MoonPearl" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithBee" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithFairy" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "Bottle" } },
        new object[] { "Sahasrahla's Hut - Right", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Kakariko Well - Top", false, new string[] {  } },
        new object[] { "Kakariko Well - Top", true, new string[] { "MoonPearl" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithBee" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithFairy" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "Bottle" } },
        new object[] { "Kakariko Well - Top", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Kakariko Well - Left", true, new string[] {  } },

        new object[] { "Kakariko Well - Middle", true, new string[] {  } },

        new object[] { "Kakariko Well - Right", true, new string[] {  } },

        new object[] { "Kakariko Well - Bottom", true, new string[] {  } },

        new object[] { "Blind's Hideout - Top", false, new string[] {  } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "MoonPearl" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithBee" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithFairy" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "Bottle" } },
        new object[] { "Blind's Hideout - Top", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Blind's Hideout - Left", false, new string[] {  } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MagicMirror" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "MoonPearl" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithBee" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithFairy" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "Bottle" } },
        new object[] { "Blind's Hideout - Left", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Blind's Hideout - Right", false, new string[] {  } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MagicMirror" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "MoonPearl" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithBee" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithFairy" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "Bottle" } },
        new object[] { "Blind's Hideout - Right", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Blind's Hideout - Far Left", false, new string[] {  } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MagicMirror" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "MoonPearl" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithBee" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithFairy" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "Bottle" } },
        new object[] { "Blind's Hideout - Far Left", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Blind's Hideout - Far Right", false, new string[] {  } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MoonPearl" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "MagicMirror" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithBee" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithFairy" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "Bottle" } },
        new object[] { "Blind's Hideout - Far Right", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Bonk Rocks Item", false, new string[] {  } },
        new object[] { "Bonk Rocks Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithBee", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithFairy", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithRedPotion", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithBluePotion", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "Bottle", "PegasusBoots" } },
        new object[] { "Bonk Rocks Item", true, new string[] { "BottleWithGoldBee", "PegasusBoots" } },

        new object[] { "Mini Moldorm Cave - Far Left", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "MoonPearl" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithBee" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "Bottle" } },
        new object[] { "Mini Moldorm Cave - Far Left", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Mini Moldorm Cave - Left", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "MoonPearl" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithBee" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "Bottle" } },
        new object[] { "Mini Moldorm Cave - Left", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Mini Moldorm Cave - Right", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "MoonPearl" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithBee" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "Bottle" } },
        new object[] { "Mini Moldorm Cave - Right", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Mini Moldorm Cave - Far Right", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "MoonPearl" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithBee" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "Bottle" } },
        new object[] { "Mini Moldorm Cave - Far Right", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Ice Rod Cave Item", false, new string[] {  } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "MoonPearl" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BigRedBomb", "MagicMirror" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithBee" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithFairy" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "Bottle" } },
        new object[] { "Ice Rod Cave Item", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Bottle Merchant", true, new string[] {  } },

        new object[] { "Sahasrahla's Hut - Sahasrahla", false, new string[] {  } },
        new object[] { "Sahasrahla's Hut - Sahasrahla", true, new string[] { "PendantOfCourage" } },

        new object[] { "Magic Bat Item", false, new string[] {  } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "MoonPearl" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithBee" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithFairy" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithRedPotion" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithGreenPotion" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithBluePotion" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "Bottle" } },
        new object[] { "Magic Bat Item", true, new string[] { "Powder", "BottleWithGoldBee" } },

        new object[] { "Sick Kid Item", false, new string[] {  } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithBee" } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithFairy" } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sick Kid Item", true, new string[] { "Bottle" } },
        new object[] { "Sick Kid Item", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Hobo", false, new string[] {  } },
        new object[] { "Hobo", true, new string[] { "MoonPearl" } },
        new object[] { "Hobo", true, new string[] { "BottleWithBee" } },
        new object[] { "Hobo", true, new string[] { "BottleWithFairy" } },
        new object[] { "Hobo", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Hobo", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Hobo", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Hobo", true, new string[] { "Bottle" } },
        new object[] { "Hobo", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Bombos Tablet", false, new string[] {  } },
        new object[] { "Bombos Tablet", true, new string[] { "BookOfMudora", "ProgressiveSword", "ProgressiveSword" } },
        new object[] { "Bombos Tablet", true, new string[] { "BookOfMudora", "L2Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "BookOfMudora", "L3Sword" } },
        new object[] { "Bombos Tablet", true, new string[] { "BookOfMudora", "L4Sword" } },

        new object[] { "King Zora", true, new string[] {  } },

        new object[] { "Lost Woods Hideout Item", false, new string[] {  } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "MoonPearl" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithBee" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithFairy" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "Bottle" } },
        new object[] { "Lost Woods Hideout Item", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Lumberjack Tree", false, new string[] {  } },
        new object[] { "Lumberjack Tree", true, new string[] { "DefeatAgahnim" } },

        new object[] { "Cave 45 Item", false, new string[] {  } },

        new object[] { "Graveyard Ledge", false, new string[] {  } },
        new object[] { "Graveyard Ledge", true, new string[] { "MoonPearl" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithBee" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithFairy" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Graveyard Ledge", true, new string[] { "Bottle" } },
        new object[] { "Graveyard Ledge", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Checkerboard Cave Item", false, new string[] {  } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "MoonPearl" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "MoonPearl" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "MoonPearl" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithBee" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithBee" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithBee" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithFairy" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithFairy" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithFairy" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithRedPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithRedPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithRedPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithGreenPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithGreenPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithGreenPotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithBluePotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithBluePotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithBluePotion" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "Bottle" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "Bottle" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "Bottle" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "ProgressiveGlove", "BottleWithGoldBee" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "PowerGlove", "BottleWithGoldBee" } },
        new object[] { "Checkerboard Cave Item", true, new string[] { "TitansMitt", "BottleWithGoldBee" } },

        new object[] { "Mini Moldorm Cave - NPC", false, new string[] {  } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "MoonPearl" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithBee" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "Bottle" } },
        new object[] { "Mini Moldorm Cave - NPC", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Library", false, new string[] {  } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MoonPearl" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "MagicMirror" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithBee" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithFairy" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithRedPotion" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithGreenPotion" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithBluePotion" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "Bottle" } },
        new object[] { "Library", true, new string[] { "PegasusBoots", "BottleWithGoldBee" } },

        new object[] { "Mushroom", false, new string[] {  } },
        new object[] { "Mushroom", true, new string[] { "BottleWithBee" } },
        new object[] { "Mushroom", true, new string[] { "BottleWithFairy" } },
        new object[] { "Mushroom", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Mushroom", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Mushroom", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Mushroom", true, new string[] { "Bottle" } },
        new object[] { "Mushroom", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Potion Shop", false, new string[] {  } },
        new object[] { "Potion Shop", true, new string[] { "Mushroom" } },

        new object[] { "Maze Race", true, new string[] {  } },

        new object[] { "Desert Ledge", true, new string[] {  } },

        new object[] { "Lake Hylia Island", true, new string[] {  } },

        new object[] { "Sunken Treasure", false, new string[] {  } },
        new object[] { "Sunken Treasure", true, new string[] { "MoonPearl" } },
        new object[] { "Sunken Treasure", true, new string[] { "MagicMirror" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithBee" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithFairy" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithRedPotion" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithGreenPotion" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithBluePotion" } },
        new object[] { "Sunken Treasure", true, new string[] { "Bottle" } },
        new object[] { "Sunken Treasure", true, new string[] { "BottleWithGoldBee" } },

        new object[] { "Zora's Domain Ledge Item", false, new string[] {  } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "Flippers" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },
        new object[] { "Zora's Domain Ledge Item", true, new string[] { "MoonPearl", "PegasusBoots" } },

        new object[] { "Flute Spot", false, new string[] {  } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "MoonPearl" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithBee" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithFairy" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithRedPotion" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithGreenPotion" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithBluePotion" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "Bottle" } },
        new object[] { "Flute Spot", true, new string[] { "Shovel", "BottleWithGoldBee" } },

        new object[] { "Waterfall Fairy - Left", false, new string[] {  } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "MoonPearl" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithBee", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithFairy", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithRedPotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithBluePotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Bottle", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithGoldBee", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithBee", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithFairy", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithRedPotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithGreenPotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithBluePotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "Bottle", "Flippers" } },
        new object[] { "Waterfall Fairy - Left", true, new string[] { "BottleWithGoldBee", "Flippers" } },

        new object[] { "Waterfall Fairy - Right", false, new string[] {  } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "MoonPearl" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithBee", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithFairy", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithRedPotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithGreenPotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithBluePotion", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Bottle", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithGoldBee", "PegasusBoots" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithBee", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithFairy", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithRedPotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithGreenPotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithBluePotion", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "Bottle", "Flippers" } },
        new object[] { "Waterfall Fairy - Right", true, new string[] { "BottleWithGoldBee", "Flippers" } },

        new object[] { "Bomb Shoppe Item", false, new string[] {  } },
        new object[] { "Bomb Shoppe Item", true, new string[] { "Crystal5", "Crystal6" } },

        new object[] { "Ganon", false, new string[] {  } },
    };
}
