namespace RandomizerTests.Logic.Inverted.MajorGlitches;

[TestClass]
public sealed class TowerOfHeraTest : InvertedMajorGlitchesLogicTests
{
    [TestMethod]
    [DynamicData(nameof(TestData), DynamicDataDisplayName = nameof(GetLogicTestDisplayNames), DynamicDataDisplayNameDeclaringType = typeof(LogicTestBase))]
    public override void TestLogic(string location, bool expected, string[] inventory)
    {
        base.TestLogic(location, expected, inventory);
    }

    public static IEnumerable<object[]> TestData => [
        ["Tower Of Hera - Big Key Chest", false, new string[] {  }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "MoonPearl", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "MoonPearl", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithBee", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithBee", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithFairy", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithFairy", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithRedPotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithRedPotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithGreenPotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithGreenPotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithBluePotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithBluePotion", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Bottle", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Bottle", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "BottleWithGoldBee", "KeyP3" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "BottleWithGoldBee", "KeyP3" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Lamp", "MagicMirror", "UncleSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "FireRod", "MagicMirror", "UncleSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Lamp", "MagicMirror", "ProgressiveSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "FireRod", "MagicMirror", "ProgressiveSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Lamp", "MagicMirror", "MasterSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "FireRod", "MagicMirror", "MasterSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Lamp", "MagicMirror", "L3Sword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "FireRod", "MagicMirror", "L3Sword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Lamp", "MagicMirror", "L4Sword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "FireRod", "MagicMirror", "L4Sword" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "Lamp", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Big Key Chest", true, new string[] { "FireRod", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "KeyD6" }],

        ["Tower Of Hera - Basement Cage", false, new string[] {  }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MoonPearl" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithBee" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithFairy" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithRedPotion" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithGreenPotion" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithBluePotion" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Bottle" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "BottleWithGoldBee" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MagicMirror", "UncleSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MagicMirror", "ProgressiveSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MagicMirror", "MasterSword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MagicMirror", "L3Sword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "MagicMirror", "L4Sword" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Basement Cage", true, new string[] { "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],

        ["Tower Of Hera - Map Chest", false, new string[] {  }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MoonPearl" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithBee" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithFairy" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithRedPotion" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithGreenPotion" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithBluePotion" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Bottle" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "BottleWithGoldBee" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MagicMirror", "UncleSword" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MagicMirror", "ProgressiveSword" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MagicMirror", "MasterSword" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MagicMirror", "L3Sword" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "MagicMirror", "L4Sword" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Map Chest", true, new string[] { "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],

        ["Tower Of Hera - Compass Chest", false, new string[] {  }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MagicMirror", "UncleSword", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MagicMirror", "ProgressiveSword", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MagicMirror", "MasterSword", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MagicMirror", "L3Sword", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "MagicMirror", "L4Sword", "BigKeyP3" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6" }],
        ["Tower Of Hera - Compass Chest", true, new string[] { "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6" }],

        ["Tower Of Hera - Big Chest", false, new string[] {  }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MagicMirror", "UncleSword", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MagicMirror", "ProgressiveSword", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MagicMirror", "MasterSword", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MagicMirror", "L3Sword", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "MagicMirror", "L4Sword", "BigKeyP3" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Big Chest", true, new string[] { "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],

        ["Tower Of Hera - Boss", false, new string[] {  }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "Hammer", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "UncleSword", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "ProgressiveSword", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MasterSword", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L3Sword", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "MoonPearl", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithFairy", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithRedPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithGreenPotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithBluePotion", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "Bottle", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "L4Sword", "BottleWithGoldBee", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "UncleSword", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "ProgressiveSword", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "MasterSword", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "L3Sword", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "L4Sword", "BigKeyP3" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MoonPearl", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBee", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithFairy", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithRedPotion", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGreenPotion", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithBluePotion", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "Bottle", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "BottleWithGoldBee", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "PegasusBoots", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "PegasusBoots", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "PegasusBoots", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "PegasusBoots", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "PegasusBoots", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "Hookshot", "UncleSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "Hookshot", "ProgressiveSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "Hookshot", "MasterSword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "Hookshot", "L3Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
        ["Tower Of Hera - Boss", true, new string[] { "MagicMirror", "Ether", "Hookshot", "L4Sword", "KeyD6", "KeyD6", "KeyD6", "BigKeyD6" }],
    ];
}
