import { error, json, type RequestHandler } from "@sveltejs/kit";
import { customAlphabet } from "nanoid";
import { Argon2id } from "oslo/password";
import { eq } from "drizzle-orm";
import { db } from "$lib/server/db";
import { users } from "$lib/server/db/schema";
import { lucia } from "$lib/server/auth";
import { requireAdmin, requireSessionUser } from "$lib/server/auth-guards";

// Unambiguous alphabet (no 0/O, 1/l/I) — the password is read out or pasted
// to the user by an admin.
const generatePassword = customAlphabet(
  "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789",
  14,
);

// Reset a user's password to a fresh autogenerated one. The plaintext is
// returned exactly once for the admin to hand over; all of the user's
// sessions are invalidated. No email involved — deliberately, the site does
// not store email addresses.
export const POST: RequestHandler = async ({ params, locals }) => {
  requireSessionUser(locals);
  requireAdmin(locals);

  const rows = await db
    .select({ id: users.id, username: users.username })
    .from(users)
    .where(eq(users.id, params.id!))
    .limit(1);
  const user = rows[0];
  if (!user) {
    throw error(404, { message: "User not found." });
  }

  const password = generatePassword();
  const hashedPassword = await new Argon2id().hash(password);
  await db.update(users).set({ hashedPassword }).where(eq(users.id, user.id));
  await lucia.invalidateUserSessions(user.id);

  return json({ username: user.username, password });
};
